### ISSUE TITLE
Presto crash

### ISSUE THREAD

**Issue by NurdinPremji** [facebook/presto#1113]
I'm running presto 0.60 on top of hadoop 1.0.3 and I am occassionally getting crashes while running a job.

On the presto server I get a warning of the form:
2014-03-10T20:33:05.797-0400     WARN   ContinuousTaskInfoFetcher-20140311_003044_00028_cn7yu.1.1-1067498       com.facebook.presto.server.HttpRemoteTask       Error updating task 20140311_003044_00028_cn7yu.1.
1: http://172.16.20.7:8080/v1/task/20140311_003044_00028_cn7yu.1.1
java.lang.RuntimeException: java.io.IOException: Connection reset by peer
        at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:58) ~[http-client-0.85.jar:0.85]
...

and on the corresponding node I got an error of the form:
WARN   http-worker-1046502     org.eclipse.jetty.servlet.ServletHandler        /v1/task/20140311_003044_00028_cn7yu.5.0/results/ffff
ffff-ffff-ffff-ffff-fffffffffffb/0
io.airlift.slice.RuntimeIOException: org.eclipse.jetty.io.EofException
        at io.airlift.slice.OutputStreamSliceOutput.writeBytes(OutputStreamSliceOutput.java:132) ~[slice-0.2.jar:0.2-689bce6580986b646155eafdd3ed7648274050e3-689bce6
580986b646155eafdd3ed7648274050e3-20130617110631-0700]
...

How would I go about debugging this issue?

**Comment by cberner** [comment]
Could you test with version 0.100 and see if this is still a problem? We fixed a lot of issues that cause crashes in recently releases.
