### ISSUE TITLE
Implement use schema and use catalog on server side

### ISSUE THREAD

**Issue by zhenxiao** [facebook/presto#1264]
Not as stated in the user manual:
http://prestodb.io/docs/current/sql/use-schema.html

In the current code base, "Use Schema" and "Use Catalog" are not supported:

presto:default> use schema benchmark;
Query 20140428_191023_00006_6w4sw failed: USE statement is not supported
com.facebook.presto.sql.analyzer.SemanticException: USE statement is not supported
    at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitUseCollection(StatementAnalyzer.java:233)
    at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitUseCollection(StatementAnalyzer.java:91)
    at com.facebook.presto.sql.tree.UseCollection.accept(UseCollection.java:51)
    at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
    at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:49)
    at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:199)
    at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:184)
    at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:145)
    at com.facebook.presto.execution.SqlQueryManager$QueryStarter.run(SqlQueryManager.java:391)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)

A workaround is to specify the catalog and schema when starting the PrestoCli:
--catalog hive --schema benchmark

In the current code base, catalog and schema are presto client configurations, and presto client is passing them to the presto server for each query. After initialization, the presto client will never update its catalog or schema values.

Only change the code at presto server side does not work. eg. 
client ->(catalog0, schema0, "use schema1") -> server
server updates its session to schema1
client ->(catalog0, schema0, "show tables")-> server
server will do "show tables" still in schema0

To support "use catalog" and "use schema", we need to have presto server sending catalog or schema update response to the presto client.

Any thoughts or other solutions?

Before these being supported, the presto user manual should be updated to say that "Use Catalog" and "Use Schema" are not supported:
http://prestodb.io/docs/current/sql/use-schema.html

**Comment by cawallin** [comment]
superceded by #1998

**Comment by cawallin** [comment]
@cberner could you close this please?
