### ISSUE TITLE
HTTP client EOF exception

### ISSUE THREAD

**Issue by electrum** [facebook/presto#1372]
This happens infrequently and is hard to reproduce:

```
presto:di> select * from (explain select 123);
Error running command: java.io.EOFException
io.airlift.http.client.RuntimeIOException: java.io.EOFException
	at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:20)
	at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:53)
	at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:33)
	at io.airlift.http.client.jetty.JettyHttpClient.execute(JettyHttpClient.java:210)
	at com.facebook.presto.client.StatementClient.<init>(StatementClient.java:82)
	at com.facebook.presto.cli.QueryRunner.startInternalQuery(QueryRunner.java:63)
	at com.facebook.presto.cli.QueryRunner.startQuery(QueryRunner.java:58)
	at com.facebook.presto.cli.Console.process(Console.java:222)
	at com.facebook.presto.cli.Console.runConsole(Console.java:165)
	at com.facebook.presto.cli.Console.run(Console.java:94)
	at com.facebook.presto.cli.Presto.main(Presto.java:31)
Caused by: java.io.EOFException
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:203)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1268)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:129)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:91)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:103)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by woshidagouxiong** [comment]
Hi
have you fixed that problem about java.io.EOFException?
