### ISSUE TITLE
The error stack give a misleading error message

### ISSUE THREAD

**Issue by FanTn** [facebook/presto#1609]
When executing a SQL query that show "Unable to create input format org.apache.hadoop.mapred.TextInputFormat", can not find "org/apache/hadoop/conf/Configurable" classes based on the error stack from server.log, but after viewing the source code (com.facebook.presto.server.PluginManager.SimpleChildFirstClassLoader.loadClass(String name, boolean resolve) throws ClassNotFoundException ) the reason is  hadoop cluster has set lzo compression coding.The error stack give us a misleading error message.

ps. the Stack : 
com.facebook.presto.spi.PrestoException: Unable to create input format org.apache.hadoop.mapred.TextInputFormat
        at com.facebook.presto.hive.HiveSplitSourceProvider$HiveSplitSource.propagatePrestoException(HiveSplitSourceProvider.java:591) ~[na:na]
        at com.facebook.presto.hive.HiveSplitSourceProvider$HiveSplitSource.getNextBatch(HiveSplitSourceProvider.java:534) ~[na:na]
        at com.facebook.presto.execution.ConnectorAwareSplitSource.getNextBatch(ConnectorAwareSplitSource.java:46) ~[presto-main-0.75.jar:0.75]
        at com.facebook.presto.execution.SqlStageExecution.scheduleSourcePartitionedNodes(SqlStageExecution.java:632) [presto-main-0.75.jar:0.75]
        at com.facebook.presto.execution.SqlStageExecution.startTasks(SqlStageExecution.java:553) [presto-main-0.75.jar:0.75]
        at com.facebook.presto.execution.SqlStageExecution.access$200(SqlStageExecution.java:93) [presto-main-0.75.jar:0.75]
        at com.facebook.presto.execution.SqlStageExecution$4.run(SqlStageExecution.java:525) [presto-main-0.75.jar:0.75]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_45]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
Caused by: java.lang.RuntimeException: Unable to create input format org.apache.hadoop.mapred.TextInputFormat
        at com.facebook.presto.hive.HiveUtil.getInputFormat(HiveUtil.java:85) ~[na:na]
        at com.facebook.presto.hive.HiveSplitSourceProvider.loadPartitionSplits(HiveSplitSourceProvider.java:201) ~[na:na]
        at com.facebook.presto.hive.HiveSplitSourceProvider.access$100(HiveSplitSourceProvider.java:82) ~[na:na]
        at com.facebook.presto.hive.HiveSplitSourceProvider$2.run(HiveSplitSourceProvider.java:174) ~[na:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_45]
        at com.facebook.presto.hive.util.BoundedExecutor.executeOrMerge(BoundedExecutor.java:82) ~[na:na]
        at com.facebook.presto.hive.util.BoundedExecutor.access$000(BoundedExecutor.java:41) ~[na:na]
        at com.facebook.presto.hive.util.BoundedExecutor$1.run(BoundedExecutor.java:53) ~[na:na]
        ... 3 common frames omitted
Caused by: java.lang.RuntimeException: Error in configuring object
        at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109) ~[na:na]
        at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:75) ~[na:na]
        at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:133) ~[na:na]
        at com.facebook.presto.hive.HiveUtil.getInputFormat(HiveUtil.java:82) ~[na:na]
        ... 11 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_45]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_45]
        at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:106) ~[na:na]
        ... 14 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configurable
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.7.0_45]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[na:1.7.0_45]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.7.0_45]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[na:1.7.0_45]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[na:1.7.0_45]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.7.0_45]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_45]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_45]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_45]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_45]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_45]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_45]
        at com.facebook.presto.server.PluginManager$SimpleChildFirstClassLoader.loadClass(PluginManager.java:355) ~[presto-main-0.75.jar:0.75]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_45]
        at java.lang.Class.forName0(Native Method) ~[na:1.7.0_45]
        at java.lang.Class.forName(Class.java:270) ~[na:1.7.0_45]
        at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:1659) ~[na:na]
        at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:1624) ~[na:na]
        at org.apache.hadoop.io.compress.CompressionCodecFactory.getCodecClasses(CompressionCodecFactory.java:128) ~[na:na]
        at org.apache.hadoop.io.compress.CompressionCodecFactory.<init>(CompressionCodecFactory.java:175) ~[na:na]
        at org.apache.hadoop.mapred.TextInputFormat.configure(TextInputFormat.java:45) ~[na:na]
        ... 19 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configurable
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_45]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_45]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_45]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_45]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_45]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_45]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_45]

**Comment by cberner** [comment]
It looks like the problem is that we're not wrappering the result of `ClassLoaderSafeConnectorSplitManager.getPartitionSplits()` with a `ThreadContextClassLoader`
