### ISSUE TITLE
Exception during planning with duplicate columns in order by clause

### ISSUE THREAD

**Issue by martint** [facebook/presto#1621]
```
select x, x from (select 1 x)  order by 1, 2;
```

```
Query 20140902_180334_61089_w8f29 failed: Multiple entries with same key: x_2=ASC_NULLS_LAST and x_2=ASC_NULLS_LAST
java.lang.IllegalArgumentException: Multiple entries with same key: x_2=ASC_NULLS_LAST and x_2=ASC_NULLS_LAST
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104)
	at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254)
	at com.facebook.presto.sql.planner.QueryPlanner.sort(QueryPlanner.java:576)
	at com.facebook.presto.sql.planner.QueryPlanner.sort(QueryPlanner.java:551)
	at com.facebook.presto.sql.planner.QueryPlanner.visitQuerySpecification(QueryPlanner.java:134)
	at com.facebook.presto.sql.planner.QueryPlanner.visitQuerySpecification(QueryPlanner.java:73)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:99)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:24)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:256)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:80)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:99)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:24)
	at com.facebook.presto.sql.planner.QueryPlanner.planQueryBody(QueryPlanner.java:143)
	at com.facebook.presto.sql.planner.QueryPlanner.visitQuery(QueryPlanner.java:100)
	at com.facebook.presto.sql.planner.QueryPlanner.visitQuery(QueryPlanner.java:73)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:80)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:24)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:243)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:80)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:80)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:24)
	at com.facebook.presto.sql.planner.LogicalPlanner.createRelationPlan(LogicalPlanner.java:173)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:79)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:202)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:183)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:144)
	at com.facebook.presto.execution.SqlQueryManager$QueryStarter.run(SqlQueryManager.java:397)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by yuananf** [comment]
Fixed by #3018
