### ISSUE TITLE
Implement MAP construction functions

### ISSUE THREAD

**Issue by nezihyigitbasi** [facebook/presto#1830]
```
presto:nyigitbasi> select MAP(1, 2.0, 3, 4.0);
Query 20141017_193500_00043_np4te failed: Function map not registered
com.facebook.presto.spi.PrestoException: Function map not registered
        at com.facebook.presto.metadata.FunctionRegistry.resolveFunction(FunctionRegistry.java:376)
        at com.facebook.presto.metadata.MetadataManager.resolveFunction(MetadataManager.java:147)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:541)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:171)
        at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:67)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:168)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:884)
        at com.facebook.presto.sql.analyzer.TupleAnalyzer.analyzeSelect(TupleAnalyzer.java:863)
        at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:345)
        at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:123)
        at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:98)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:24)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:533)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:106)
        at com.facebook.presto.sql.tree.Query.accept(Query.java:80)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:24)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:52)
        at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:204)
        at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:189)
        at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:150)
        at com.facebook.presto.execution.SqlQueryManager$QueryStarter$QuerySubmitter$2.run(SqlQueryManager.java:465)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by nezihyigitbasi** [comment]
Fixed through #1841
