### ISSUE TITLE
Problems with ROW_NUMBER together with multiple order by fields

### ISSUE THREAD

**Issue by mhinkka** [facebook/presto#1833]
Related to an issue I noted earlier in presto google group: 
https://groups.google.com/d/msg/presto-users/5BI9Pb0mGN0/6ioSQn9O9SYJ

It seems that at least with Presto 0.77, using ROW_NUMBER with partitioning and ordered 
by more than one field causes errors similar to the following when processing tables having 
more than 10000 - 100000 rows (works on small tables):
Query 20141020_084228_00005_ty6jn failed: end index (16388) must not be greater than size (16386)

The numbers change after every run.

The used query is like this:
SELECT 
  ROW_NUMBER() OVER (PARTITION BY evt_case ORDER BY evt_timestamp ASC, evt_event ASC) AS evt_asc_rank 
FROM events;

Modifying the query by removing one of the ORDER BY-fields will fix the problem:
SELECT 
  ROW_NUMBER() OVER (PARTITION BY evt_case ORDER BY evt_timestamp ASC) AS evt_asc_rank 
FROM events;

Source data looks like this (100000 rows):

evt_case, evt_event, evt_timestamp
"3979092","603","1276268574"
"3979953","603","1276268574"
"3979445","603","1276268574"
"3979954","603","1276268574"
"3980284","607","1275897595"
"3980128","607","1275897595"
"3979446","607","1275897595"
"3979625","607","1275897595"
"3978926","607","1275897595"
"3979626","607","1275897595"
"3980129","607","1275897595"
"3978749","607","1275897595"
...

Server logs have errors like this:
2014-10-20T11:40:26.685+0300    ERROR   SplitRunner-15-61       com.facebook.presto.execution.TaskExecutor      Error processing Split 20141020_084011_00000_ty6jn.7.0-0 (start = 1413794423905, wall = 2773 ms, cpu = 27 ms, calls = 4)
java.lang.IndexOutOfBoundsException: end index (16391) must not be greater than size (16386)
        at io.airlift.slice.Preconditions.checkPositionIndexes(Preconditions.java:80) ~[slice-0.7.jar:0.7]
        at io.airlift.slice.Slice.checkIndexLength(Slice.java:984) ~[slice-0.7.jar:0.7]
        at io.airlift.slice.Slice.getLong(Slice.java:366) ~[slice-0.7.jar:0.7]
        at com.facebook.presto.spi.block.AbstractVariableWidthBlock.getLong(AbstractVariableWidthBlock.java:59) ~[presto-spi-0.77.jar:0.77]
        at com.facebook.presto.spi.type.BigintType.compareTo(BigintType.java:73) ~[presto-spi-0.77.jar:0.77]
        at com.facebook.presto.spi.block.SortOrder.compareBlockValue(SortOrder.java:62) ~[presto-spi-0.77.jar:0.77]
        at com.facebook.presto.$gen.PagesIndexComparator_139.compareTo(Unknown Source) ~[na:na]
        at com.facebook.presto.operator.PagesIndex$1.compare(PagesIndex.java:241) ~[presto-main-0.77.jar:0.77]
        at com.facebook.presto.operator.WindowOperator.getOutput(WindowOperator.java:281) ~[presto-main-0.77.jar:0.77]
        at com.facebook.presto.operator.Driver.process(Driver.java:330) ~[presto-main-0.77.jar:0.77]
        at com.facebook.presto.operator.Driver.processFor(Driver.java:272) ~[presto-main-0.77.jar:0.77]
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:541) ~[presto-main-0.77.jar:0.77]
        at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:444) ~[presto-main-0.77.jar:0.77]
        at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:578) ~[presto-main-0.77.jar:0.77]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]

The error war replicateable at least in a cluster having three workers and one dedicated coordinator.

The test environment is such that Presto 0.77 is running on Hive 0.13.1 and Hadoop 2.4.0. I also tested switching to Hadoop 1.2.1 but it didn't help.

I also tested with Presto 0.60 which seemed to work without problems.

**Comment by cberner** [comment]
Please re-open if you can reproduce this. If you can include a test query that reproduces it on the TPCH data that would be great! I tried and wasn't able to though with one like this `select row_number() over (partition by clerk order by orderkey asc, orderdate asc) from orders;`
