### ISSUE TITLE
could not fetch data from Kafka, error code is '6'

### ISSUE THREAD

**Issue by Du-Li** [facebook/presto#1940]
I am working a presto-kafka use case, which deposits data from an external kafka source to the presto db.  When querying the table, most of the time it reports "could not fetch data from Kafka, error code is '6'" and sometimes "table not found". But occasionally the query returns the right results.

According to the Kafka protocol guid, this error code 6 is thrown if the client attempts to send messages to a replica that is not the leader for some partition. It indicates that the clients metadata is out of date. From my server log, there are numerous errors such as the following:

"kafka.consumer.SimpleConsumer Reconnect due to socket error: null"

"com.facebook.presto.execution.TaskExecutor        Error processing Split 20141107_195411_00003_dvti2.1.0-9 (start = 1415390052299, wall = 914 ms, cpu = 0 ms, calls = 1)"

java.nio.channels.ClosedByInterruptException: null
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202) ~[na:1.7.0_17]
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:634) ~[na:1.7.0_17]
        at kafka.network.BlockingChannel.connect(BlockingChannel.scala:57) ~[na:na]
        at kafka.consumer.SimpleConsumer.connect(SimpleConsumer.scala:44) ~[na:na]
        at kafka.consumer.SimpleConsumer.reconnect(SimpleConsumer.scala:57) ~[na:na]
        at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:79) ~[na:na]
        at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:71) ~[na:na]

**Comment by cberner** [comment]
Did this fix get committed? Please re-open if not.
