### ISSUE TITLE
when a column has a number in middle of column label, like this  'onein1mon_term_type' has error. may by is't a bug

### ISSUE THREAD

**Issue by anywhy** [facebook/presto#1993]
it's error with presto 0.84 and hive-cdh5
when using jdbc or cli has same errors!

this is jdbc error:
Caused by: java.sql.SQLException: Query failed (#20141119_085227_00548_g5uab): Column 'onein1mon_term_type' cannot be resolved
	at com.facebook.presto.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1770)
	at com.facebook.presto.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:1721)
	at com.facebook.presto.jdbc.PrestoResultSet.<init>(PrestoResultSet.java:140)
	at com.facebook.presto.jdbc.PrestoStatement.executeQuery(PrestoStatement.java:49)
	at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.apache.ibatis.logging.jdbc.StatementLogger.invoke(StatementLogger.java:53)
	at $Proxy21.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.SimpleStatementHandler.query(SimpleStatementHandler.java:69)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at $Proxy19.query(Unknown Source)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:57)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:259)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:132)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:105)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:81)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:104)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:98)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:358)
	... 34 more
Caused by: com.facebook.presto.sql.analyzer.SemanticException: Column 'onein1mon_term_type' cannot be resolved
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.createMissingAttributeException(ExpressionAnalyzer.java:292)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.tryVisitRowFieldAccessor(ExpressionAnalyzer.java:256)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitQualifiedNameReference(ExpressionAnalyzer.java:239)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitQualifiedNameReference(ExpressionAnalyzer.java:180)
	at com.facebook.presto.sql.tree.QualifiedNameReference.accept(QualifiedNameReference.java:41)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:177)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:936)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.analyzeSelect(TupleAnalyzer.java:872)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:346)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:124)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:99)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:24)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:533)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:106)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:81)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:24)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:52)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:206)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:191)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:152)
	at com.facebook.presto.execution.SqlQueryManager$QueryStarter$QuerySubmitter$2.run(SqlQueryManager.java:490)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cberner** [comment]
This query seems to work fine for me: `select * from (values 1) t("a1a");` Could you provide an example that's not working for you, if this is still an issue?
