### ISSUE TITLE
when using JDBC dirver to query has a error

### ISSUE THREAD

**Issue by anywhy** [facebook/presto#2039]
2014-12-02T14:07:37.527+0800    ERROR   SplitRunner-3241-51133  com.facebook.presto.execution.TaskExecutor      Error processing Split 20141202_060710_00271_dmeqi.0.0-0 (start = 1417500431035, wall = 26492 ms, cpu = 296 ms, calls = 463)
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:158) ~[guava-18.0.jar:na]
        at com.facebook.presto.operator.RowNumberOperator.addInput(RowNumberOperator.java:192) ~[presto-main-0.83.jar:0.83]
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:357) ~[presto-main-0.83.jar:0.83]
        at com.facebook.presto.operator.Driver.processFor(Driver.java:283) ~[presto-main-0.83.jar:0.83]
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:557) ~[presto-main-0.83.jar:0.83]
        at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:444) ~[presto-main-0.83.jar:0.83]
        at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:578) ~[presto-main-0.83.jar:0.83]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_67]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_67]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]

**Comment by cberner** [comment]
Are you still seeing this issue? We've made some improvements to that code in more recently releases

**Comment by anywhy** [comment]
The new version is not
