### ISSUE TITLE
NPE when using max_by/min_by

### ISSUE THREAD

**Issue by martint** [facebook/presto#2040]
```
java.lang.NullPointerException
	at com.facebook.presto.spi.type.DoubleType.compareTo(DoubleType.java:72)
	at com.facebook.presto.operator.aggregation.MaxBy.combine(MaxBy.java:125)
	at com.facebook.presto.$gen.VarcharVarcharDoubleMaxByGroupedAccumulator_576.addIntermediate(Unknown Source)
	at com.facebook.presto.operator.HashAggregationOperator$Aggregator.processPage(HashAggregationOperator.java:388)
	at com.facebook.presto.operator.HashAggregationOperator$GroupByHashAggregationBuilder.processPage(HashAggregationOperator.java:296)
	at com.facebook.presto.operator.HashAggregationOperator$GroupByHashAggregationBuilder.access$200(HashAggregationOperator.java:263)
	at com.facebook.presto.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:212)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:357)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:283)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:557)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:444)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:578)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by martint** [comment]
@huanghuashou are you still working on this?

**Comment by huanghuashou** [comment]
Sorry for late, working on it now. Will provide a diff soon.

**Comment by lstyls** [comment]
Hi @martint, I'm going to be working on this one. I'm new to presto and DB engine development in general. Can you advise on how to repro the exception?

**Comment by martint** [comment]
I haven't been able to come up with a query that reproduces this deterministically. You might need to write a unit test that exercises the API of those functions directly.
