### ISSUE TITLE
run presto with no connector exception

### ISSUE THREAD

**Issue by aslldab1** [facebook/presto#2076]
When I run the PrestoServer class, It start failed with connector exception. This is the detailed exception.

2014-12-07T19:44:40.519+0800	ERROR	main	com.facebook.presto.server.PrestoServer	No factory for connector mysql
java.lang.IllegalArgumentException: No factory for connector mysql
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[jar:rsrc:guava-18.0.jar!/:na]
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:97) ~[rsrc:./:na]
	at com.facebook.presto.metadata.CatalogManager.loadCatalog(CatalogManager.java:88) ~[rsrc:./:na]
	at com.facebook.presto.metadata.CatalogManager.loadCatalogs(CatalogManager.java:70) ~[rsrc:./:na]
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:108) [rsrc:./:na]
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:60) [rsrc:./:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58) [presto-main.jar:na]

**Comment by wbchn** [comment]
I got this error when load properties, before the error, there are some infomation:
````
2015-03-05T19:37:58.993-0800	 INFO	main	com.facebook.presto.server.PluginManager	-- Finished loading plugin /mnt/presto-data/plugin/hive-cdh4 --
2015-03-05T19:37:58.994-0800	 INFO	main	com.facebook.presto.metadata.CatalogManager	-- Loading catalog etc/catalog/dbslave2.properties --
```

This error accour when **the db in properties could not be connect**, fix connection and will be ok.
