### ISSUE TITLE
Presto with concurrency

### ISSUE THREAD

**Issue by FanTn** [facebook/presto#2086]
Hi! 
I have 6 different queries. Each query is completed  with 20 second,but I run the 6 queries at the same time and the queries will finish with 3-5 minutes.I'd like to know why  is there such a big difference between them.

In the coordinator's server.log have found many error message like this : 

2014-12-09T18:38:09.468+0800     WARN   ContinuousTaskInfoFetcher-20141209_103755_00006_b79r9.2.3-1596  com.facebook.presto.server.HttpRemoteTask   Error updating task 20141209_103755_00006_b79r9.2.3: http://192.168.179.33:8090/v1/task/20141209_103755_00006_b79r9.2.3
java.lang.RuntimeException: Server at http://192.168.179.33:8090/v1/task/20141209_103755_00006_b79r9.2.3?summarize returned SERVICE_UNAVAILABLE
    at com.facebook.presto.server.HttpRemoteTask$SimpleHttpResponseHandler.onSuccess(HttpRemoteTask.java:738) [presto-main-0.83.jar:0.83]
    at com.facebook.presto.server.HttpRemoteTask$SimpleHttpResponseHandler.onSuccess(HttpRemoteTask.java:717) [presto-main-0.83.jar:0.83]
    at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319) [guava-18.0.jar:na]
    at io.airlift.concurrent.BoundedExecutor.executeOrMerge(BoundedExecutor.java:68) [concurrent-0.96.jar:0.96]
    at io.airlift.concurrent.BoundedExecutor.access$000(BoundedExecutor.java:27) [concurrent-0.96.jar:0.96]
    at io.airlift.concurrent.BoundedExecutor$1.run(BoundedExecutor.java:39) [concurrent-0.96.jar:0.96]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_45]
    at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]

These queries concurrently run multiple times,the scan table nodes are less and less.
ps. 
node-scheduler.max-splits-per-node=512
task.shard.max-threads=256
com.facebook.presto.execution.TaskExecutor.pendingSplits's size is 512.
The server have 32 cores.

@electrum
Thanks!!

**Comment by cberner** [comment]
We fixed a lot of communication issues in recent releases. Could you re-open this, if it's still an issue?

**Comment by justinjose28** [comment]
Hi,

We ran into this same issue while running queries concurrently. A single query to a hive table like 'select count(*) from true_metric_table' takes 1 sec. If there are two concurrent requests, it takes almost 2 seconds and if I run 'N' such queries concurrently, it almost takes N*Time taken for one request.

We are using presto version 0.118 and our hive table contains 130 million records stored in ORC format with zlib compression. Presto is running in a 4 node(60GB/8 core) cluster. 

Please let me know if you need more information.

**Comment by cberner** [comment]
What is the average CPU usage in your cluster when running one query? Presto is designed to use 100% of the CPU, so if 1 query uses it all, then it's expected that N queries would take N times as long
