### ISSUE TITLE
Bad error message for scalar subquery

### ISSUE THREAD

**Issue by electrum** [facebook/presto#2165]
```
presto> select (select 123);
Query 20141229_190248_09947_q9qf4 failed: not yet implemented: com.facebook.presto.sql.tree.SubqueryExpression
com.facebook.presto.spi.PrestoException: not yet implemented: com.facebook.presto.sql.tree.SubqueryExpression
	at com.facebook.presto.sql.planner.ExpressionInterpreter$Visitor.visitExpression(ExpressionInterpreter.java:791)
	at com.facebook.presto.sql.tree.AstVisitor.visitSubqueryExpression(AstVisitor.java:327)
	at com.facebook.presto.sql.tree.SubqueryExpression.accept(SubqueryExpression.java:34)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.planner.ExpressionInterpreter.optimize(ExpressionInterpreter.java:140)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.simplifyExpression(SimplifyExpressions.java:115)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter$$Lambda$112/1236990587.apply(Unknown Source)
	at com.google.common.collect.Maps$7.transformEntry(Maps.java:1812)
	at com.google.common.collect.Maps$10.getValue(Maps.java:1857)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:292)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:86)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:66)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:101)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:112)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:85)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:66)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:101)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:112)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:85)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:66)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:101)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:112)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:85)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:66)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:101)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.lambda$defaultRewrite$15(PlanRewriter.java:75)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext$$Lambda$109/665800274.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.defaultRewrite(PlanRewriter.java:76)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:40)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:22)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:79)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.rewriteWith(PlanRewriter.java:29)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions.optimize(SimplifyExpressions.java:63)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:88)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:210)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:191)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:152)
	at com.facebook.presto.execution.SqlQueryManager$QueryStarter$QuerySubmitter$2.run(SqlQueryManager.java:474)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by joy-yao** [comment]
Claiming this task.

**Comment by joy-yao** [comment]
Returning this task.

**Comment by martint** [comment]
Fixed
