### ISSUE TITLE
Create table fails with ARRAY type

### ISSUE THREAD

**Issue by snarayananqubole** [facebook/presto#2180]
Edit: Edited original issue. Turns out it didn't have anything with unnest.

```
presto:default> create table foo as select ARRAY[1,2] x;

Query 20150105_120821_00007_rk8ib, FAILED, 1 node
http://127.0.0.1:8081/v1/query/20150105_120821_00007_rk8ib?pretty
Splits: 3 total, 1 done (33.33%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 33% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
0:09 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20150105_120821_00007_rk8ib failed: java.lang.String cannot be cast to [Ljava.lang.Object;
java.lang.ClassCastException: java.lang.String cannot be cast to [Ljava.lang.Object;
	at org.apache.hadoop.hive.serde2.objectinspector.StandardListObjectInspector.getListLength(StandardListObjectInspector.java:86)
	at org.apache.hadoop.hive.ql.io.orc.WriterImpl$ListTreeWriter.write(WriterImpl.java:1441)
	at org.apache.hadoop.hive.ql.io.orc.WriterImpl$StructTreeWriter.write(WriterImpl.java:1390)
	at org.apache.hadoop.hive.ql.io.orc.WriterImpl.addRow(WriterImpl.java:2018)
	at org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat$OrcRecordWriter.write(OrcOutputFormat.java:85)
	at com.facebook.presto.hive.HiveRecordSink.finishRecord(HiveRecordSink.java:337)
	at com.facebook.presto.spi.RecordPageSink.appendPage(RecordPageSink.java:56)
	at com.facebook.presto.operator.TableWriterOperator.addInput(TableWriterOperator.java:145)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:357)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:283)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:563)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:443)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:577)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

RecordSink SPI doesn't support ARRAY type and tries to write a string. Hive's object inspector complains about mismatch in types.

**Comment by cawallin** [comment]
That query works now:
presto:default> create table foo as select ARRAY[1,2] x;
CREATE TABLE: 1 row

Query 20150729_030057_00020_knw79, FINISHED, 3 nodes
Splits: 8 total, 8 done (100.00%)
0:01 [0 rows, 0B] [0 rows/s, 0B/s]

presto:default> select * from foo;
   x    
--------
 [1, 2] 
(1 row)

Query 20150729_030103_00021_knw79, FINISHED, 3 nodes
Splits: 4 total, 4 done (100.00%)
0:00 [1 rows, 77B] [4 rows/s, 332B/s]

**Comment by cberner** [comment]
Thanks for going through all these @cawallin !
