### ISSUE TITLE
Support implicit coercions in VALUES

### ISSUE THREAD

**Issue by martint** [facebook/presto#2198]
```
VALUES 
   (1, 2), 
   (1.2, 3.4)
```

currently fails with:
```
Query 20150108_110048_00012_j5xif failed: Values rows have mismatched types: Expected: (bigint, bigint), Actual: (double, double)
com.facebook.presto.sql.analyzer.SemanticException: Values rows have mismatched types: Expected: (bigint, bigint), Actual: (double, double)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitValues(TupleAnalyzer.java:546)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitValues(TupleAnalyzer.java:133)
	at com.facebook.presto.sql.tree.Values.accept(Values.java:43)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:493)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:114)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:81)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:52)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:208)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:193)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:154)
	at com.facebook.presto.execution.SqlQueryManager$QueryStarter$QuerySubmitter$2.run(SqlQueryManager.java:470)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The engine should insert any necessary casts following the implicit coercion rules, effectively resolving it as:

```
VALUES 
   (CAST(1 AS DOUBLE), CAST(2 AS DOUBLE)), 
   (1.2, 3.4);
```

**Comment by losipiuk** [comment]
This seems to be fixed already
