### ISSUE TITLE
Checking whether an array<bigint> contains null fails

### ISSUE THREAD

**Issue by nezihyigitbasi** [facebook/presto#2207]
Check against ``array<double>`` works fine:
```
presto:nyigitbasi> select CONTAINS(ARRAY [1.0, 2.0], null);
 _col0 
-------
 NULL  
(1 row)
```

This doesn't work
```
presto:nyigitbasi> select CONTAINS(ARRAY [1, 2], null);
Query 20150109_175643_00065_segad failed: Function contains(array<double>,double):boolean argument 0 must evaluate to a array<double> (actual: array<bigint>)
com.facebook.presto.sql.analyzer.SemanticException: Function contains(array<double>,double):boolean argument 0 must evaluate to a array<double> (actual: array<bigint>)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.coerceType(ExpressionAnalyzer.java:801)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:632)

```

I guess the issue is since there is not an exact match against ``contains(array<bigint>,null)``, a coerced match is found against ``contains(array<double>,double)``, and query fails.

**Comment by cberner** [comment]
seems to be fixed in the most recent release
