### ISSUE TITLE
Array equality operator fails with null elements

### ISSUE THREAD

**Issue by nezihyigitbasi** [facebook/presto#2208]
```
presto:nyigitbasi> select array[null] = array[null];
Query 20150109_180744_00075_segad failed: null
java.lang.NullPointerException
        at com.facebook.presto.operator.scalar.ArrayEqualOperator.specialize(ArrayEqualOperator.java:52)
        at com.facebook.presto.metadata.FunctionRegistry.resolveFunction(FunctionRegistry.java:360)

```

**Comment by nezihyigitbasi** [comment]
With the ``0.98.SNAPSHOT`` version this is not a problem any more. Hit another problem though (will create a separate issue for it).

```
presto:default> select array[null] = array[null];
Query 20150318_200726_00004_yuyqq failed: ARRAY comparison not supported for arrays with null elements
```
