### ISSUE TITLE
maven build error: jacoco or doxia problem?

### ISSUE THREAD

**Issue by zqhxuyuan** [facebook/presto#2218]
when I build presto src code use : mvn clean install -DskipTests. here is errors : 
PS: My Env is Ubuntu14.10, jdk1.8.0_25, mvn:3.2.5
both 0.90-SNAPSHOT and 0.89 have below errors

--------------------------------------------------------------------------------------------------------------------------

[INFO] --- jacoco-maven-plugin:0.6.2.201302030002:report (report) @ presto-root ---
[WARNING] Error injecting: org.jacoco.maven.ReportMojo
java.lang.NoClassDefFoundError: org/apache/maven/doxia/sink/Sink
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663)
	at java.lang.Class.getDeclaredConstructors(Class.java:2012)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:99)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:657)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:875)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:798)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:281)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:213)
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:998)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1031)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:994)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1044)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:113)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:122)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:82)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:464)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:119)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.apache.maven.doxia.sink.Sink
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 54 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] presto-root ........................................ FAILURE [ 32.353 s]
[INFO] presto-spi ......................................... SKIPPED
[INFO] presto-client ...................................... SKIPPED
[INFO] presto-parser ...................................... SKIPPED
[INFO] presto-tpch ........................................ SKIPPED
[INFO] presto-main ........................................ SKIPPED
[INFO] presto-tests ....................................... SKIPPED
[INFO] presto-kafka ....................................... SKIPPED
[INFO] presto-cassandra ................................... SKIPPED
[INFO] presto-orc ......................................... SKIPPED
[INFO] presto-benchmark ................................... SKIPPED
[INFO] presto-hive ........................................ SKIPPED
[INFO] presto-hive-hadoop1 ................................ SKIPPED
[INFO] presto-hive-hadoop2 ................................ SKIPPED
[INFO] presto-hive-cdh4 ................................... SKIPPED
[INFO] presto-hive-cdh5 ................................... SKIPPED
[INFO] presto-example-http ................................ SKIPPED
[INFO] presto-raptor ...................................... SKIPPED
[INFO] presto-base-jdbc ................................... SKIPPED
[INFO] presto-mysql ....................................... SKIPPED
[INFO] presto-postgresql .................................. SKIPPED
[INFO] presto-ml .......................................... SKIPPED
[INFO] presto-jdbc ........................................ SKIPPED
[INFO] presto-cli ......................................... SKIPPED
[INFO] presto-benchmark-driver ............................ SKIPPED
[INFO] presto-server ...................................... SKIPPED
[INFO] presto-docs ........................................ SKIPPED
[INFO] presto-verifier .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:13 min
[INFO] Finished at: 2015-01-12T10:57:31+08:00
[INFO] Final Memory: 36M/204M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.6.2.201302030002:report (report) on project presto-root: Execution report of goal org.jacoco:jacoco-maven-plugin:0.6.2.201302030002:report failed: A required class was missing while executing org.jacoco:jacoco-maven-plugin:0.6.2.201302030002:report: org/apache/maven/doxia/sink/Sink
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.jacoco:jacoco-maven-plugin:0.6.2.201302030002
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/hadoop/repo/org/jacoco/jacoco-maven-plugin/0.6.2.201302030002/jacoco-maven-plugin-0.6.2.201302030002.jar
[ERROR] urls[1] = file:/home/hadoop/repo/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[2] = file:/home/hadoop/repo/org/codehaus/plexus/plexus-interpolation/1.8.1/plexus-interpolation-1.8.1.jar
[ERROR] urls[3] = file:/home/hadoop/repo/junit/junit/4.8.2/junit-4.8.2.jar
[ERROR] urls[4] = file:/home/hadoop/repo/org/codehaus/plexus/plexus-utils/1.5.6/plexus-utils-1.5.6.jar
[ERROR] urls[5] = file:/home/hadoop/repo/org/apache/maven/reporting/maven-reporting-api/2.1.0/maven-reporting-api-2.1.0.jar
[ERROR] urls[6] = file:/home/hadoop/repo/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.jar
[ERROR] urls[7] = file:/home/hadoop/repo/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.jar
[ERROR] urls[8] = file:/home/hadoop/repo/org/apache/maven/reporting/maven-reporting-impl/2.1/maven-reporting-impl-2.1.jar
[ERROR] urls[9] = file:/home/hadoop/repo/org/apache/maven/doxia/doxia-core/1.1.2/doxia-core-1.1.2.jar
[ERROR] urls[10] = file:/home/hadoop/repo/xerces/xercesImpl/2.8.1/xercesImpl-2.8.1.jar
[ERROR] urls[11] = file:/home/hadoop/repo/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
[ERROR] urls[12] = file:/home/hadoop/repo/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar
[ERROR] urls[13] = file:/home/hadoop/repo/commons-codec/commons-codec/1.2/commons-codec-1.2.jar
[ERROR] urls[14] = file:/home/hadoop/repo/org/apache/maven/doxia/doxia-site-renderer/1.1.2/doxia-site-renderer-1.1.2.jar
[ERROR] urls[15] = file:/home/hadoop/repo/org/apache/maven/doxia/doxia-decoration-model/1.1.2/doxia-decoration-model-1.1.2.jar
[ERROR] urls[16] = file:/home/hadoop/repo/org/apache/maven/doxia/doxia-module-xhtml/1.1.2/doxia-module-xhtml-1.1.2.jar
[ERROR] urls[17] = file:/home/hadoop/repo/org/apache/maven/doxia/doxia-module-fml/1.1.2/doxia-module-fml-1.1.2.jar
[ERROR] urls[18] = file:/home/hadoop/repo/org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.jar
[ERROR] urls[19] = file:/home/hadoop/repo/org/codehaus/plexus/plexus-velocity/1.1.7/plexus-velocity-1.1.7.jar
[ERROR] urls[20] = file:/home/hadoop/repo/org/apache/velocity/velocity/1.5/velocity-1.5.jar
[ERROR] urls[21] = file:/home/hadoop/repo/commons-collections/commons-collections/3.2/commons-collections-3.2.jar
[ERROR] urls[22] = file:/home/hadoop/repo/commons-validator/commons-validator/1.2.0/commons-validator-1.2.0.jar
[ERROR] urls[23] = file:/home/hadoop/repo/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar
[ERROR] urls[24] = file:/home/hadoop/repo/commons-digester/commons-digester/1.6/commons-digester-1.6.jar
[ERROR] urls[25] = file:/home/hadoop/repo/commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar
[ERROR] urls[26] = file:/home/hadoop/repo/oro/oro/2.0.8/oro-2.0.8.jar
[ERROR] urls[27] = file:/home/hadoop/repo/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar
[ERROR] urls[28] = file:/home/hadoop/repo/org/jacoco/org.jacoco.agent/0.6.2.201302030002/org.jacoco.agent-0.6.2.201302030002-runtime.jar
[ERROR] urls[29] = file:/home/hadoop/repo/org/jacoco/org.jacoco.core/0.6.2.201302030002/org.jacoco.core-0.6.2.201302030002.jar
[ERROR] urls[30] = file:/home/hadoop/repo/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar
[ERROR] urls[31] = file:/home/hadoop/repo/org/jacoco/org.jacoco.report/0.6.2.201302030002/org.jacoco.report-0.6.2.201302030002.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>com.facebook.presto:presto-root:0.90-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.apache.maven.doxia.sink.Sink
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by cberner** [comment]
Could not reproduce. Please reopen, if you're still seeing this
