### ISSUE TITLE
Current Hive version doesn't support binary type for Parquet

### ISSUE THREAD

**Issue by nezihyigitbasi** [facebook/presto#2224]
Currently Presto depends on ``Hive 0.13.1`` and support for the Parquet ``binary`` type isn't available in that release, see stack trace below. This support was added recently ([see this](https://github.com/apache/hive/commit/46f08ff3dc6894bf3882191b7c66e46806f2d103#diff-8c6363e90d442f239bc252a104f1bfedR105)) and Presto's shaded Hive should be updated once it's released (yep, ``Hive 0.14`` also doesn't include this patch, [see](https://github.com/apache/hive/blob/release-0.14.0/ql/src/java/org/apache/hadoop/hive/ql/io/parquet/serde/ArrayWritableObjectInspector.java))

```
Query 20150114_170919_00453_dzhr7 failed: Unknown field type: binary
java.lang.UnsupportedOperationException: Unknown field type: binary
	at org.apache.hadoop.hive.ql.io.parquet.serde.ArrayWritableObjectInspector.getObjectInspector(ArrayWritableObjectInspector.java:108)
	at org.apache.hadoop.hive.ql.io.parquet.serde.ArrayWritableObjectInspector.<init>(ArrayWritableObjectInspector.java:60)
	at org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe.initialize(ParquetHiveSerDe.java:113)
	at com.facebook.presto.hive.HiveRecordSink.initializeSerializer(HiveRecordSink.java:230)
	at com.facebook.presto.hive.HiveRecordSink.<init>(HiveRecordSink.java:112)
	at com.facebook.presto.hive.HiveClient.getRecordSink(HiveClient.java:767)
	at com.facebook.presto.spi.classloader.ClassLoaderSafeConnectorRecordSinkProvider.getRecordSink(ClassLoaderSafeConnectorRecordSinkProvider.java:39)
	at com.facebook.presto.operator.RecordSinkManager.getRecordSink(RecordSinkManager.java:40)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.getRecordSink(LocalExecutionPlanner.java:1534)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.access$1900(LocalExecutionPlanner.java:174)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitTableWriter(LocalExecutionPlanner.java:1317)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitTableWriter(LocalExecutionPlanner.java:344)
	at com.facebook.presto.sql.planner.plan.TableWriterNode.accept(TableWriterNode.java:116)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitSink(LocalExecutionPlanner.java:1285)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitSink(LocalExecutionPlanner.java:344)
	at com.facebook.presto.sql.planner.plan.SinkNode.accept(SinkNode.java:69)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:226)
	at com.facebook.presto.execution.SqlTaskExecution.<init>(SqlTaskExecution.java:147)
	at com.facebook.presto.execution.SqlTaskExecution.createSqlTaskExecution(SqlTaskExecution.java:109)
	at com.facebook.presto.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:101)
	at com.facebook.presto.execution.SqlTask.updateTask(SqlTask.java:219)
	at com.facebook.presto.execution.SqlTaskManager.updateTask(SqlTaskManager.java:223)
	at com.facebook.presto.server.TaskResource.createOrUpdateTask(TaskResource.java:104)
```

**Comment by cawallin** [comment]
@electrum looks like you updated Presto's shaded Hive version to 1.2.0, so we can close this
