### ISSUE TITLE
Query to ORC fails with "low must be less than or equal to high"

### ISSUE THREAD

**Issue by snarayananqubole** [facebook/presto#2295]
Ran into this weird bug. Had an ORC file created using hive 11 where if I accessed one particular column, the query would fail with the attached stack trace.

Turns out the ORC file had bad stats for this particular column (probably a Hive bug - I haven't tracked it down). However, presto not allowing me to access the data is definitely problematic. I've put in a fix to TupleDomainOrcPredicate to catch badly formed domains and create universal ranges for those columns.

If this sounds acceptable, I'll start a PR for this.

```
Query 20150127_170137_00014_za3un failed: low must be less than or equal to high
com.facebook.presto.spi.PrestoException: low must be less than or equal to high
at com.facebook.presto.hive.orc.OrcPageSource.getNextPage(OrcPageSource.java:275)
at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:196)
at com.facebook.presto.operator.Driver.processInternal(Driver.java:351)
at com.facebook.presto.operator.Driver.processFor(Driver.java:283)
at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:563)
at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:443)
at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:577)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: low must be less than or equal to high
at com.facebook.presto.spi.Range.(Range.java:47)
at com.facebook.presto.spi.Range.range(Range.java:87)
at com.facebook.presto.orc.TupleDomainOrcPredicate.createDomain(TupleDomainOrcPredicate.java:132)
at com.facebook.presto.orc.TupleDomainOrcPredicate.getDomain(TupleDomainOrcPredicate.java:116)
at com.facebook.presto.orc.TupleDomainOrcPredicate.matches(TupleDomainOrcPredicate.java:65)
at com.facebook.presto.orc.StripeReader.selectRowGroups(StripeReader.java:281)
at com.facebook.presto.orc.StripeReader.readStripe(StripeReader.java:119)
at com.facebook.presto.orc.OrcRecordReader.advanceToNextStripe(OrcRecordReader.java:252)
at com.facebook.presto.orc.OrcRecordReader.advanceToNextRowGroup(OrcRecordReader.java:221)
at com.facebook.presto.orc.OrcRecordReader.nextBatch(OrcRecordReader.java:192)
at com.facebook.presto.hive.orc.OrcPageSource.getNextPage(OrcPageSource.java:231)
```

**Comment by dain** [comment]
What type is the column?  Also, which version of Presto.  We have found tons of bugs in the ORC stats collection code.

**Comment by snarayananqubole** [comment]
This was a string column. Presto version was 0.90-SNAPSHOT.

**Comment by martint** [comment]
Does your data contain non-ASCII unicode values? We saw an issue related to this in the past, and made this change to get around it: https://github.com/facebook/presto/commit/96e45e22fe1e4392119b1c182ebeaa18bc4e5a5d. Looking closely at the code, I realize the fix is completely broken for ORC. The `if` block is in the wrong method -- it should be in `toStringStatistics` :/

**Comment by snarayananqubole** [comment]
No - all the values seem to be ASCII values AFAICT.
