### ISSUE TITLE
Improve error message when creating Hive deserializer

### ISSUE THREAD

**Issue by electrum** [facebook/presto#2317]
Example stack trace:

```
java.lang.IllegalArgumentException: missing property: serialization.lib
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-18.0.jar:na]
	at com.facebook.presto.hive.HiveUtil.getDeserializer(HiveUtil.java:278) ~[na:na]
	at com.facebook.presto.hive.HiveUtil.getTableObjectInspector(HiveUtil.java:254) ~[na:na]
	at com.facebook.presto.hive.HiveUtil.getTableStructFields(HiveUtil.java:271) ~[na:na]
	at com.facebook.presto.hive.HiveClient.getColumnHandles(HiveClient.java:399) ~[na:na]
	at com.facebook.presto.hive.HiveClient.getTableMetadata(HiveClient.java:319) ~[na:na]
	at com.facebook.presto.hive.HiveClient.listTableColumns(HiveClient.java:527) ~[na:na]

**Comment by zhenxiao** [comment]
@electrum how about:
"missing Hive Deserializer property: serialization.lib"

**Comment by JonathanBennett** [comment]
For further information there was a corrupted Hive table in the metastore which, upon forceful removal of the table the query was successful in running. (For further information it was a Cloudera Canary healthcheck table which had become corrupted)

A more helpful error would inform what table in the hive metastore caused the error to be thrown, but I realise that might be a pipe dream.

**Comment by electrum** [comment]
There are a few issues here:

1) The message is very cryptic. A better message would be `Table or partition is missing Hive deserializer property (serialization.lib)`
2) The message does not tell the user which table or partition. In large warehouses this would be very hard to track down (probably need to go to the metastore MySQL database directly). Fixing this probably requires validating it when fetching the table or partition metadata, rather than trying to pass that information through to all of the call sites (plus, we should fail as soon as possible).
3) A corrupt table blocks metadata retrieval. However, it is unclear how this should be fixed. Return a single column named `table_is_corrupt`?
