### ISSUE TITLE
How to start PrestoServer with eclipse?

### ISSUE THREAD

**Issue by aslldab1** [facebook/presto#2324]
I build the project with eclipse and try to start server by running class PrestoServer. But it prints the following error:
java.lang.IllegalArgumentException: No factory for connector mysql
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-18.0.jar:na]
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:97) ~[classes/:na]
	at com.facebook.presto.metadata.CatalogManager.loadCatalog(CatalogManager.java:88) ~[classes/:na]
	at com.facebook.presto.metadata.CatalogManager.loadCatalogs(CatalogManager.java:70) ~[classes/:na]
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:108) [classes/:na]
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:60) [classes/:na]
2015-02-05T15:16:51.429+0800	 INFO	Thread-71	io.airlift.bootstrap.LifeCycleManager	Life cycle stopping...

**Comment by electrum** [comment]
You need to do a full build on the command line first to generate the ServiceLoader entries.

**Comment by aslldab1** [comment]
I build the project with "mvn eclipse:eclipse" on the command line, how to make the full build ?

**Comment by dain** [comment]
`mvn clean install`

**Comment by aslldab1** [comment]
After a full build, the error occurs as before. It there anything wrong with my running arguments?
`<addr>` -server -Dlog.levels-file=/media/WorkSpace/presto/etc/log.properties -Dconfig=/media/WorkSpace/presto/etc/config.properties -Dnode.environment=production

**Comment by cberner** [comment]
Unfortunately, none of the core developers use Eclipse. Were you able to fix this on your own?
