### ISSUE TITLE
Query failed: Could not initialize class org.xerial.snappy.Snappy

### ISSUE THREAD

**Issue by soulmachine** [facebook/presto#2325]
My table is created by the following command:

    CREATE EXTERNAL TABLE my_table_name(filed_name STRING, ...)
    ROW FORMAT SERDE 'parquet.hive.serde.ParquetHiveSerDe'
    STORED AS
    INPUTFORMAT 'parquet.hive.DeprecatedParquetInputFormat'
    OUTPUTFORMAT 'parquet.hive.DeprecatedParquetOutputFormat'
    LOCATION 'hdfs://hostname:8020/xxx/';

In Hive, everything is fine, I can query anything I want, but in Presto, I can't, everytime it throws out an error:

        Query 20150205_102115_00037_n352u failed: Could not initialize class org.xerial.snappy.Snappy

The data is stored in Parquet format compressed by Snappy.

I tried to add `-Dorg.xerial.snappy.tempdir=/tmp` to jvm.config but it didn't work.

And in the log `server.log`, there is an exception:

	2015-02-05T10:46:35.369-0800    ERROR   main    Bootstrap       Uncaught exception in thread main
	com.google.inject.internal.util.$ComputationException: java.lang.ArrayIndexOutOfBoundsException: 19955
	        at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553) ~[guice-3.0.jar:na]
	        at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419) ~[guice-3.0.jar:na]
	        at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041) ~[guice-3.0.jar:na]
	        at com.google.inject.internal.util.$StackTraceElements.forMember(StackTraceElements.java:53) ~[guice-3.0.jar:na]
	        at com.google.inject.internal.Errors.formatSource(Errors.java:690) ~[guice-3.0.jar:na]
	        at com.google.inject.internal.Errors.formatInjectionPoint(Errors.java:720) ~[guice-3.0.jar:na]
	        at com.google.inject.internal.Errors.formatSource(Errors.java:684) ~[guice-3.0.jar:na]
	        at com.google.inject.internal.Errors.format(Errors.java:555) ~[guice-3.0.jar:na]
	        at com.google.inject.CreationException.getMessage(CreationException.java:48) ~[guice-3.0.jar:na]
	        at io.airlift.log.Logger.error(Logger.java:308) ~[log-0.99.jar:0.99]
	        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:121) ~[presto-main-0.92.jar:0.92]
	        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:59) ~[presto-main-0.92.jar:0.92]
	Caused by: java.lang.ArrayIndexOutOfBoundsException: 19955
	        at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source) ~[guice-3.0.jar:na]
	        at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source) ~[guice-3.0.jar:na]
	        at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source) ~[guice-3.0.jar:na]
	        at com.google.inject.internal.util.$LineNumbers.<init>(LineNumbers.java:62) ~[guice-3.0.jar:na]
	        at com.google.inject.internal.util.$StackTraceElements$1.apply(StackTraceElements.java:36) ~[guice-3.0.jar:na]
	        at com.google.inject.internal.util.$StackTraceElements$1.apply(StackTraceElements.java:33) ~[guice-3.0.jar:na]
	        at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549) ~[guice-3.0.jar:na]
	        ... 11 common frames omitted

Does anyone happen to know this?

**Comment by electrum** [comment]
Can you run the CLI with --debug and post the full stack trace?

**Comment by soulmachine** [comment]
Here is the stack trace:

	Query 20150206_001859_00011_n352u failed: Could not initialize class org.xerial.snappy.Snappy
	java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy
		at parquet.hadoop.codec.SnappyDecompressor.decompress(SnappyDecompressor.java:59)
		at parquet.hadoop.codec.NonBlockedDecompressorStream.read(NonBlockedDecompressorStream.java:48)
		at java.io.DataInputStream.readFully(DataInputStream.java:195)
		at java.io.DataInputStream.readFully(DataInputStream.java:169)
		at parquet.bytes.BytesInput$StreamBytesInput.toByteArray(BytesInput.java:201)
		at parquet.column.values.dictionary.PlainValuesDictionary$PlainBinaryDictionary.<init>(PlainValuesDictionary.java:62)
		at parquet.column.Encoding$4.initDictionary(Encoding.java:127)
		at parquet.column.impl.ColumnReaderImpl.<init>(ColumnReaderImpl.java:341)
		at parquet.column.impl.ColumnReadStoreImpl.newMemColumnReader(ColumnReadStoreImpl.java:63)
		at parquet.column.impl.ColumnReadStoreImpl.getColumnReader(ColumnReadStoreImpl.java:58)
		at parquet.io.RecordReaderImplementation.<init>(RecordReaderImplementation.java:265)
		at parquet.io.MessageColumnIO.getRecordReader(MessageColumnIO.java:59)
		at parquet.io.MessageColumnIO.getRecordReader(MessageColumnIO.java:73)
		at parquet.hadoop.InternalParquetRecordReader.checkRead(InternalParquetRecordReader.java:110)
		at parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:172)
		at parquet.hadoop.ParquetRecordReader.nextKeyValue(ParquetRecordReader.java:130)
		at com.facebook.presto.hive.ParquetHiveRecordCursor.advanceNextPosition(ParquetHiveRecordCursor.java:219)
		at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:93)
		at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:230)
		at com.facebook.presto.operator.Driver.processInternal(Driver.java:351)
		at com.facebook.presto.operator.Driver.processFor(Driver.java:283)
		at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:555)
		at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:444)
		at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:578)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)

I've installed snappy by `sudo yum install snappy` on all nodes.

**Comment by felipegasparini** [comment]
I'm having the same problem.

I can create and query the table with Hive but when I try to query using Presto it throws out the error with the missing Snappy class (java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy).

I'm running Presto on EMR using the bootstrap action from s3://support.elasticmapreduce/bootstrap-actions/presto/install-presto.rb.

**Comment by cberner** [comment]
I think this was fixed in a recent release. Please re-open if you're still seeing this
