### ISSUE TITLE
java.sql.SQLException: Value '0000-00-00' can not be represented as java.sql.Date

### ISSUE THREAD

**Issue by avasilevskiy** [facebook/presto#2326]
Running Presto query on MySQL datasource :

presto:default> SELECT hdate FROM mysql.service.users limit 10;

Query 20150205_181558_00013_xduyk, FAILED, 1 node
Splits: 2 total, 0 done (0.00%)
0:01 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20150205_181558_00013_xduyk failed: java.sql.SQLException: Value '0000-00-00' can not be represented as java.sql.Date
--------------------------------------------------------------------
From MySQL workbench the same query yields:

'0000-00-00'
'2014-10-24'
'2014-12-06'
'2014-12-01'
'2014-10-07'

Presto worker log:

2015-02-05T18:15:58.406+0000	ERROR	SplitRunner-13-44	com.facebook.presto.execution.TaskExecutor	Error processing Split 20150205_181558_00013_xduyk.1.0-0 (start = 1423160158317, wall = 82 ms, cpu = 0 ms, calls = 1)
java.lang.RuntimeException: java.sql.SQLException: Value '0000-00-00' can not be represented as java.sql.Date
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-18.0.jar:na]
	at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:243) ~[na:na]
	at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.isNull(JdbcRecordCursor.java:214) ~[na:na]
	at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:101) ~[presto-spi-0.92.jar:0.92]
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:230) ~[presto-main-0.92.jar:0.92]
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:351) ~[presto-main-0.92.jar:0.92]
	at com.facebook.presto.operator.Driver.processFor(Driver.java:283) ~[presto-main-0.92.jar:0.92]
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:563) ~[presto-main-0.92.jar:0.92]
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:443) ~[presto-main-0.92.jar:0.92]
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:577) ~[presto-main-0.92.jar:0.92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_31]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_31]
Caused by: java.sql.SQLException: Value '0000-00-00' can not be represented as java.sql.Date
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078) ~[na:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989) ~[na:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975) ~[na:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920) ~[na:na]
	at com.mysql.jdbc.ResultSetRow.getDateFast(ResultSetRow.java:141) ~[na:na]
	at com.mysql.jdbc.ByteArrayRow.getDateFast(ByteArrayRow.java:238) ~[na:na]
	at com.mysql.jdbc.ResultSetImpl.getDate(ResultSetImpl.java:2211) ~[na:na]
	at com.mysql.jdbc.ResultSetImpl.getDate(ResultSetImpl.java:2173) ~[na:na]
	at com.mysql.jdbc.ResultSetImpl.getObject(ResultSetImpl.java:5052) ~[na:na]
	at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.isNull(JdbcRecordCursor.java:209) ~[na:na]
	... 10 common frames omitted
2015-02-05

**Comment by yuananf** [comment]
I believe this is caused by JDBC, add zeroDateTimeBehavior=convertToNull at the end of the jdbc connection string will fix.
like this
jdbc:mysql://127.0.0.1:3306?zeroDateTimeBehavior=convertToNull

**Comment by avasilevskiy** [comment]
Looks good !

NULL
'2014-10-24'
'2014-12-06'
'2014-12-01'
'2014-10-07'

**Comment by patelnainesh222** [comment]
Thanks

**Comment by chandankumarv11** [comment]
yes it's working
[  jdbc:mysql://127.0.0.1:3306?zeroDateTimeBehavior=convertToNull  ]

**Comment by Manindersaini** [comment]
worked well......

**Comment by swapna-subramani** [comment]
yes,it works...thank u

**Comment by ppdouble** [comment]
>- Datetimes with all-zero components (0000-00-00 ...): These values cannot be represented reliably in Java. Connector/J 3.0.x always converted them to NULL when being read from a ResultSet.
>
>Connector/J 3.1 throws an exception by default when these values are encountered, as this is the most correct behavior according to the JDBC and SQL standards. This behavior can be modified using the zeroDateTimeBehavior configuration property. The permissible values are:
>
>exception (the default), which throws an SQLException with an SQLState of S1009.
>
>convertToNull, which returns NULL instead of the date.
>
>round, which rounds the date to the nearest closest value which is 0001-01-01.


[connector-j/5.1](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-installing-upgrading-3-0-to-3-1.html)

[connector-j/8.0](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-datetime-types-processing.html#cj-conn-prop_zeroDateTimeBehavior)
