### ISSUE TITLE
Query failed: repeated binary array (UTF8) is not a group

### ISSUE THREAD

**Issue by soulmachine** [facebook/presto#2329]
If my data is in parquet format(UNCOMPRESSED), it will fail,

	presto:default> describe my_table_avro_parquet;
	                 Column                  |      Type      | Null | Partition Key | Comment
	------------------------------------------+----------------+------+---------------+---------
	 tags                                     | array<varchar> | true | false         |
	 (1 rows)
	 ...
	presto:default> select tags from chef_logstash_structured_avro3 limit 10;
	...
	Query 20150205_202243_00079_n352u failed: repeated binary array (UTF8) is not a group

If my data is in plain text, it will succeed,

	presto:default> describe my_table_text;
	                 Column                  |      Type      | Null | Partition Key | Comment
	------------------------------------------+----------------+------+---------------+---------
	 tags                                     | array<varchar> | true | false         |
	 (1 rows)
	 ...
	presto:default> select tags from chef_logstash_text limit 10;
	                        tags
	------------------------------------------------------
	...
	(10 rows)

Here is the stack trace when I pass the `--debug` option to launch cli:

	Query 20150206_001338_00009_n352u failed: repeated binary array (UTF8) is not a group
	java.lang.ClassCastException: repeated binary array (UTF8) is not a group
		at parquet.schema.Type.asGroupType(Type.java:137)
		at com.facebook.presto.hive.ParquetHiveRecordCursor$ParquetListJsonConverter.<init>(ParquetHiveRecordCursor.java:774)
		at com.facebook.presto.hive.ParquetHiveRecordCursor$PrestoReadSupport.<init>(ParquetHiveRecordCursor.java:401)
		at com.facebook.presto.hive.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:313)
		at com.facebook.presto.hive.ParquetHiveRecordCursor.<init>(ParquetHiveRecordCursor.java:116)
		at com.facebook.presto.hive.ParquetRecordCursorProvider.createHiveRecordCursor(ParquetRecordCursorProvider.java:65)
		at com.facebook.presto.hive.HivePageSourceProvider.getHiveRecordCursor(HivePageSourceProvider.java:129)
		at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:107)
		at com.facebook.presto.spi.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:42)
		at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:58)
		at com.facebook.presto.operator.TableScanOperator.addSplit(TableScanOperator.java:144)
		at com.facebook.presto.operator.Driver.processNewSource(Driver.java:259)
		at com.facebook.presto.operator.Driver.processNewSources(Driver.java:224)
		at com.facebook.presto.operator.Driver.access$300(Driver.java:53)
		at com.facebook.presto.operator.Driver$DriverLockResult.close(Driver.java:524)
		at com.facebook.presto.operator.Driver.updateSource(Driver.java:202)
		at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:461)
		at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunnerFactory.access$1500(SqlTaskExecution.java:428)
		at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:549)
		at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:444)
		at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:578)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)

My Avro schema is:

	{"namespace": "me.soulmachine.avro",
	 "type": "record",
	 "name": "ServerLog",
	 "fields": [
	     {"name": "tags", "type":{"type": "array", "items": "string"}, "default": [""]}
	 ]
	}

Why does Presto can recognize array of strings in text file format but not in Parquet format?

**Comment by dain** [comment]
Parquet has a custom integration (without the custom integration Parquet is about 10x slower).  

We do have tests for Parquet with `array<varchar>`, but looking at the code, I think we are using information that only Hive writes.  Did you write the data with Hive or Presto?

@cberner is working on a fix for this code right now, so maybe he can fix this at the same time.

**Comment by soulmachine** [comment]
Thanks for you comment.

I used Hive to create the table, I use Presto to run SQL queries, Presto is a pure reader and will not modify the table.

Can you give me a link to the code of Parquet custom integration, I need it badly :)

**Comment by dain** [comment]
This is just a custom integration between Presto an the existing Parquet reader code, unlike the ORC reader in Presto which is new code.  

https://github.com/facebook/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/ParquetHiveRecordCursor.java

**Comment by dain** [comment]
BTW if you care about performance, ORC is currently much faster than Parquet

**Comment by dain** [comment]
@cberner did you fix this?

**Comment by cberner** [comment]
I think so. @soulmachine can you reopen, if you still see this on master (or with 0.97 when it's released)?

**Comment by colinmarc** [comment]
@cberner I'm still see this on 0.97. I can follow up with a test case.

**Comment by colinmarc** [comment]
The issue is here:

```
 listType.getType(0).asGroupType()
```
(https://github.com/facebook/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/ParquetHiveRecordCursor.java#L777)

The schema for a LIST looks like:

```
  optional group foo (LIST) {
    repeated binary foo_tuple (UTF8);
  }
```

So the error message is `java.lang.ClassCastException: repeated binary foo_tuple (UTF8) is not a group`

**Comment by colinmarc** [comment]
I opened a PR for this: #2511

**Comment by soulmachine** [comment]
@colinmarc Great!

**Comment by itismewxg** [comment]
but even in spark sql 1.6.1 still have this issue

**Comment by pandeesh** [comment]
i see this still on 2.0.1. what's the work around for this?

**Comment by itismewxg** [comment]
keep seeing

**Comment by nezihyigitbasi** [comment]
@itismewxg Did you try the new Parquet reader? You can enable it with `hive.parquet-optimized-reader.enabled` (or the session property `parquet_optimized_reader_enabled`).

**Comment by itismewxg** [comment]
@nezihyigitbasi Thanks!

**Comment by itismewxg** [comment]
in fact, I am using sparksql so far as the query engine, and parquet-store as piece by piece as data source schema is changing on the fly. but for such NULL/List change happened between 2 pieces, just hit on such problem

**Comment by nezihyigitbasi** [comment]
@itismewxg did this fix your problem?

**Comment by itismewxg** [comment]
Not exactly, I knew presto with this flag can solve the problem, but as above, I am using sparksql as the query engine, look into sparksql's source code, might find the point to change the way sparksql handle the List

**Comment by itismewxg** [comment]
and, in fact, i made a walk around in my own project, readout the original json message (txt), Thanks God, we keep both json and parquet, get the RDD, and then, make the mapper to handle such in-consistent schema things in our original message.
And, i would like to share more, you know, the original messages are from javascripts, in js world, they take message format consistency as nothing to bother backend person, hahaha

**Comment by sonnythehottest** [comment]
Hi, I actually experience similar issue in parquet, read using spark SQL: `java.lang.ClassCastException: optional binary element (UTF8) is not a group`. Do you guys any idea / workaround for this?

**Comment by nezihyigitbasi** [comment]
@sonnythehottest Can you provide the entire stack trace (pass `--debug` to presto-cli) and more details about what you are doing? Did you try the optimized/new Parquet reader?
