### ISSUE TITLE
Compiler fails for magic literal in method names

### ISSUE THREAD

**Issue by electrum** [facebook/presto#2346]
SELECT rand() > 0.5 and contains(array[1.5], rand())

**Comment by martint** [comment]
The error it produces is:

```
java.lang.ClassFormatError: Illegal method name "$literal$array<double>" in class com/facebook/presto/$gen/PageProcessor_84121
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
	at com.facebook.presto.sql.gen.ExpressionCompiler.compilePageProcessor(ExpressionCompiler.java:89)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:798)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:711)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:338)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:361)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:338)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:79)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:220)
	at com.facebook.presto.execution.SqlTaskExecution.<init>(SqlTaskExecution.java:147)
	at com.facebook.presto.execution.SqlTaskExecution.createSqlTaskExecution(SqlTaskExecution.java:109)
	at com.facebook.presto.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:101)
	at com.facebook.presto.execution.SqlTask.updateTask(SqlTask.java:212)
	at com.facebook.presto.execution.SqlTaskManager.updateTask(SqlTaskManager.java:217)
	at com.facebook.presto.server.TaskResource.createOrUpdateTask(TaskResource.java:101)
```

**Comment by haozhun** [comment]
Talked with @martint.

While fixing the naming can work, it's not the best approach. The magic literal shouldn't exist in the bytecode. Magic literal should always be translated in expression optimizer, and such translation can never fail. Therefore, lazy behavior in SQL does not affect this. The better approach is to make `ExpressionOptimizer` translate the arguments even if the function is one of the special forms (if, and, ...). When failure is encountered during such translation, leave the function involved alone, but continue on other functions.
