### ISSUE TITLE
ClassCastException in buildAccumulatorFactory

### ISSUE THREAD

**Issue by dain** [facebook/presto#2368]
This query:

```sql
select ds, max(x), numeric_histogram(10, x) 
from (
   select *, cardinality(regexp_extract_all(str, 'pattern')) x 
   from tab 
   where str is not null
)
group by 1 order by 1;
```

causes:

```
Query 20150214_074945_04999_uc6tn failed: com.facebook.presto.sql.tree.Cast cannot be cast to com.facebook.presto.sql.tree.QualifiedNameReference
java.lang.ClassCastException: com.facebook.presto.sql.tree.Cast cannot be cast to com.facebook.presto.sql.tree.QualifiedNameReference
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.buildAccumulatorFactory(LocalExecutionPlanner.java:1404)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.planGroupByAggregation(LocalExecutionPlanner.java:1448)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitAggregation(LocalExecutionPlanner.java:655)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitAggregation(LocalExecutionPlanner.java:378)
	at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:165)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:222)
	at com.facebook.presto.execution.SqlTaskExecution.<init>(SqlTaskExecution.java:147)
	at com.facebook.presto.execution.SqlTaskExecution.createSqlTaskExecution(SqlTaskExecution.java:109)
	at com.facebook.presto.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:101)
	at com.facebook.presto.execution.SqlTask.updateTask(SqlTask.java:217)
	at com.facebook.presto.execution.SqlTaskManager.updateTask(SqlTaskManager.java:217)
	at com.facebook.presto.server.TaskResource.createOrUpdateTask(TaskResource.java:103)
```

**Comment by martint** [comment]
This is the same as https://github.com/facebook/presto/issues/2032
