### ISSUE TITLE
Presto server throws exception when running on a nodes with UTC tz

### ISSUE THREAD

**Issue by puneetjaiswal** [facebook/presto#2370]
I get this response client side

presto:default> show schemas;
Error running command: Error starting query at http://ec2-54-187-253-90.us-west-2.compute.amazonaws.com:8070/v1/statement returned an invalid response: JsonResponse{statusCode=500, statusMessage=Internal Server Error, headers={Content-Length=[4935], Date=[Mon, 16 Feb 2015 22:11:46 GMT], Content-Type=[text/plain]}, hasValue=false, value=null}

However this is the error I see server side:

2015-02-16T22:11:46.342+0000	 WARN	http-worker-122	com.facebook.presto.server.ThrowableMapper	Request failed for /v1/statement
com.facebook.presto.spi.type.TimeZoneNotSupportedException: Time zone GMT-00:00 is not supported
	at com.facebook.presto.spi.type.TimeZoneKey.getTimeZoneKey(TimeZoneKey.java:128) ~[presto-spi-0.94-SNAPSHOT.jar:0.94-SNAPSHOT]
	at com.facebook.presto.Session$SessionBuilder.<init>(Session.java:270) ~[presto-main-0.94-SNAPSHOT.jar:0.94-SNAPSHOT]
	at com.facebook.presto.Session$SessionBuilder.<init>(Session.java:264) ~[presto-main-0.94-SNAPSHOT.jar:0.94-SNAPSHOT]
	at com.facebook.presto.Session.builder(Session.java:261) ~[presto-main-0.94-SNAPSHOT.jar:0.94-SNAPSHOT]
	at com.facebook.presto.server.ResourceUtil.createSessionForRequest(ResourceUtil.java:58) ~[presto-main-0.94-SNAPSHOT.jar:0.94-SNAPSHOT]
	at com.facebook.presto.server.StatementResource.createQuery(StatementResource.java:147) ~[presto-main-0.94-SNAPSHOT.jar:0.94-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]

**Comment by cberner** [comment]
We just need to add support for this to `TimeZoneKey`

As a test case, add this to `TestTimeZoneKey.testUtc()`
`assertSame(TimeZoneKey.getTimeZoneKey("GMT-00:00"), UTC_KEY);`

**Comment by dain** [comment]
Merged. Thanks!
