### ISSUE TITLE
TestExchangeClient failures

### ISSUE THREAD

**Issue by electrum** [facebook/presto#2384]
I have not been able to reproduce this yet. Details at https://gist.github.com/petroav/7a0863911fd3aef437e2

```
testAddLocation(com.facebook.presto.operator.TestExchangeClient)  Time elapsed: 0.085 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:494)
        at org.testng.Assert.assertEquals(Assert.java:123)
        at org.testng.Assert.assertEquals(Assert.java:286)
        at org.testng.Assert.assertEquals(Assert.java:296)
        at com.facebook.presto.operator.TestExchangeClient.testAddLocation(TestExchangeClient.java:158)
```

**Comment by petroav** [comment]
I believe this was fixed with https://github.com/facebook/presto/commit/a74237e77a13b7a2843161afd780ff6feee0f930. I am no longer seeing the unit test failure so you should feel free to close the issue. Thank you @cberner for taking care of this!

**Comment by cberner** [comment]
Sure thing!
