### ISSUE TITLE
HIVE_CURSOR_ERROR - Could not obtain block

### ISSUE THREAD

**Issue by burakkk** [facebook/presto#2467]
Hello,
I'm trying to read a hive table using presto and hive-hadoop2 connector but I got an error. It seems like presto tries to connect infiniband network from hadoop cluster which can be able to use only inside the hadoop cluster. But I installed the presto outside the cluster. I read the hive connector's document and I also added the hive.config.resources parameters. I also added dfs.client.use.datanode.hostname to cluster's hdfs-site.xml. It's still not working :(  Did I miss something?

presto:default> select * from ehaspulat_sentinel limit 2;

Query 20150305_093515_00002_z65jk, FAILED, 1 node
Splits: 101 total, 0 done (0.00%)
2:22 [0 rows, 0B] [0 rows/s, 0B/s]

more etc/catalog/hive.properties 
connector.name=hive-hadoop2
hive.metastore.uri=thrift://10.xxx.xx.xx:9083
hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml

dfs.client.use.datanode.hostname = true

....
2015-03-05T11:37:41.377+0200	ERROR	SplitRunner-45-156	com.facebook.presto.execution.TaskExecutor	Error processing Split 20150305_093515_00002_z65jk.1.0-36 (start = 1425548116568, wall = 144809 ms, cpu = 0 ms, calls = 1): HIVE_CANNOT_OPEN_SPLIT: Error opening Hive split hdfs://marutestmaster01:8020/apps/hive/warehouse/ehaspulat_sentinel/000009_0 (offset=67108864, length=33554432) using org.apache.hadoop.mapred.TextInputFormat: Could not obtain block: BP-2056852000-39.7.48.18-1418319726816:blk_1073951532_1099513219203 file=/apps/hive/warehouse/ehaspulat_sentinel/000009_0
2015-03-05T11:37:41.390+0200	ERROR	SplitRunner-20-130	com.facebook.presto.execution.TaskExecutor	Error processing Split 20150305_093515_00002_z65jk.1.0-11 (start = 1425548116568, wall = 144822 ms, cpu = 0 ms, calls = 1): HIVE_CANNOT_OPEN_SPLIT: Error opening Hive split hdfs://marutestmaster01:8020/apps/hive/warehouse/ehaspulat_sentinel/000017_0 (offset=134217728, length=25361292) using org.apache.hadoop.mapred.TextInputFormat: Could not obtain block: BP-2056852000-39.7.48.18-1418319726816:blk_1073951632_1099513219303 file=/apps/hive/warehouse/ehaspulat_sentinel/000017_0
2015-03-05T11:37:41.442+0200	ERROR	SplitRunner-34-145	com.facebook.presto.execution.TaskExecutor	Error processing Split 20150305_093515_00002_z65jk.1.0-25 (start = 1425548116570, wall = 144872 ms, cpu = 0 ms, calls = 1): HIVE_CURSOR_ERROR: Could not obtain block: BP-2056852000-39.7.48.18-1418319726816:blk_1073951532_1099513219203 file=/apps/hive/warehouse/ehaspulat_sentinel/000009_0
....

**Comment by electrum** [comment]
Presto uses the HDFS client library. Can you try running "hadoop fs -cat" on one of the files from a Presto worker? That will tell us if the Hadoop client is able to read the files.

**Comment by burakkk** [comment]
When I try this command (hdfs dfs  -cat hdfs://marutestmaster01:8020/apps/hive/warehouse/ehaspulat_sentinel/000009_0) , it also doesn't work. But if I add dfs.client.use.datanode.hostname parameter (final command is  hdfs dfs -Ddfs.client.use.datanode.hostname=true  -cat hdfs://marutestmaster01:8020/apps/hive/warehouse/ehaspulat_sentinel/000009_0), it's working and I can be able to see data.

hdfs dfs  -cat hdfs://marutestmaster01:8020/apps/hive/warehouse/ehaspulat_sentinel/000009_0
...
15/03/05 18:14:49 WARN hdfs.BlockReaderFactory: I/O error constructing remote block reader.
org.apache.hadoop.net.ConnectTimeoutException: 60000 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=/39.7.48.23:50010]
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:532)
	at org.apache.hadoop.hdfs.DFSClient.newConnectedPeer(DFSClient.java:2884)
	at org.apache.hadoop.hdfs.BlockReaderFactory.nextTcpPeer(BlockReaderFactory.java:747)
	at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReaderFromTcp(BlockReaderFactory.java:662)
	at org.apache.hadoop.hdfs.BlockReaderFactory.build(BlockReaderFactory.java:326)
	at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:570)
	at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:793)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:840)
	at java.io.DataInputStream.read(DataInputStream.java:83)
	at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:78)
	at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:52)
	at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:112)
	at org.apache.hadoop.fs.shell.Display$Cat.printToStdout(Display.java:103)
	at org.apache.hadoop.fs.shell.Display$Cat.processPath(Display.java:98)
	at org.apache.hadoop.fs.shell.Command.processPaths(Command.java:306)
	at org.apache.hadoop.fs.shell.Command.processPathArgument(Command.java:278)
	at org.apache.hadoop.fs.shell.Command.processArgument(Command.java:260)
	at org.apache.hadoop.fs.shell.Command.processArguments(Command.java:244)
	at org.apache.hadoop.fs.shell.Command.processRawArguments(Command.java:190)
	at org.apache.hadoop.fs.shell.Command.run(Command.java:154)
	at org.apache.hadoop.fs.FsShell.run(FsShell.java:287)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:340)
15/03/05 18:14:49 WARN hdfs.DFSClient: Failed to connect to /39.7.48.23:50010 for block, add to deadNodes and continue. org.apache.hadoop.net.ConnectTimeoutException: 60000 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=/39.7.48.23:50010]
org.apache.hadoop.net.ConnectTimeoutException: 60000 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=/39.7.48.23:50010]
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:532)
	at org.apache.hadoop.hdfs.DFSClient.newConnectedPeer(DFSClient.java:2884)
	at org.apache.hadoop.hdfs.BlockReaderFactory.nextTcpPeer(BlockReaderFactory.java:747)
	at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReaderFromTcp(BlockReaderFactory.java:662)
	at org.apache.hadoop.hdfs.BlockReaderFactory.build(BlockReaderFactory.java:326)
	at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:570)
	at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:793)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:840)
	at java.io.DataInputStream.read(DataInputStream.java:83)
	at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:78)
	at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:52)
	at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:112)
	at org.apache.hadoop.fs.shell.Display$Cat.printToStdout(Display.java:103)
	at org.apache.hadoop.fs.shell.Display$Cat.processPath(Display.java:98)
	at org.apache.hadoop.fs.shell.Command.processPaths(Command.java:306)
	at org.apache.hadoop.fs.shell.Command.processPathArgument(Command.java:278)
	at org.apache.hadoop.fs.shell.Command.processArgument(Command.java:260)
	at org.apache.hadoop.fs.shell.Command.processArguments(Command.java:244)
	at org.apache.hadoop.fs.shell.Command.processRawArguments(Command.java:190)
	at org.apache.hadoop.fs.shell.Command.run(Command.java:154)
	at org.apache.hadoop.fs.FsShell.run(FsShell.java:287)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:340)

**Comment by cberner** [comment]
Looks like you were able to fix this on your own?

**Comment by rsolver200** [comment]
Hi,
I am trying to read data stored in openstack Swift using Presto (hive-hadoop2 connector). 
query: select * from test.table_from_swift limit 10;

error message:
2015-09-02T15:41:41.682Z	ERROR	SplitRunner-3-37	com.facebook.presto.execution.TaskExecutor	Error processing Split 20150902_154116_00002_bgj8g.1.9-3 {path=swift://testbucket.datalake/futuredata-2016-05-02.csv.bz2, start=0, length=51715641, hosts=[localhost], database=test, table=table_from_swift, forceLocalScheduling=false, partitionName=<UNPARTITIONED>, effectivePredicate=TupleDomain:ALL} (start = 1441208495128, wall = 6554 ms, cpu = 0 ms, calls = 1): HIVE_CANNOT_OPEN_SPLIT: Error opening Hive split swift://testbucket.datalake/futuredata-2016-05-02.csv.bz2 (offset=0, length=51715641) using org.apache.hadoop.mapred.TextInputFormat: sleep interrupted

I am running the latest Presto server and hive is able to read the data from swift.

**Comment by electrum** [comment]
@nanaessuman This looks like a different error. Could you file a different issue?

**Comment by versemonger** [comment]
@burakisikli  I got the same error. How did you fix it?

**Comment by versemonger** [comment]
@electrum Do you mean that hdfs or hadoop must be also be installed where presto runs?

**Comment by dabaitu** [comment]
@electrum Hi David. Want to get some more detail on this.
I'm running 0.149 in our production and ran into this error consistently with a split. 
I was able to 'cat' the file on the worker node.
The exact trace I got:
`com.facebook.presto.spi.PrestoException: Error opening Hive split viewfs://hadoop-dw2-nn.smf1.twitter.com/logs/tfe_inc_auth_requests/2016/11/25/10/tfe_inc_auth_requests_2016-11-25-10_atla-m-00169.lzo.parquet (offset=402653184, length=67108864): Could not obtain block: BP-556508847-10.36.180.140-1380755044316:blk_2994865035_1101529321388 file=/logs/tfe_inc_auth_requests/2016/11/25/10/tfe_inc_auth_requests_2016-11-25-10_atla-m-00169.lzo.parquet
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:479)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.<init>(ParquetHiveRecordCursor.java:246)
	at com.facebook.presto.hive.parquet.ParquetRecordCursorProvider.createHiveRecordCursor(ParquetRecordCursorProvider.java:96)
	at com.facebook.presto.hive.HivePageSourceProvider.getHiveRecordCursor(HivePageSourceProvider.java:151)
	at com.facebook.presto.hive.HivePageSourceProvider.doCreatePageSource(HivePageSourceProvider.java:129)
	at com.facebook.presto.hive.HivePageSourceProvider.lambda$createPageSource$0(HivePageSourceProvider.java:80)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:79)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:44)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:48)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.createSourceIfNecessary(ScanFilterAndProjectOperator.java:292)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.isFinished(ScanFilterAndProjectOperator.java:180)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:375)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:618)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:529)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:665)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.hadoop.hdfs.BlockMissingException: Could not obtain block: BP-556508847-10.36.180.140-1380755044316:blk_2994865035_1101529321388 file=/logs/tfe_inc_auth_requests/2016/11/25/10/tfe_inc_auth_requests_2016-11-25-10_atla-m-00169.lzo.parquet
	at org.apache.hadoop.hdfs.DFSInputStream.chooseDataNode(DFSInputStream.java:946)
	at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:604)
	at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:844)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:896)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:697)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at parquet.bytes.BytesUtils.readIntLittleEndian(BytesUtils.java:66)
	at parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:418)
	at parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:385)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.lambda$createParquetRecordReader$0(ParquetHiveRecordCursor.java:415)
	at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:76)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:415)
	... 21 more`
Any help would be greatly appreciated.

**Comment by ellison840611** [comment]
I added the following sentence to the configuration file(etc/catalog/hive.properties), which solved the problem:
hive.config.resources=/local directory/core-site.xml,/local directory/hdfs-site.xml

**Comment by SongChujun** [comment]
u can take a look at my answer here: https://stackoverflow.com/a/72425172/7230839.
