### ISSUE TITLE
[bug] ORC error when push down Date type predicate

### ISSUE THREAD

**Issue by yuananf** [facebook/presto#2477]
I have an ORC table employees_orc, and got error with query 
select * from employees_orc where hire_date= date '1985-02-18'

Query 20150309_060956_00010_hxbst failed: Mismatched Domain types: class java.lang.Long vs class java.lang.Integer
com.facebook.presto.spi.PrestoException: Mismatched Domain types: class java.lang.Long vs class java.lang.Integer
	at com.facebook.presto.hive.orc.OrcPageSource.getNextPage(OrcPageSource.java:275)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:196)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:343)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:283)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:563)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:449)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:583)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Mismatched Domain types: class java.lang.Long vs class java.lang.Integer
	at com.facebook.presto.spi.Domain.checkTypeCompatibility(Domain.java:226)
	at com.facebook.presto.spi.Domain.intersect(Domain.java:180)
	at com.facebook.presto.spi.TupleDomain.intersect(TupleDomain.java:256)
	at com.facebook.presto.spi.TupleDomain.overlaps(TupleDomain.java:355)
	at com.facebook.presto.orc.TupleDomainOrcPredicate.matches(TupleDomainOrcPredicate.java:71)
	at com.facebook.presto.orc.StripeReader.selectRowGroups(StripeReader.java:281)
	at com.facebook.presto.orc.StripeReader.readStripe(StripeReader.java:119)
	at com.facebook.presto.orc.OrcRecordReader.advanceToNextStripe(OrcRecordReader.java:252)
	at com.facebook.presto.orc.OrcRecordReader.advanceToNextRowGroup(OrcRecordReader.java:221)
	at com.facebook.presto.orc.OrcRecordReader.nextBatch(OrcRecordReader.java:192)
	at com.facebook.presto.hive.orc.OrcPageSource.getNextPage(OrcPageSource.java:231)
	... 9 more

@dain can you take a look at this, I think this is a bug.

**Comment by dain** [comment]
I think the bug is here

 https://github.com/facebook/presto/blob/master/presto-orc/src/main/java/com/facebook/presto/orc/TupleDomainOrcPredicate.java#L107

The problem is the `DateStatistics` contain `int` values and we need long values.  The fix should be as easy as converting the line to something like:
```java
return createDomain(boxedJavaType, hasNullValue, columnStatistics.getDateStatistics(), value -> (long) value);
```

**Comment by yuananf** [comment]
I just did the fix, but the result seems to be wrong.

presto:employees> select * from employees_orc where hire_date = date '2000-01-28';
 emp_no | birth_date | first_name | last_name | gender | hire_date 
--------+------------+------------+-----------+--------+-----------
(0 rows)

presto:employees> select * from employees_orc where cast(hire_date as varchar)= '2000-01-28';
 emp_no | birth_date | first_name | last_name | gender | hire_date  
--------+------------+------------+-----------+--------+------------
 463807 | 1964-06-13 | Bikash     | Covnot    | M      | 2000-01-28 
(1 row)

**Comment by dain** [comment]
Can you try debugging to see what values are getting set into the tuple domains?

**Comment by yuananf** [comment]
I find the reason now. It's quite weird.
My hive version is hive-0.13.1-cdh5.3.0
Follow the steps can generate the wrong result.
(1) Create an ORC table in presto.
      create table employees_orc as select * from employees;
(2) Insert overwrite this ORC table in Hive
      insert overwrite table employees_orc select * from employees;
(3) Query in presto
      select * from employees_orc where hire_date = date '2000-01-28';

If I omit step (2), then the result is correct.
It seems to be caused by hive orc write.

The value that are getting set into the tuple domains is 10984.
Marker{type=class java.lang.Long, value=10984, bound=EXACTLY}

**Comment by yuananf** [comment]
The following change can fix for me. But I do not understand why this will work.
https://github.com/facebook/presto/blob/master/presto-orc/src/main/java/com/facebook/presto/orc/TupleDomainOrcPredicate.java#L60
if (columnStatistics == null)
==> 
if (columnStatistics == null || columnReference.getType().getTypeSignature().getBase().equals(StandardTypes.DATE))

**Comment by dain** [comment]
That just disables predicate pushdown for the `DATE` type.

**Comment by yuananf** [comment]
Oh, I see.
