### ISSUE TITLE
'IN' is broken for 'string'

### ISSUE THREAD

**Issue by damiencarol** [facebook/presto#2502]
Simple query as:
```sql
    select
         cube_vol . benchmark  as  c0 ,
         cube_vol . volume  as  c1 ,
         cube_vol . soft  as  c2 ,
        avg( cube_vol . average ) as  m0 
    from
         bench . cube_vol  as  cube_vol 
    where
         cube_vol . benchmark  in ('VOL--2', 'VOL-2', 'VOL1', 'VOL2', 'VOL3', 'VOL4', 'VOL5', 'VOLFIL2')
    and
         cube_vol . volume  in (10000000, 100000000, 1000000000, 200000000, 50000000, 500000000)
    and
         cube_vol . soft  in ('hive', 'presto', 'spark')
    group by
         cube_vol . benchmark ,
         cube_vol . volume ,
         cube_vol . soft 
```
Throws:
```
   com.facebook.presto.sql.analyzer.SemanticException: IN value and list items must be the same type: varchar
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.coerceToSingleType(ExpressionAnalyzer.java:896)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitInPredicate(ExpressionAnalyzer.java:762)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitInPredicate(ExpressionAnalyzer.java:208)
        at com.facebook.presto.sql.tree.InPredicate.accept(InPredicate.java:41)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:226)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.coerceType(ExpressionAnalyzer.java:847)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitLogicalBinaryExpression(ExpressionAnalyzer.java:349)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitLogicalBinaryExpression(ExpressionAnalyzer.java:208)
        at com.facebook.presto.sql.tree.LogicalBinaryExpression.accept(LogicalBinaryExpression.java:59)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:226)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.coerceType(ExpressionAnalyzer.java:847)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitLogicalBinaryExpression(ExpressionAnalyzer.java:348)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitLogicalBinaryExpression(ExpressionAnalyzer.java:208)
        at com.facebook.presto.sql.tree.LogicalBinaryExpression.accept(LogicalBinaryExpression.java:59)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:181)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1019)
        at com.facebook.presto.sql.analyzer.TupleAnalyzer.analyzeExpression(TupleAnalyzer.java:1064)
        at com.facebook.presto.sql.analyzer.TupleAnalyzer.analyzeWhere(TupleAnalyzer.java:894)
        at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:345)
        at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:132)
        at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:98)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:502)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:114)
        at com.facebook.presto.sql.tree.Query.accept(Query.java:80)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:52)
        at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:198)
        at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:184)
        at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:145)
        at com.facebook.presto.execution.QueuedExecution.lambda$start$50(QueuedExecution.java:68)
        at com.facebook.presto.execution.QueuedExecution$$Lambda$143/1896681155.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by damiencarol** [comment]
If I do
```sql
describe cube_vol
```
```
+--------------------------+-----------------------+-----------------------+--+
|         col_name         |       data_type       |        comment        |
+--------------------------+-----------------------+-----------------------+--+
| benchmark                | string                |                       |
| volume                   | string                |                       |
| format                   | string                |                       |
| aggregate_report_count   | int                   |                       |
| average                  | int                   |                       |
| aggregate_report_min     | int                   |                       |
| aggregate_report_max     | int                   |                       |
| aggregate_report_stddev  | double                |                       |
| soft                     | string                |                       |
| version                  | string                |                       |
|                          | NULL                  | NULL                  |
| # Partition Information  | NULL                  | NULL                  |
| # col_name               | data_type             | comment               |
|                          | NULL                  | NULL                  |
| soft                     | string                |                       |
| version                  | string                |                       |
+--------------------------+-----------------------+-----------------------+--+
```

**Comment by damiencarol** [comment]
It seems to only affect "string  IN (varchar, varchar)"

**Comment by dain** [comment]
Can you simplify the query?  Also does it reproduce with the TPCH connector?

**Comment by damiencarol** [comment]
Will make more tests.

**Comment by damiencarol** [comment]
I can't reproduce this bug. I think it could be produced when we do ALTER TABLE foo CHANGE bar bar varchar(50) when bar is string.
