### ISSUE TITLE
Exception when doing partial cancel

### ISSUE THREAD

**Issue by electrum** [facebook/presto#2650]
```
java.lang.IllegalStateException: noMoreSplits has already been set for 35
	at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
	at com.facebook.presto.server.HttpRemoteTask.addSplits(HttpRemoteTask.java:241)
	at com.facebook.presto.execution.SqlStageExecution.addNewExchangesAndBuffers(SqlStageExecution.java:813)
	at com.facebook.presto.execution.SqlStageExecution.scheduleTask(SqlStageExecution.java:737)
	at com.facebook.presto.execution.SqlStageExecution.scheduleTask(SqlStageExecution.java:731)
	at com.facebook.presto.execution.SqlStageExecution.scheduleFixedNodeCount(SqlStageExecution.java:601)
	at com.facebook.presto.execution.SqlStageExecution.startTasks(SqlStageExecution.java:552)
	at com.facebook.presto.execution.SqlStageExecution$$Lambda$571/160040220.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wesleychowadroll** [comment]
One of our clusters started getting this out of the blue. It's been running the same query every hour for weeks, then last night it started logging this and queries would return pretty much immediately with no data. Any insights into what's causing this and how to address it? Restarting the cluster doesn't seem to help. We're currently running 0.105

**Comment by dain** [comment]
I have a pending pull request that completely rewrites the SqlStageExecution and generally the query scheduler.  This should not be possible in the new code.

**Comment by wesleychowadroll** [comment]
Excellent. I'm just spinning up a new cluster in the meantime, so I'll just update to the latest version when that comes out.

Thanks for the quick response!

**Comment by martint** [comment]
The new scheduler code is in, closing. Please reopen if you see it again.
