### ISSUE TITLE
hitting error when launch presto from the current master

### ISSUE THREAD

**Issue by zhenxiao** [facebook/presto#2725]
./presto-server-0.101-SNAPSHOT/bin/launcher run
fail, in the log:

2015-04-16T16:22:51.100-0700	ERROR	main	com.facebook.presto.server.PrestoServer	Unable to create injector, see the following errors:

1) Explicit bindings are required and io.airlift.log.Logging is not explicitly bound.
  while locating io.airlift.log.Logging
    for parameter 0 at io.airlift.log.LoggingMBean.<init>(LoggingMBean.java:33)
  at io.airlift.log.LogJmxModule.configure(LogJmxModule.java:34)

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Explicit bindings are required and io.airlift.log.Logging is not explicitly bound.
  while locating io.airlift.log.Logging
    for parameter 0 at io.airlift.log.LoggingMBean.<init>(LoggingMBean.java:33)
  at io.airlift.log.LogJmxModule.configure(LogJmxModule.java:34)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:448)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:286)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:103)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:59)

Am I miss something?

**Comment by dain** [comment]
I think @electrum missed something when he updated to the newest airlift

**Comment by electrum** [comment]
This is fixed now. Please update Airlift `log-manager` to the latest snapshot version.
