### ISSUE TITLE
presto-jdbc: PrestoResultSet.getInt fails with Boolean values

### ISSUE THREAD

**Issue by lucboudreau** [facebook/presto#2732]
Most drivers will support this by returning either 0 or 1.

Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Number
	at com.facebook.presto.jdbc.PrestoResultSet.getInt(PrestoResultSet.java:223)
	at org.apache.commons.dbcp.DelegatingResultSet.getInt(DelegatingResultSet.java:186)
	at mondrian.rolap.SqlStatement$3.get(SqlStatement.java:380)

**Comment by Myrthan** [comment]
I'm claiming this one.

**Comment by electrum** [comment]
Fixed in 0ad0c84

**Comment by electrum** [comment]
Fixed in 66010b074cf81ce63e94cc43cc7361ad1a3b4e23

**Comment by lucboudreau** [comment]
Thanks guys! Great job on presto overall btw.
