### ISSUE TITLE
EXPLAIN (FORMAT JSON) fails

### ISSUE THREAD

**Issue by cberner** [facebook/presto#2755]
`explain (format JSON) select 1;`

results in
```
Query 20150420_214411_00007_9inn7 failed: not yet implemented: com.facebook.presto.sql.planner.plan.ValuesNode
java.lang.UnsupportedOperationException: not yet implemented: com.facebook.presto.sql.planner.plan.ValuesNode
	at com.facebook.presto.util.JsonPlanPrinter$SourceVisitor.visitPlan(JsonPlanPrinter.java:274)
	at com.facebook.presto.util.JsonPlanPrinter$SourceVisitor.visitPlan(JsonPlanPrinter.java:80)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitValues(PlanVisitor.java:75)
	at com.facebook.presto.sql.planner.plan.ValuesNode.accept(ValuesNode.java:72)
	at com.facebook.presto.util.JsonPlanPrinter$SourceVisitor.processChildren(JsonPlanPrinter.java:280)
	at com.facebook.presto.util.JsonPlanPrinter$SourceVisitor.visitProject(JsonPlanPrinter.java:226)
	at com.facebook.presto.util.JsonPlanPrinter$SourceVisitor.visitProject(JsonPlanPrinter.java:80)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.util.JsonPlanPrinter$SourceVisitor.processChildren(JsonPlanPrinter.java:280)
	at com.facebook.presto.util.JsonPlanPrinter$SourceVisitor.visitOutput(JsonPlanPrinter.java:232)
	at com.facebook.presto.util.JsonPlanPrinter$SourceVisitor.visitOutput(JsonPlanPrinter.java:80)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:79)
	at com.facebook.presto.util.JsonPlanPrinter.<init>(JsonPlanPrinter.java:66)
	at com.facebook.presto.util.JsonPlanPrinter.getPlan(JsonPlanPrinter.java:71)
	at com.facebook.presto.sql.planner.PlanPrinter.getJsonPlanSource(PlanPrinter.java:126)
	at com.facebook.presto.sql.analyzer.QueryExplainer.getJsonPlan(QueryExplainer.java:85)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.getQueryPlan(StatementAnalyzer.java:485)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitExplain(StatementAnalyzer.java:463)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitExplain(StatementAnalyzer.java:114)
	at com.facebook.presto.sql.tree.Explain.accept(Explain.java:54)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:52)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:200)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:186)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:147)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$52(QueuedExecution.java:68)
	at com.facebook.presto.execution.QueuedExecution$$Lambda$168/776697083.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

There also should be tests for `FORMAT JSON`

**Comment by martint** [comment]
'JSON' format for explain is no longer supported. We may introduce it later with a revised implementation.
