### ISSUE TITLE
IndexOutOfBoundsException in AddExchanges visitUnion

### ISSUE THREAD

**Issue by dain** [facebook/presto#2824]
```
java.lang.IndexOutOfBoundsException: index (0) must be less than size (0)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:310)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:292)
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:65)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitUnion(AddExchanges.java:830)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitUnion(AddExchanges.java:133)
	at com.facebook.presto.sql.planner.plan.UnionNode.accept(UnionNode.java:133)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:885)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitPlan(AddExchanges.java:156)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitPlan(AddExchanges.java:133)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitProject(PlanVisitor.java:40)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitJoin(AddExchanges.java:661)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitJoin(AddExchanges.java:133)
	at com.facebook.presto.sql.planner.plan.JoinNode.accept(JoinNode.java:158)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:885)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitPlan(AddExchanges.java:156)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitPlan(AddExchanges.java:133)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitProject(PlanVisitor.java:40)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:885)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitWindow(AddExchanges.java:309)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitWindow(AddExchanges.java:133)
	at com.facebook.presto.sql.planner.plan.WindowNode.accept(WindowNode.java:171)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:885)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:162)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:133)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:79)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges.optimize(AddExchanges.java:129)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:89)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:207)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:186)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:147)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$113(QueuedExecution.java:68)
	at com.facebook.presto.execution.QueuedExecution$$Lambda$162/282261966.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by martint** [comment]
This is possibly the issue @nileema found: https://github.com/nileema/presto/commit/898e6e1687443deb32569554dba4c2168e02efd0
