### ISSUE TITLE
Sporadic Hive test failures

### ISSUE THREAD

**Issue by electrum** [facebook/presto#2869]
This seems suspicious:
```
testEmptyTableCreation(com.facebook.presto.hive.TestHiveClient)
java.lang.RuntimeException: Primitve type DOUBLE should not take parameters
	at org.apache.hadoop.hive.serde2.lazy.objectinspector.primitive.LazyPrimitiveObjectInspectorFactory.getLazyObjectInspector(LazyPrimitiveObjectInspectorFactory.java:136)
	at org.apache.hadoop.hive.serde2.lazy.objectinspector.primitive.LazyPrimitiveObjectInspectorFactory.getLazyObjectInspector(LazyPrimitiveObjectInspectorFactory.java:113)
	at org.apache.hadoop.hive.serde2.lazy.LazyFactory.createLazyObjectInspector(LazyFactory.java:224)
	at org.apache.hadoop.hive.serde2.lazy.LazyFactory.createColumnarStructInspector(LazyFactory.java:314)
	at org.apache.hadoop.hive.serde2.columnar.ColumnarSerDe.initialize(ColumnarSerDe.java:88)
	at com.facebook.presto.hive.HiveUtil.initializeDeserializer(HiveUtil.java:333)
	at com.facebook.presto.hive.HiveUtil.getDeserializer(HiveUtil.java:295)
	at com.facebook.presto.hive.HiveUtil.getTableObjectInspector(HiveUtil.java:257)
	at com.facebook.presto.hive.HiveUtil.getTableStructFields(HiveUtil.java:274)
	at com.facebook.presto.hive.HiveUtil.hiveColumnHandles(HiveUtil.java:512)
	at com.facebook.presto.hive.HiveMetadata.getTableMetadata(HiveMetadata.java:190)
	at com.facebook.presto.hive.HiveMetadata.getTableMetadata(HiveMetadata.java:180)
	at com.facebook.presto.hive.AbstractTestHiveClient.doCreateEmptyTable(AbstractTestHiveClient.java:1447)
	at com.facebook.presto.hive.AbstractTestHiveClient.testEmptyTableCreation(AbstractTestHiveClient.java:1149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

It sometimes has a different message:
```
java.lang.RuntimeException: Primitve type LONG should not take parameters
```

**Comment by nicktrav** [comment]
I'm also running into this error when testing Hive with Spark.

Are you able to replicate the issue?

**Comment by electrum** [comment]
@nicktrav we see this sporadically from our unit tests in Jenkins, but I haven't had time to track it down.

**Comment by electrum** [comment]
This seems to be due to HIVE-10023.

**Comment by nicktrav** [comment]
Thanks for the follow up @electrum. I dug a little deeper and noticed that the issue was only with certain types of HIVE tables that were written using the `org.apache.hadoop.hive.serde2` serde. Hopefully it's fixed in an upcoming Spark release.

**Comment by yaoxin226** [comment]
This shows up frequently in our cluster there days. We are running presto 103.

**Comment by cberner** [comment]
Fixed by https://github.com/facebook/presto/pull/4396
