### ISSUE TITLE
array_sort fails with a mix of null and non-null elements

### ISSUE THREAD

**Issue by nezihyigitbasi** [facebook/presto#2903]
In addition to fixing this bug, we should determine what the null order should be as it seems like there is no null sort order defined in the standard, see [this](http://dba.stackexchange.com/questions/8504/why-are-nulls-sorted-first). Once we determine this I will be happy to provide a patch.

```Java
presto:default> select ARRAY_SORT(ARRAY [NULL, 1, 2, NULL]);
Query 20150512_175328_00135_2cpjs failed: end index (24) must not be greater than size (16)
java.lang.IndexOutOfBoundsException: end index (24) must not be greater than size (16)
	at io.airlift.slice.Preconditions.checkPositionIndexes(Preconditions.java:94)
	at io.airlift.slice.Slice.checkIndexLength(Slice.java:1022)
	at io.airlift.slice.Slice.getLong(Slice.java:366)
	at com.facebook.presto.spi.block.AbstractVariableWidthBlock.getLong(AbstractVariableWidthBlock.java:59)
	at com.facebook.presto.spi.type.BigintType.compareTo(BigintType.java:73)
	at com.facebook.presto.operator.scalar.ArraySortFunction$1.compare(ArraySortFunction.java:103)
	at com.facebook.presto.operator.scalar.ArraySortFunction$1.compare(ArraySortFunction.java:98)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:356)
	at java.util.TimSort.sort(TimSort.java:216)
	at java.util.Arrays.sort(Arrays.java:1438)
	at java.util.List.sort(List.java:478)
	at java.util.Collections.sort(Collections.java:175)
	at com.facebook.presto.operator.scalar.ArraySortFunction.sort(ArraySortFunction.java:97)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:625)
```

**Comment by martint** [comment]
The spec defines the behavior for null ordering for the ORDER BY clause. In particular, it says that if the null ordering is missing, it's implicit and implementation-defined. For array_sort, we should pick a policy consistent with what we're doing for ORDER BY, and, possibly, add a version of array_sort that takes a parameter to control how nulls are handled.

**Comment by geraint0923** [comment]
Should be fixed by #6167
