### ISSUE TITLE
ConcurrentModificationException in ClusterMemoryManager

### ISSUE THREAD

**Issue by martint** [facebook/presto#2982]
```
java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
at com.google.common.collect.Iterators$7.computeNext(Iterators.java:651)
at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
at java.util.AbstractSet.removeAll(AbstractSet.java:173)
at com.facebook.presto.memory.ClusterMemoryManager.updateNodes(ClusterMemoryManager.java:191)
at com.facebook.presto.memory.ClusterMemoryManager.process(ClusterMemoryManager.java:121)
at com.facebook.presto.execution.SqlQueryManager.enforceMemoryLimits(SqlQueryManager.java:370)
at com.facebook.presto.execution.SqlQueryManager$1.run(SqlQueryManager.java:141)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by cberner** [comment]
Fixed by https://github.com/facebook/presto/pull/2984
