### ISSUE TITLE
No plugin found for prefix 'presto-docs' in the current project - Build failure

### ISSUE THREAD

**Issue by sumanth232** [facebook/presto#3029]
This is the error I am getting while doing 'mvn clean install' .

No plugin found for prefix 'presto-docs' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/var/root/.m2/repository), sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
org.apache.maven.plugin.prefix.NoPluginFoundForPrefixException: No plugin found for prefix 'presto-docs' in the current project and in the plugin groups [org.tomdz.maven, com.mycila, com.facebook.presto, org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/var/root/.m2/repository), sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots), central (https://repo.maven.apache.org/maven2)]

The build failed at this point :

[INFO] --- sphinx-maven-plugin:1.0.3:generate (default) @ presto-docs ---
[INFO] Unpacking sphinx to /Users/sprinklr/tools/presto/presto-docs/target/sphinx
[ERROR] Exception in thread "main" javax.script.ScriptException: ValueError: unknown locale: UTF-8 in <script> at line number 1
[ERROR] 	at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:191)
[ERROR] 	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42)
[ERROR] 	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
[ERROR] 	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
[ERROR] 	at org.tomdz.maven.sphinx.SphinxRunner.run(SphinxRunner.java:59)
[ERROR] 	at org.tomdz.maven.sphinx.SphinxRunner.main(SphinxRunner.java:25)
[ERROR] Caused by: Traceback (most recent call last):
[ERROR]   File "<script>", line 1, in <module>
[ERROR]   File "/Users/sprinklr/tools/presto/presto-docs/target/sphinx/sphinx/__init__.py", line 47, in main
[ERROR]     from sphinx import cmdline
[ERROR]   File "/Users/sprinklr/tools/presto/presto-docs/target/sphinx/sphinx/__init__.py", line 47, in main
[ERROR]     from sphinx import cmdline
[ERROR]   File "/Users/sprinklr/tools/presto/presto-docs/target/sphinx/sphinx/cmdline.py", line 18, in <module>
[ERROR]     from docutils.utils import SystemMessage
[ERROR]   File "/Users/sprinklr/tools/presto/presto-docs/target/sphinx/docutils/utils/__init__.py", line 19, in <module>
[ERROR]     from docutils.io import FileOutput
[ERROR]   File "/Users/sprinklr/tools/presto/presto-docs/target/sphinx/docutils/io.py", line 18, in <module>
[ERROR]     from docutils.error_reporting import locale_encoding, ErrorString, ErrorOutput
[ERROR]   File "/Users/sprinklr/tools/presto/presto-docs/target/sphinx/docutils/error_reporting.py", line 47, in <module>
[ERROR]     locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
[ERROR]   File "/private/var/root/.m2/repository/org/python/jython-standalone/2.5.2/jython-standalone-2.5.2.jar/Lib/locale.py", line 443, in getdefaultlocale
[ERROR]   File "/private/var/root/.m2/repository/org/python/jython-standalone/2.5.2/jython-standalone-2.5.2.jar/Lib/locale.py", line 375, in _parse_localename
[ERROR] ValueError: unknown locale: UTF-8
[ERROR] 
[ERROR] 	at org.python.core.PyException.doRaise(PyException.java:200)
[ERROR] 	at org.python.core.Py.makeException(Py.java:1225)
[ERROR] 	at org.python.core.Py.makeException(Py.java:1229)
[ERROR] 	at locale$py._parse_localename$14(/private/var/root/.m2/repository/org/python/jython-standalone/2.5.2/jython-standalone-2.5.2.jar/Lib/locale.py:375)
[ERROR] 	at locale$py.call_function(/private/var/root/.m2/repository/org/python/jython-standalone/2.5.2/jython-standalone-2.5.2.jar/Lib/locale.py)
[ERROR] 	at org.python.core.PyTableCode.call(PyTableCode.java:165)
[ERROR] 	at org.python.core.PyBaseCode.call(PyBaseCode.java:134)
[ERROR] 	at org.python.core.PyFunction.__call__(PyFunction.java:317)
[ERROR] 	at locale$py.getdefaultlocale$16(/private/var/root/.m2/repository/org/python/jython-standalone/2.5.2/jython-standalone-2.5.2.jar/Lib/locale.py:443)
[ERROR] 	at locale$py.call_function(/private/var/root/.m2/repository/org/python/jython-standalone/2.5.2/jython-standalone-2.5.2.jar/Lib/locale.py)
[ERROR] 	at org.python.core.PyTableCode.call(PyTableCode.java:165)
[ERROR] 	at org.python.core.PyBaseCode.call(PyBaseCode.java:301)
[ERROR] 	at org.python.core.PyBaseCode.call(PyBaseCode.java:114)
[ERROR] 	at org.python.core.PyFunction.__call__(PyFunction.java:307)
[ERROR] 	at docutils.error_reporting$py.f$0(/Users/sprinklr/tools/presto/presto-docs/target/sphinx/docutils/error_reporting.py:131)
[ERROR] 	at docutils.error_reporting$py.call_function(/Users/sprinklr/tools/presto/presto-docs/target/sphinx/docutils/error_reporting.py)
[ERROR] 	at org.python.core.PyTableCode.call(PyTableCode.java:165)
[ERROR] 	at org.python.core.PyCode.call(PyCode.java:18)
[ERROR] 	at org.python.core.imp.createFromCode(imp.java:386)
[ERROR] 	at org.python.core.imp.createFromSource(imp.java:349)
[ERROR] 	at org.python.core.imp.loadFromSource(imp.java:573)
[ERROR] 	at org.python.core.imp.find_module(imp.java:473)
[ERROR] 	at org.python.core.PyModule.impAttr(PyModule.java:100)
[ERROR] 	at org.python.core.imp.import_next(imp.java:715)
[ERROR] 	at org.python.core.imp.import_logic(imp.java:777)
[ERROR] 	at org.python.core.imp.import_name(imp.java:839)
[ERROR] 	at org.python.core.imp.importName(imp.java:884)
[ERROR] 	at org.python.core.ImportFunction.__call__(__builtin__.java:1220)
[ERROR] 	at org.python.core.PyObject.__call__(PyObject.java:357)
[ERROR] 	at org.python.core.__builtin__.__import__(__builtin__.java:1173)
[ERROR] 	at org.python.core.imp.importFromAs(imp.java:978)
[ERROR] 	at org.python.core.imp.importFrom(imp.java:954)
[ERROR] 	at docutils.io$py.f$0(/Users/sprinklr/tools/presto/presto-docs/target/sphinx/docutils/io.py:485)
[ERROR] 	at docutils.io$py.call_function(/Users/sprinklr/tools/presto/presto-docs/target/sphinx/docutils/io.py)
[ERROR] 	at org.python.core.PyTableCode.call(PyTableCode.java:165)
[ERROR] 	at org.python.core.PyCode.call(PyCode.java:18)
[ERROR] 	at org.python.core.imp.createFromCode(imp.java:386)
[ERROR] 	at org.python.core.imp.createFromSource(imp.java:349)
[ERROR] 	at org.python.core.imp.loadFromSource(imp.java:573)
[ERROR] 	at org.python.core.imp.find_module(imp.java:473)
[ERROR] 	at org.python.core.PyModule.impAttr(PyModule.java:100)
[ERROR] 	at org.python.core.imp.import_next(imp.java:715)
[ERROR] 	at org.python.core.imp.import_logic(imp.java:777)
[ERROR] 	at org.python.core.imp.import_name(imp.java:839)
[ERROR] 	at org.python.core.imp.importName(imp.java:884)
[ERROR] 	at org.python.core.ImportFunction.__call__(__builtin__.java:1220)
[ERROR] 	at org.python.core.PyObject.__call__(PyObject.java:357)
[ERROR] 	at org.python.core.__builtin__.__import__(__builtin__.java:1173)
[ERROR] 	at org.python.core.imp.importFromAs(imp.java:978)
[ERROR] 	at org.python.core.imp.importFrom(imp.java:954)
[ERROR] 	at docutils.utils$py.f$0(/Users/sprinklr/tools/presto/presto-docs/target/sphinx/docutils/utils/__init__.py:666)
[ERROR] 	at docutils.utils$py.call_function(/Users/sprinklr/tools/presto/presto-docs/target/sphinx/docutils/utils/__init__.py)
[ERROR] 	at org.python.core.PyTableCode.call(PyTableCode.java:165)
[ERROR] 	at org.python.core.PyCode.call(PyCode.java:18)
[ERROR] 	at org.python.core.imp.createFromCode(imp.java:386)
[ERROR] 	at org.python.core.imp.createFromSource(imp.java:349)
[ERROR] 	at org.python.core.imp.loadFromSource(imp.java:573)
[ERROR] 	at org.python.core.imp.find_module(imp.java:473)
[ERROR] 	at org.python.core.PyModule.impAttr(PyModule.java:100)
[ERROR] 	at org.python.core.imp.import_next(imp.java:715)
[ERROR] 	at org.python.core.imp.import_logic(imp.java:777)
[ERROR] 	at org.python.core.imp.import_name(imp.java:839)
[ERROR] 	at org.python.core.imp.importName(imp.java:884)
[ERROR] 	at org.python.core.ImportFunction.__call__(__builtin__.java:1220)
[ERROR] 	at org.python.core.PyObject.__call__(PyObject.java:357)
[ERROR] 	at org.python.core.__builtin__.__import__(__builtin__.java:1173)
[ERROR] 	at org.python.core.imp.importFromAs(imp.java:978)
[ERROR] 	at org.python.core.imp.importFrom(imp.java:954)
[ERROR] 	at sphinx.cmdline$py.f$0(/Users/sprinklr/tools/presto/presto-docs/target/sphinx/sphinx/cmdline.py:60)
[ERROR] 	at sphinx.cmdline$py.call_function(/Users/sprinklr/tools/presto/presto-docs/target/sphinx/sphinx/cmdline.py)
[ERROR] 	at org.python.core.PyTableCode.call(PyTableCode.java:165)
[ERROR] 	at org.python.core.PyCode.call(PyCode.java:18)
[ERROR] 	at org.python.core.imp.createFromCode(imp.java:386)
[ERROR] 	at org.python.core.imp.createFromSource(imp.java:349)
[ERROR] 	at org.python.core.imp.loadFromSource(imp.java:573)
[ERROR] 	at org.python.core.imp.find_module(imp.java:473)
[ERROR] 	at org.python.core.PyModule.impAttr(PyModule.java:100)
[ERROR] 	at org.python.core.PyModule.__findattr_ex__(PyModule.java:127)
[ERROR] 	at org.python.core.PyObject.__findattr__(PyObject.java:863)
[ERROR] 	at org.python.core.imp.import_name(imp.java:849)
[ERROR] 	at org.python.core.imp.importName(imp.java:884)
[ERROR] 	at org.python.core.ImportFunction.__call__(__builtin__.java:1220)
[ERROR] 	at org.python.core.PyObject.__call__(PyObject.java:357)
[ERROR] 	at org.python.core.__builtin__.__import__(__builtin__.java:1173)
[ERROR] 	at org.python.core.imp.importFromAs(imp.java:978)
[ERROR] 	at org.python.core.imp.importFrom(imp.java:954)
[ERROR] 	at sphinx$py.main$1(/Users/sprinklr/tools/presto/presto-docs/target/sphinx/sphinx/__init__.py:72)
[ERROR] 	at sphinx$py.call_function(/Users/sprinklr/tools/presto/presto-docs/target/sphinx/sphinx/__init__.py)
[ERROR] 	at org.python.core.PyTableCode.call(PyTableCode.java:165)
[ERROR] 	at org.python.core.PyBaseCode.call(PyBaseCode.java:134)
[ERROR] 	at org.python.core.PyFunction.__call__(PyFunction.java:317)
[ERROR] 	at org.python.pycode._pyx1.f$0(<script>:1)
[ERROR] 	at org.python.pycode._pyx1.call_function(<script>)
[ERROR] 	at org.python.core.PyTableCode.call(PyTableCode.java:165)
[ERROR] 	at org.python.core.PyCode.call(PyCode.java:18)
[ERROR] 	at org.python.core.Py.runCode(Py.java:1261)
[ERROR] 	at org.python.core.__builtin__.eval(__builtin__.java:484)
[ERROR] 	at org.python.core.__builtin__.eval(__builtin__.java:488)
[ERROR] 	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:198)
[ERROR] 	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:40)
[ERROR] 	... 4 more

Please guide me to oversome this

**Comment by sumanth232** [comment]
This is locale setting problem in Mac OS X 

This is solved by setting it to correct locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8


http://stackoverflow.com/questions/19961239/pelican-3-3-pelican-quickstart-error-valueerror-unknown-locale-utf-8
