### ISSUE TITLE
Not able to connect Mysql database to presto  - No factory for connector mysql

### ISSUE THREAD

**Issue by sumanth232** [facebook/presto#3038]
I always get this error when trying to start the Presto server in Intellij.
2015-06-05T19:30:32.293+0530	ERROR	main	com.facebook.presto.server.PrestoServer	No factory for connector mysql
java.lang.IllegalArgumentException: No factory for connector mysql
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:131)
	at com.facebook.presto.metadata.CatalogManager.loadCatalog(CatalogManager.java:88)
	at com.facebook.presto.metadata.CatalogManager.loadCatalogs(CatalogManager.java:70)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:107)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

2015-06-05T19:30:32.294+0530	INFO	Thread-88	io.airlift.bootstrap.LifeCycleManager	Life cycle stopping...

Process finished with exit code 1
Pls help

I installed mysql using brew.

$ cat etc/catalog/mysql.properties
connector.name=mysql
connection-url=jdbc:mysql://localhost:3306
connection-user=root
connection-password=asd

**Comment by yuananf** [comment]
What is your presto version? The latest version is 0.107.
Besides, the connection-url should not use localhost, better to use hostname or IP.

**Comment by sumanth232** [comment]
I am using the lastest version 0.107.

Pls give an example on how to to write the connection-url

**Comment by vamsivinjam** [comment]
String driverName = "com.facebook.presto.jdbc.PrestoDriver";
Connection con = DriverManager.getConnection("jdbc:presto://ip:8082/", "username", "pawd");

**Comment by sumanth232** [comment]
@yuananf , I have tried all the permutations and combinations for the connection-url, but getting the same error. Pls help.

**Comment by sumanth232** [comment]
@vamsivinjam , I didn't get what you are trying to say.
I have to set the connection-uel in the etc/catalog/mysql.properties file. 
Mysql is running on the port 3306

**Comment by yuananf** [comment]
Can you list your plugin directory? And can you show more information about your cluster? Like how many nodes is in your cluster, did you synchronize the plugin and config?

**Comment by sumanth232** [comment]
I am a beginner who is trying to use presto based on the instructions provided on the github page.
I just want to see , how the Mysql connector works in presto. I am planning to write a ElasticSearch connector for Presto.

**Comment by vamsivinjam** [comment]
u have to give this url in ur code (eg:java) and what ever your sql port u have to give that port number.....im working on single node

**Comment by sumanth232** [comment]
@vamsivinjam , do you mean, I need to edit the code of presto ?

**Comment by sumanth232** [comment]
@yuananf , I could start the presto server without the mysql.properties file.

presto:default> SELECT * FROM system.runtime.nodes;
               node_id                |         http_uri          | node_version | coordinator | active 
--------------------------------------+---------------------------+--------------+-------------+--------
 ffffffff-ffff-ffff-ffff-ffffffffffff | http://172.16.11.209:8080 | testversion  | true        | true   
(1 row)

Query 20150608_073129_00002_p4khy, FINISHED, 1 node
Splits: 2 total, 2 done (100.00%)
0:00 [1 rows, 74B] [13 rows/s, 969B/s]

**Comment by yuananf** [comment]
You run presto on a single-node?

**Comment by sumanth232** [comment]
@yuananf , yes I am running it on a single node.

$ cat etc/catalog/config.properties

# sample nodeId to provide consistency across test runs
node.id=ffffffff-ffff-ffff-ffff-ffffffffffff
node.environment=test
http-server.http.port=8080

discovery-server.enabled=true
discovery.uri=http://localhost:8080

exchange.http-client.max-connections=1000
exchange.http-client.max-connections-per-server=1000
exchange.http-client.connect-timeout=1m
exchange.http-client.read-timeout=1m

scheduler.http-client.max-connections=1000
scheduler.http-client.max-connections-per-server=1000
scheduler.http-client.connect-timeout=1m
scheduler.http-client.read-timeout=1m

query.client.timeout=5m
query.max-age=30m

plugin.bundles=\
  ../presto-raptor/pom.xml,\
  ../presto-hive-cdh4/pom.xml,\
  ../presto-example-http/pom.xml,\
  ../presto-kafka/pom.xml, \
  ../presto-tpch/pom.xml

presto.version=testversion
experimental-syntax-enabled=true
distributed-joins-enabled=true


$ cat etc/catalog/node.properties

node.environment=production
node.id=ffffffff-ffff-ffff-ffff-ffffffffffff
node.data-dir=/Users/sprinklr/tools/data

**Comment by yuananf** [comment]
for plugin.bundles, why don't you add mysql here

**Comment by sumanth232** [comment]
@yuananf , Thank you so much for your time, bro. The presto server started in Intellij after adding in the plugin.bundles.

But, the queries on mysql database are throwing errors. 

$ presto-cli/target/presto.jar

presto:default> SHOW SCHEMAS FROM mysql;

Query 20150608_094513_00003_a6qne, FAILED, 1 node
Splits: 2 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20150608_094513_00003_a6qne failed: null


![screenshot 2015-06-08 14 49 03](https://cloud.githubusercontent.com/assets/4672368/8032309/ad382da6-0df2-11e5-967c-52033f4e4c69.png)

**Comment by sumanth232** [comment]
@yuananf 

```
2015-06-08T18:10:15.985+0530    ERROR   SplitRunner-12-60   com.facebook.presto.execution.TaskExecutor  Error processing Split 20150608_124015_00003_j4z2k.1.0-0 (start = 1433767215966, wall = 19 ms, cpu = 0 ms, calls = 1)
java.lang.NullPointerException
    at com.facebook.presto.plugin.mysql.MySqlClient.getSchemaNames(MySqlClient.java:57)
    at com.facebook.presto.plugin.jdbc.JdbcMetadata.listSchemaNames(JdbcMetadata.java:61)
    at com.facebook.presto.metadata.MetadataManager.listSchemaNames(MetadataManager.java:206)
    at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.buildSchemata(InformationSchemaPageSourceProvider.java:241)
    at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInformationSchemaTable(InformationSchemaPageSourceProvider.java:130)
    at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInternalTable(InformationSchemaPageSourceProvider.java:115)
    at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.createPageSource(InformationSchemaPageSourceProvider.java:86)
    at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:44)
    at com.facebook.presto.operator.TableScanOperator.createSourceIfNecessary(TableScanOperator.java:258)
    at com.facebook.presto.operator.TableScanOperator.isFinished(TableScanOperator.java:206)
    at com.facebook.presto.operator.Driver.processInternal(Driver.java:377)
    at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
    at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:586)
    at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
    at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:639)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```
