### ISSUE TITLE
Unknown field t1.c1:array<bigint>

### ISSUE THREAD

**Issue by joy-yao** [facebook/presto#3099]
After renaming a column in Hive: 
```
ALTER TABLE t1 CHANGE COLUMN old_c1 c1 array\<bigint\>
```
This throws an exception:
```
SELECT * FROM t1
Query failed: Unknown field t1.c1:array\<bigint\>
java.lang.IllegalArgumentException: Unknown field t1.c1:array\<bigint\>
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitTable(TupleAnalyzer.java:252)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitTable(TupleAnalyzer.java:135)
	at com.facebook.presto.sql.tree.Table.accept(Table.java:36)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.analyzeFrom(TupleAnalyzer.java:958)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:349)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:135)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:98)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:520)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:115)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:80)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:52)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:252)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:238)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:202)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$163(QueuedExecution.java:68)
	at com.facebook.presto.execution.QueuedExecution$$Lambda$222/659591746.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by electrum** [comment]
This is caused by #3105
