### ISSUE TITLE
Bug in property derivations for UNNEST

### ISSUE THREAD

**Issue by martint** [facebook/presto#3165]
```sql
SELECT * FROM orders, UNNEST(ARRAY[1])
```

fails with the following exception (run with TestTpchDistributedQueries)

```
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Optional.<init>(Optional.java:96)
	at java.util.Optional.of(Optional.java:108)
	at com.facebook.presto.sql.planner.optimizations.PropertyDerivations$Visitor.lambda$visitExchange$226(PropertyDerivations.java:304)
	at com.facebook.presto.sql.planner.optimizations.PropertyDerivations$Visitor$$Lambda$231/1206340351.apply(Unknown Source)
	at com.facebook.presto.sql.planner.optimizations.ActualProperties.translate(ActualProperties.java:139)
	at com.facebook.presto.sql.planner.optimizations.PropertyDerivations$Visitor.visitExchange(PropertyDerivations.java:304)
	at com.facebook.presto.sql.planner.optimizations.PropertyDerivations$Visitor.visitExchange(PropertyDerivations.java:98)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:148)
	at com.facebook.presto.sql.planner.optimizations.PropertyDerivations.deriveProperties(PropertyDerivations.java:95)
	at com.facebook.presto.sql.planner.optimizations.PropertyDerivations.deriveProperties(PropertyDerivations.java:90)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.deriveProperties(AddExchanges.java:900)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.withDerivedProperties(AddExchanges.java:895)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:176)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:135)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:79)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges.optimize(AddExchanges.java:131)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:93)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:259)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:238)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:202)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$2(QueuedExecution.java:68)
	at com.facebook.presto.execution.QueuedExecution$$Lambda$157/524802461.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by martint** [comment]
You can add this test case to AbstractTestQueries:


```java
assertQuery("SELECT * FROM orders, UNNEST(ARRAY[1])", "SELECT orders.*, 1 FROM orders");
```
