### ISSUE TITLE
Analyzer error when row field reference is used in aggregation query

### ISSUE THREAD

**Issue by martint** [facebook/presto#3173]
The following query (add it to AbstractTestQueries)

```
SELECT a.col0, count(*) FROM (VALUES ROW(test_row(1, 1))) t(a)
```

fails with an exception instead of "a.col0 not in GROUP BY clause":

```
java.lang.IllegalStateException: No fields for name 'a.col0'
	at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
	at com.facebook.presto.sql.analyzer.AggregationAnalyzer$Visitor.visitQualifiedNameReference(AggregationAnalyzer.java:339)
	at com.facebook.presto.sql.analyzer.AggregationAnalyzer$Visitor.visitQualifiedNameReference(AggregationAnalyzer.java:133)
	at com.facebook.presto.sql.tree.QualifiedNameReference.accept(QualifiedNameReference.java:39)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.AggregationAnalyzer$Visitor.process(AggregationAnalyzer.java:428)
	at com.facebook.presto.sql.analyzer.AggregationAnalyzer.analyze(AggregationAnalyzer.java:128)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.verifyAggregations(TupleAnalyzer.java:1024)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.analyzeAggregations(TupleAnalyzer.java:987)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:358)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:135)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:98)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:520)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:115)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:80)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:52)
	at com.facebook.presto.testing.LocalQueryRunner.createDrivers(LocalQueryRunner.java:362)
	at com.facebook.presto.testing.LocalQueryRunner.execute(LocalQueryRunner.java:324)
	at com.facebook.presto.tests.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:83)
	at com.facebook.presto.tests.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:78)
	at com.facebook.presto.tests.AbstractTestQueries.testSomething(AbstractTestQueries.java:4292)
```

**Comment by joy-yao** [comment]
This is fixed in https://github.com/facebook/presto/pull/3636
