### ISSUE TITLE
UNION query fails for UnknownType

### ISSUE THREAD

**Issue by haozhun** [facebook/presto#3184]
With configuration

    optimizer.optimize-hash-generation=true

This query fails

    (VALUES NULL) UNION (VALUES NULL)

Stack trace

    com.facebook.presto.spi.PrestoException: Compiler failed and interpreter is disabled
    	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:909)
    	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:808)
    	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:410)
    	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
    	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitAggregation(LocalExecutionPlanner.java:705)
    	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitAggregation(LocalExecutionPlanner.java:410)
    	at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:160)
    	at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:242)
    	at com.facebook.presto.execution.SqlTaskExecution.<init>(SqlTaskExecution.java:164)
    	at com.facebook.presto.execution.SqlTaskExecution.createSqlTaskExecution(SqlTaskExecution.java:115)
    	at com.facebook.presto.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:80)
    	at com.facebook.presto.execution.SqlTask.updateTask(SqlTask.java:229)
    	at com.facebook.presto.execution.SqlTaskManager.updateTask(SqlTaskManager.java:265)
    	at com.facebook.presto.server.TaskResource.createOrUpdateTask(TaskResource.java:103)
    	at sun.reflect.GeneratedMethodAccessor537.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
    	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
    	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
    	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
    	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
    	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
    	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
    	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
    	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
    	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
    	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
    	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
    	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
    	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
    	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
    	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
    	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
    	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
    	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
    	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300)
    	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:62)
    	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)
    	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
    	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
    	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    	at org.eclipse.jetty.server.Server.handle(Server.java:499)
    	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
    	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
    	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: -1
    	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
    	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
    	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
    	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
    	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
    	at com.facebook.presto.sql.gen.ExpressionCompiler.compilePageProcessor(ExpressionCompiler.java:87)
    	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:897)
    	... 63 more
    Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    	at org.objectweb.asm.Frame.a(Unknown Source)
    	at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
    	at com.facebook.presto.byteCode.MethodDefinition.visit(MethodDefinition.java:253)
    	at com.facebook.presto.byteCode.MethodDefinition.visit(MethodDefinition.java:207)
    	at com.facebook.presto.byteCode.ClassDefinition.visit(ClassDefinition.java:158)
    	at com.facebook.presto.sql.gen.CompilerUtils.defineClasses(CompilerUtils.java:100)
    	at com.facebook.presto.sql.gen.CompilerUtils.defineClass(CompilerUtils.java:74)
    	at com.facebook.presto.sql.gen.CompilerUtils.defineClass(CompilerUtils.java:80)
    	at com.facebook.presto.sql.gen.ExpressionCompiler.compileProcessor(ExpressionCompiler.java:130)
    	at com.facebook.presto.sql.gen.ExpressionCompiler.compileAndInstantiate(ExpressionCompiler.java:93)
    	at com.facebook.presto.sql.gen.ExpressionCompiler.access$300(ExpressionCompiler.java:42)
    	at com.facebook.presto.sql.gen.ExpressionCompiler$1.load(ExpressionCompiler.java:53)
    	at com.facebook.presto.sql.gen.ExpressionCompiler$1.load(ExpressionCompiler.java:48)
    	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
    	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
    	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
    	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
    	... 69 more

**Comment by Myrthan** [comment]
https://gist.github.com/Myrthan/44e5df378d6b9631f450

**Comment by haozhun** [comment]
Issue seems to be in `HashGenerationOptimizer.getHashProjectNode`. The generated expression was never analyzed, and a cast from unknown to boolean should have been inserted. @cberner what can be done here?
