### ISSUE TITLE
Presto should not move predicates that can throw on input

### ISSUE THREAD

**Issue by erichwang** [facebook/presto#3232]
SAMPLE QUERY:

WITH table1 AS (
  SELECT CAST(orderkey AS VARCHAR) orderkey FROM orders
),
table2 AS (
  SELECT CASE WHEN orderkey % 2 = 0 THEN CAST(orderkey AS VARCHAR) || 'x' ELSE CAST(orderkey AS VARCHAR) END orderkey FROM orders
)
SELECT * FROM (SELECT *, CAST(orderkey AS BIGINT) FROM table1) a JOIN table2 b ON a.orderkey = b.orderkey;

presto:tiny> explain WITH table1 AS ( SELECT CAST(orderkey AS VARCHAR) orderkey FROM orders ), table2 AS ( SELECT CASE WHEN orderkey % 2 = 0 THEN CAST(orderkey AS VARCHAR) || 'x' ELSE CAST(orderkey AS VARCHAR) END orderkey FROM orders ) SELECT * FROM (SELECT *, CAST(orderkey AS BIGINT) FROM table1) a JOIN table2 b ON a.orderkey = b.orderkey;
                                                                                                                                                                         Query Plan
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 - Output[orderkey, _col1, orderkey] => [expr:varchar, expr_4:bigint, expr_20:varchar]
         orderkey := expr
         _col1 := expr_4
         orderkey := expr_20
     - Exchange[GATHER] => expr_4:bigint, expr:varchar, expr_20:varchar
         - InnerJoin[("expr" = "expr_20") AND ("expr_4" = "expr_41")] => [expr_4:bigint, expr:varchar, expr_20:varchar, expr_41:bigint]
             - Project => [expr_4:bigint, expr:varchar]
                     expr_4 := CAST(CAST("orderkey" AS VARCHAR) AS BIGINT)
                     expr := CAST("orderkey" AS VARCHAR)
                 - Filter[(CAST(CAST("orderkey" AS VARCHAR) AS BIGINT) = CAST(CAST("orderkey" AS VARCHAR) AS BIGINT))] => [orderkey:bigint]
                     - TableScan[tpch:tpch:orders:sf0.01, original constraint=true] => [orderkey:bigint]
                             LAYOUT: tpch:orders:sf0.01
                             orderkey := tpch:orderkey
             - Exchange[REPLICATE] => expr_20:varchar, expr_41:bigint
                 - Project => [expr_20:varchar, expr_41:bigint]
                         expr_20 := (CASE WHEN (("orderkey_10" % 2) = 0) THEN "concat"(CAST("orderkey_10" AS VARCHAR), 'x') ELSE CAST("orderkey_10" AS VARCHAR) END)
                         expr_41 := CAST((CASE WHEN (("orderkey_10" % 2) = 0) THEN "concat"(CAST("orderkey_10" AS VARCHAR), 'x') ELSE CAST("orderkey_10" AS VARCHAR) END) AS BIGINT)
                     - Filter[(CAST((CASE WHEN (("orderkey_10" % 2) = 0) THEN "concat"(CAST("orderkey_10" AS VARCHAR), 'x') ELSE CAST("orderkey_10" AS VARCHAR) END) AS BIGINT) = CAST((CASE WHEN (("orderkey_10" % 2) = 0) THEN "concat"(CAST
                         - TableScan[tpch:tpch:orders:sf0.01, original constraint=true] => [orderkey_10:bigint]
                                 LAYOUT: tpch:orders:sf0.01
                                 orderkey_10 := tpch:orderkey

(1 row)

Query 20150708_012948_00021_7wdf4, FINISHED, 1 node
http://localhost:8080/v1/query/20150708_012948_00021_7wdf4?pretty
Splits: 1 total, 1 done (100.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 0% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
0:02 [0 rows, 0B] [0 rows/s, 0B/s]

presto:tiny> WITH table1 AS ( SELECT CAST(orderkey AS VARCHAR) orderkey FROM orders ), table2 AS ( SELECT CASE WHEN orderkey % 2 = 0 THEN CAST(orderkey AS VARCHAR) || 'x' ELSE CAST(orderkey AS VARCHAR) END orderkey FROM orders ) SELECT * FROM (SELECT *, CAST(orderkey AS BIGINT) FROM table1) a JOIN table2 b ON a.orderkey = b.orderkey;

Query 20150708_012952_00022_7wdf4, FAILED, 1 node
http://localhost:8080/v1/query/20150708_012952_00022_7wdf4?pretty
Splits: 5 total, 0 done (0.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 40% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20150708_012952_00022_7wdf4 failed: Can not cast '2x' to BIGINT
com.facebook.presto.spi.PrestoException: Can not cast '2x' to BIGINT
	at com.facebook.presto.type.VarcharOperators.castToBigint(VarcharOperators.java:160)
	at com_facebook_presto_$gen_CursorProcessor_74.filter(Unknown Source)
	at com_facebook_presto_$gen_CursorProcessor_74.process(Unknown Source)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:204)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:380)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:639)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by martint** [comment]
Technically, it's not legal to merge or reorder filters from subqueries unless it can be proven they are equivalent.

From the ANSI spec:

> 7.4 `<table expression>`:
> * The result of a `<table expression>` is a derived table [...]
> * If all optional clauses (where, group by, having, window) are omitted, then the result of the `<table expression>` is the same as the result of the `<from clause>`. Otherwise, each specified clause is applied to the result of the previously specified clause [...]

> 7.6 `<table reference>`:
> * If a `<derived table>` or `<lateral derived table>` LDT simply containing `<query expression>` QE is specified, then the result of LDT is the result of QE.

> 7.8 `<where clause>`:
> Specify a table derived by the application of a `<search condition>` to the result of the preceding `<from clause>`.

> 1) Let T be the result of the preceding `<from clause>`.
> 2) The `<search condition>` is effectively evaluated for each row of T. The result of the `<where clause>` is a table of those rows of T for which the result of the `<search condition>` is True.

**Comment by raghavsethi** [comment]
Unassigning since it's not clear when and how we will do this, given that a ton of projections can throw.

**Comment by martint** [comment]
Here's a simpler repro:

```sql
CREATE TABLE t AS (SELECT * FROM (VALUES 0,1,2) t(x));

SELECT * 
FROM (
    SELECT 10/x a 
    FROM t 
    WHERE sin(x) > -1 AND x > 0 
) 
WHERE a > 0
```
