### ISSUE TITLE
Arrays with only one null value will throw exception when doing arrayContains

### ISSUE THREAD

**Issue by zhenxiao** [facebook/presto#3328]
We have an Array<Bigint> column in a table, one of the rows having [null] for this column, when doing:
contains(array_column, value)
the following exception will throw:
```
java.lang.IndexOutOfBoundsException: end index (8) must not be greater than size (0)
	at io.airlift.slice.Preconditions.checkPositionIndexes(Preconditions.java:94)
	at io.airlift.slice.Slice.checkIndexLength(Slice.java:1022)
	at io.airlift.slice.Slice.getLong(Slice.java:366)
	at com.facebook.presto.spi.block.AbstractVariableWidthBlock.getLong(AbstractVariableWidthBlock.java:59)
	at com.facebook.presto.spi.type.BigintType.equalTo(BigintType.java:58)
	at com.facebook.presto.operator.scalar.ArrayContains.contains(ArrayContains.java:99)
	at com.facebook.presto.$gen.CursorProcessor_1265.filter(Unknown Source)
	at com.facebook.presto.$gen.CursorProcessor_1265.process(Unknown Source)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:183)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:343)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:283)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:563)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:639)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
It is because the slice for this value [null] has lengh 0 and size 0, but when ArrayContains trying to do a:
type.equalTo(arrayBlock, i, valueBlock, 0)
Slice will trigger this exception.

@cberner @haozhun 
Do you think we could just continue, without doing type.equalTo() if the arrayBlock isNull?

**Comment by zhenxiao** [comment]
Fixed by https://github.com/facebook/presto/commit/54a24570d440a429f9587342c91631ba69ace362
