### ISSUE TITLE
Dereference of array in row throws exception in LocalExecutionPlanner

### ISSUE THREAD

**Issue by dain** [facebook/presto#3371]
```java
assertQuery("SELECT a.col1[1] FROM (VALUES ROW(test_row(TRUE, ARRAY [1], MAP(ARRAY[1, 3], ARRAY[2.0, 4.0])))) as t(a)");
```

```
java.lang.IllegalArgumentException: Can't create a symbol from a qualified name with prefix
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.facebook.presto.sql.planner.Symbol.fromQualifiedName(Symbol.java:52)
	at com.facebook.presto.sql.planner.SymbolToInputRewriter.rewriteQualifiedNameReference(SymbolToInputRewriter.java:42)
	at com.facebook.presto.sql.planner.SymbolToInputRewriter.rewriteQualifiedNameReference(SymbolToInputRewriter.java:28)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitQualifiedNameReference(ExpressionTreeRewriter.java:606)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitQualifiedNameReference(ExpressionTreeRewriter.java:56)
	at com.facebook.presto.sql.tree.QualifiedNameReference.accept(QualifiedNameReference.java:39)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.rewrite(ExpressionTreeRewriter.java:45)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitSubscriptExpression(ExpressionTreeRewriter.java:164)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitSubscriptExpression(ExpressionTreeRewriter.java:56)
	at com.facebook.presto.sql.tree.SubscriptExpression.accept(SubscriptExpression.java:35)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.rewrite(ExpressionTreeRewriter.java:45)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.rewriteWith(ExpressionTreeRewriter.java:29)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:859)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:802)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:407)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:430)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:407)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:79)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:239)
	at com.facebook.presto.execution.SqlTaskExecution.<init>(SqlTaskExecution.java:165)
```

**Comment by cberner** [comment]
@haozhun is going to look into this when he has time

**Comment by haozhun** [comment]
@joy-yao It seems you are working on this issue.

**Comment by joy-yao** [comment]
The fix is in https://github.com/facebook/presto/pull/3636
