### ISSUE TITLE
Running Presto in IDEA with postgresql

### ISSUE THREAD

**Issue by wanghaisheng** [facebook/presto#3384]
my config.properties
```
# sample nodeId to provide consistency across test runs
node.id=ffffffff-ffff-ffff-ffff-ffffffffffff
node.environment=test
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
task.max-memory=1GB
discovery-server.enabled=true
discovery.uri=http://localhost:8080


exchange.http-client.max-connections=1000
exchange.http-client.max-connections-per-server=1000
exchange.http-client.connect-timeout=1m
exchange.http-client.read-timeout=1m

scheduler.http-client.max-connections=1000
scheduler.http-client.max-connections-per-server=1000
scheduler.http-client.connect-timeout=1m
scheduler.http-client.read-timeout=1m

query.client.timeout=5m
query.max-age=30m

plugin.bundles=\
  ../presto-raptor/pom.xml,\
  ../presto-hive-cdh4/pom.xml,\
  ../presto-example-http/pom.xml,\
  ../presto-kafka/pom.xml, \
  ../presto-mysql/pom.xml, \
  ../presto-postgresql/pom.xml, \
  ../presto-tpch/pom.xml

presto.version=testversion
experimental-syntax-enabled=true
distributed-joins-enabled=true

```
add the following postgresql.properties
```
connector.name=postgresql
connection-url=jdbc:postgresql://192.168.59.103:5432/fhirbase
connection-user=fhirbase
connection-password=fhirbase
```
the server did not start 
```
2015-07-31T13:45:58.959+0800	INFO	main	Bootstrap	
2015-07-31T13:45:59.084+0800	ERROR	main	com.facebook.presto.server.PrestoServer	Unable to create injector, see the following errors:

1) Explicit bindings are required and com.facebook.presto.plugin.jdbc.cache.JdbcCacheConfig is not explicitly bound.
  while locating com.facebook.presto.plugin.jdbc.cache.JdbcCacheConfig
    for parameter 3 at com.facebook.presto.plugin.postgresql.PostgreSqlClient.<init>(PostgreSqlClient.java:40)
  at com.facebook.presto.plugin.postgresql.PostgreSqlClientModule.configure(PostgreSqlClientModule.java:30)

2) Explicit bindings are required and com.facebook.presto.plugin.jdbc.subtable.JdbcSubTableConfig is not explicitly bound.
  while locating com.facebook.presto.plugin.jdbc.subtable.JdbcSubTableConfig
    for parameter 2 at com.facebook.presto.plugin.postgresql.PostgreSqlClient.<init>(PostgreSqlClient.java:40)
  at com.facebook.presto.plugin.postgresql.PostgreSqlClientModule.configure(PostgreSqlClientModule.java:30)

2 errors
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Explicit bindings are required and com.facebook.presto.plugin.jdbc.cache.JdbcCacheConfig is not explicitly bound.
  while locating com.facebook.presto.plugin.jdbc.cache.JdbcCacheConfig
    for parameter 3 at com.facebook.presto.plugin.postgresql.PostgreSqlClient.<init>(PostgreSqlClient.java:40)
  at com.facebook.presto.plugin.postgresql.PostgreSqlClientModule.configure(PostgreSqlClientModule.java:30)

2) Explicit bindings are required and com.facebook.presto.plugin.jdbc.subtable.JdbcSubTableConfig is not explicitly bound.
  while locating com.facebook.presto.plugin.jdbc.subtable.JdbcSubTableConfig
    for parameter 2 at com.facebook.presto.plugin.postgresql.PostgreSqlClient.<init>(PostgreSqlClient.java:40)
  at com.facebook.presto.plugin.postgresql.PostgreSqlClientModule.configure(PostgreSqlClientModule.java:30)

2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:448)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:242)
	at com.facebook.presto.plugin.jdbc.JdbcConnectorFactory.create(JdbcConnectorFactory.java:68)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:147)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:133)
	at com.facebook.presto.metadata.CatalogManager.loadCatalog(CatalogManager.java:111)
	at com.facebook.presto.metadata.CatalogManager.loadCatalogs(CatalogManager.java:82)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:116)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)


2015-07-31T13:45:59.085+0800	INFO	Thread-85	io.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
```

**Comment by electrum** [comment]
These errors reference classes `JdbcCacheConfig` and `JdbcSubTableConfig` which don't exist in the main Presto source tree. Are you running a version that you modified yourself? Feel free to join our IRC channel for live help.
