### ISSUE TITLE
Deleting from a view fails with message "null"

### ISSUE THREAD

**Issue by electrum** [facebook/presto#3473]
```
Query 20150819_234246_03937_tyk28 failed: null
java.lang.NullPointerException
	at com.facebook.presto.metadata.MetadataManager.lookupConnectorFor(MetadataManager.java:683)
	at com.facebook.presto.metadata.MetadataManager.getUpdateRowIdColumnHandle(MetadataManager.java:499)
	at com.facebook.presto.sql.planner.QueryPlanner.planDelete(QueryPlanner.java:186)
	at com.facebook.presto.sql.planner.LogicalPlanner.createDeletePlan(LogicalPlanner.java:165)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:84)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:263)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:242)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:206)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$65(QueuedExecution.java:68)
	at com.facebook.presto.execution.QueuedExecution$$Lambda$523/1798497265.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by electrum** [comment]
This should fail in the analyzer with a proper error message. Longer term, we could support deletion from simple views.

**Comment by nezihyigitbasi** [comment]
@electrum got a fix for this, can you please take a look?

**Comment by electrum** [comment]
Thanks!
