### ISSUE TITLE
Filed to read Orc File in our cloud storage

### ISSUE THREAD

**Issue by yuananf** [facebook/presto#3532]
I was tying to use presto to read our own cloud storage, and I found PrestoS3FileSystem and it's really helpful. So I wrote a similar one to read files in our own cloud storage.

Everything works fine but fails with ORC file, throwing following error
```
Caused by: com.facebook.presto.hive.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type.
	at com.facebook.presto.hive.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:99)
	at com.facebook.presto.hive.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:498)
	at com.facebook.presto.hive.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:461)
	at com.facebook.presto.hive.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:579)
	at com.facebook.presto.hive.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:280)
	at com.facebook.presto.hive.protobuf.CodedInputStream.readGroup(CodedInputStream.java:240)
	at com.facebook.presto.hive.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:488)
	at com.facebook.presto.hive.protobuf.GeneratedMessage.parseUnknownField(GeneratedMessage.java:193)
	at org.apache.hadoop.hive.ql.io.orc.OrcProto$PostScript.<init>(OrcProto.java:17858)
	at org.apache.hadoop.hive.ql.io.orc.OrcProto$PostScript.<init>(OrcProto.java:17816)
	at org.apache.hadoop.hive.ql.io.orc.OrcProto$PostScript$1.parsePartialFrom(OrcProto.java:17954)
	at org.apache.hadoop.hive.ql.io.orc.OrcProto$PostScript$1.parsePartialFrom(OrcProto.java:17949)
	at com.facebook.presto.hive.protobuf.AbstractParser.parseFrom(AbstractParser.java:89)
	at com.facebook.presto.hive.protobuf.AbstractParser.parseFrom(AbstractParser.java:95)
	at com.facebook.presto.hive.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at org.apache.hadoop.hive.ql.io.orc.OrcProto$PostScript.parseFrom(OrcProto.java:18302)
	at com.facebook.presto.orc.metadata.OrcMetadataReader.readPostScript(OrcMetadataReader.java:49)
	at com.facebook.presto.orc.OrcReader.<init>(OrcReader.java:89)
	at com.facebook.presto.hive.orc.OrcPageSourceFactory.createOrcPageSource(OrcPageSourceFactory.java:152)
	... 14 more
```
My case is quite similar with https://github.com/facebook/hive-dwrf/issues/6, but my format is orc not dwrf.
BTW, other file formats works fine: ```RCFile, Text, LZO```.

Hive version ```hive-0.12.0-cdh5.1.0```
Hadoop version ```hadoop-2.3.0-cdh5.1.0```
Presto is the current master version.

@electrum @dain any suggestions?

**Comment by electrum** [comment]
Hive ORC data is read using `HdfsOrcDataSource` which only uses one method on the `FSDataInputStream`: `readFully(long position, byte[] buffer, int offset, int length)`

My initial guess is that this method is buggy in `PrestoS3FileSystem` and is not used by other file formats. However, this would mean that no one is using ORC with S3, which is surprising, or else it is a rare bug.

How reproducible is this? Does it happen every time? Always on the same file? Only for certain files?

**Comment by dain** [comment]
The key part of that stack trace are these three calls:
```
    at org.apache.hadoop.hive.ql.io.orc.OrcProto$PostScript.parseFrom(OrcProto.java:18302)
    at com.facebook.presto.orc.metadata.OrcMetadataReader.readPostScript(OrcMetadataReader.java:49)
    at com.facebook.presto.orc.OrcReader.<init>(OrcReader.java:89)
```
The system is attempting to create the `OrcReader`.  The first thing the code does is read the file footer which contains a data structure called `PostScript` which is encoded using Protobuf (a binary structure encoding from Google).  When the Protobuf library tries to decode the data, it got an error.  This is normally caused by a corrupted file.

You should be able to test if it is the file or your FileSystem implementation by down loading the file, and using the "file://" url to read it (or write a tiny program to new up an `OrcReader`)

**Comment by yuananf** [comment]
@electrum I was not using Amazon S3, but using our own cloud storage which is developed by our company. 
I think ORC in S3 is ok because Netflix had a report about it http://techblog.netflix.com/2014/10/using-presto-in-our-big-data-platform.html

The problem is always reproducible in my test environment, and always happens on ORC file format, the other file formats are ok(```RCFile, Text, LZO, Sequencefile```).

**Comment by yuananf** [comment]
@Dain my case is similar to https://github.com/facebook/hive-dwrf/issues/6.
I downloaded the orc file and put it to hdfs, then it can be read without any error. So the file is ok.
I was thinking that maybe I made some mistake on reading our own cloud storage, but the weird thing is other file formats are ok to read.

**Comment by dain** [comment]
@yuananf I'd start debugging at `com.facebook.presto.hive.orc.HdfsOrcDataSource#readInternal`, which is the only code `OrcReader` uses to fetch data.

**Comment by electrum** [comment]
Are you using the AWS SDK to talk to your cloud storage? S3 supports HTTP Range and we rely on that to do seeks. If your cloud storage looks like S3 but ignores Range that could cause this error.

**Comment by yuananf** [comment]
@electrum exactly! It was really my problem, I missed some code when doing seek.
When I fixed it, everything works fine! Thank you very much!

@dain Sorry for bothering you, thank you very much!
