### ISSUE TITLE
Fix ArrayType.equalTo to work with comparable, non-orderable types

### ISSUE THREAD

**Issue by cberner** [facebook/presto#3542]
This query should work
```
select count(*), x
from (
  select
    array[map(array[y], array[y])],
    y
  from
    (values 1, 1) t(y)
) u(x, v)
group by x;
```

but it fails with 
```
java.lang.UnsupportedOperationException: map<bigint,bigint> type is not ordered
	at com.facebook.presto.spi.type.AbstractType.compareTo(AbstractType.java:87)
	at com.facebook.presto.type.ArrayType.compareTo(ArrayType.java:107)
	at com.facebook.presto.type.ArrayType.equalTo(ArrayType.java:81)
	at com_facebook_presto_$gen_PagesHashStrategy_29762.positionEqualsRow(Unknown Source)
	at com.facebook.presto.operator.MultiChannelGroupByHash.positionEqualsCurrentRow(MultiChannelGroupByHash.java:371)
	at com.facebook.presto.operator.MultiChannelGroupByHash.putIfAbsent(MultiChannelGroupByHash.java:242)
	at com.facebook.presto.operator.MultiChannelGroupByHash.getGroupIds(MultiChannelGroupByHash.java:199)
	at com.facebook.presto.operator.HashAggregationOperator$GroupByHashAggregationBuilder.processPage(HashAggregationOperator.java:294)
	at com.facebook.presto.operator.HashAggregationOperator$GroupByHashAggregationBuilder.access$200(HashAggregationOperator.java:256)
	at com.facebook.presto.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:210)
```

**Comment by haozhun** [comment]
@raghavsethi fixes this in #3567
