### ISSUE TITLE
Raptor database errors not categorized

### ISSUE THREAD

**Issue by electrum** [facebook/presto#3602]
We need a wrapper like `DatabaseShardManager.runTransaction()` for everything that touches the metadata database, both in `DatabaseShardManager` and in `RaptorMetadata`, that throws a proper `PrestoException`.

```
org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed. [statement:"SELECT count(*)
FROM external_batches
WHERE external_batch_id = :externalBatchId", located:"SELECT count(*)
FROM external_batches
WHERE external_batch_id = :externalBatchId", rewritten:"SELECT count(*)
FROM external_batches
WHERE external_batch_id = ?", arguments:{ positional:{}, named:{externalBatchId:'773657'}, finder:[]}]
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1308)
	at org.skife.jdbi.v2.Query.fold(Query.java:167)
	at org.skife.jdbi.v2.Query.first(Query.java:262)
	at org.skife.jdbi.v2.Query.first(Query.java:254)
	at org.skife.jdbi.v2.sqlobject.ResultReturnThing$SingleValueResultReturnThing.result(ResultReturnThing.java:111)
	at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:47)
	at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:44)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:174)
	at org.skife.jdbi.v2.sqlobject.SqlObject$1.intercept(SqlObject.java:75)
	at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$32cb9a24.externalBatchExists(<generated>)
	at com.facebook.presto.raptor.metadata.DatabaseShardManager.commitShards(DatabaseShardManager.java:139)
	at com.facebook.presto.raptor.RaptorMetadata.commitInsert(RaptorMetadata.java:444)
	at com.facebook.presto.metadata.MetadataManager.commitInsert(MetadataManager.java:550)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$1.commitTable(LocalExecutionPlanner.java:1716)
	at com.facebook.presto.operator.TableCommitOperator.getOutput(TableCommitOperator.java:148)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:380)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by electrum** [comment]
Fixed in 357f579737acee52e540ae4eabaeccb52717f9c8
