### ISSUE TITLE
TestStateMachine.testSetIf() fails non-deterministically

### ISSUE THREAD

**Issue by cberner** [facebook/presto#3629]
This happens pretty frequently on Travis, so likely is some kind of race

testSetIf(com.facebook.presto.execution.TestStateMachine)  Time elapsed: 0.253 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at com.facebook.presto.execution.TestStateMachine.assertNoStateChange(TestStateMachine.java:312)
	at com.facebook.presto.execution.TestStateMachine.testSetIf(TestStateMachine.java:222)

**Comment by dain** [comment]
This is likely because the task started at `com/facebook/presto/execution/TestStateMachine.java:273` is not starting quickly enough on Travis.  The solution should be something like :
```java
        if (isTerminalState) {
            MoreFutures.tryGetFutureValue(waitChange, 1, SECONDS);
        }
        assertEquals(waitChange.isDone(), isTerminalState);
```
