### ISSUE TITLE
IndexOutOfBoundsException from generated aggregation code

### ISSUE THREAD

**Issue by dain** [facebook/presto#3770]
Saw this in production once.  I think it might be cause by an empty page.
```
java.lang.IndexOutOfBoundsException: index (1) must be less than size (1)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:310)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:292)
	at com.google.common.collect.SingletonImmutableList.get(SingletonImmutableList.java:45)
	at com_facebook_presto_$gen_BigintBigintDoubleApproxPercentileAccumulator_79.addInput(Unknown Source)
	at com.facebook.presto.operator.AggregationOperator$Aggregator.processPage(AggregationOperator.java:221)
	at com.facebook.presto.operator.AggregationOperator.addInput(AggregationOperator.java:146)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:386)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cberner** [comment]
Do you know how to reproduce this?

**Comment by dain** [comment]
We talked offline and this is not a real issue.
