### ISSUE TITLE
Planning error for query with HAVING clause

### ISSUE THREAD

**Issue by martint** [facebook/presto#3825]
The following query:

```sql
SELECT a, count(1) 
FROM (VALUES 1,2,3) t(a)
GROUP BY a
HAVING count(1) > 1 
```

Fails with:
```
java.lang.IllegalArgumentException: Invalid node. Predicate dependencies ([count_3, expr_2]) not in source plan output ([a, count, count_3])
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.facebook.presto.sql.planner.PlanSanityChecker.checkDependencies(PlanSanityChecker.java:494)
	at com.facebook.presto.sql.planner.PlanSanityChecker.access$100(PlanSanityChecker.java:63)
	at com.facebook.presto.sql.planner.PlanSanityChecker$Visitor.visitFilter(PlanSanityChecker.java:189)
	at com.facebook.presto.sql.planner.PlanSanityChecker$Visitor.visitFilter(PlanSanityChecker.java:72)
	at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:71)
	at com.facebook.presto.sql.planner.PlanSanityChecker$Visitor.visitProject(PlanSanityChecker.java:209)
	at com.facebook.presto.sql.planner.PlanSanityChecker$Visitor.visitProject(PlanSanityChecker.java:72)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.PlanSanityChecker$Visitor.visitProject(PlanSanityChecker.java:209)
	at com.facebook.presto.sql.planner.PlanSanityChecker$Visitor.visitProject(PlanSanityChecker.java:72)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.PlanSanityChecker$Visitor.visitProject(PlanSanityChecker.java:209)
	at com.facebook.presto.sql.planner.PlanSanityChecker$Visitor.visitProject(PlanSanityChecker.java:72)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.PlanSanityChecker$Visitor.visitProject(PlanSanityChecker.java:209)
	at com.facebook.presto.sql.planner.PlanSanityChecker$Visitor.visitProject(PlanSanityChecker.java:72)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.PlanSanityChecker$Visitor.visitOutput(PlanSanityChecker.java:259)
	at com.facebook.presto.sql.planner.PlanSanityChecker$Visitor.visitOutput(PlanSanityChecker.java:72)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.PlanSanityChecker.validate(PlanSanityChecker.java:69)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:95)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:266)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:245)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:209)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$171(QueuedExecution.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This works in version 0.123

**Comment by martint** [comment]
I bisected it to this commit: db5ea9183412656f9cbf2e8a9302666ac323143d
