### ISSUE TITLE
NullPointerException when reading parquet data from S3

### ISSUE THREAD

**Issue by Cidan** [facebook/presto#3827]
I've exported about 350 million records from our Cassandra database to S3 using Spark in parquet format. I then created an external table in our stand alone Hive/Hadoop cluster that points to this data, however Presto is throwing errors when certain columns are selected.

Our setup is like so:

* n Cassandra servers running Spark on top of them.
* n Hadoop servers running hive 0.13.1
* 30 Presto workers

Here is a partial schema. Unfortunately I am unable to provide the full schema, however these columns should suffice for the purposes of this issue.

```
            Column             |  Type   | Null | Partition Key | Comment
-------------------------------+---------+------+---------------+---------
 puid                          | varchar | true | false         |
 ts                            | bigint  | true | false         |
 uid                           | varchar | true | false         |
```

The error I get is:
```
2015-10-25T20:04:29.855Z        ERROR   SplitRunner-35-35       com.facebook.presto.execution.TaskExecutor      Error processing Split 20151025_200427_00176_bu25r.1.6-1 {path=s3n://xxx/part-r-00104-899794d4-cc41-4a52-8cbf-5e7f89671242.gz.parquet, start=0, length=18262360, hosts=[localhost], database=default, table=xxx, forceLocalScheduling=false, partitionName=<UNPARTITIONED>, effectivePredicate=TupleDomain:ALL} (start = 1445803468298, wall = 1557 ms, cpu = 0 ms, calls = 1)
java.lang.NullPointerException
        at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:118)
        at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:239)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:380)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587)
        at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
        at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:640)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Here are the various queries and their results:

| Query | Result |
--- | ---
`select puid from xxx` | works
`select count(puid) from xxx` | works
`select uid,ts,puid from xxx where uid is null` | works? (shows results with ts 0, incorrect)
`select count(uid) from xxx where uid is null` | works? returns 0, which is untrue
`select uid from xxx` | error
`select uid from xxx where uid is not null` | error
`select uid,puid,ts from xxx` | error

A few things to note:
* This error happens multiple times per query, each error with a different parquet file in S3 (part-r-nnnnn)
* The same error happens with multiple different types of queries.
* These same files can be read back via Spark or Hive, parsed and transformed, without issue.
* The UID isn't the only column this happens on, it's just the one I picked for this example.
* This data is sparse; some rows might be missing a column.

The pattern here is when Presto tries to load a UID that isn't a NULL, it gets the above error.

If I can provide any more information, please let me know. Thanks!

**Comment by zhenxiao** [comment]
Which presto version are you using?
Would you please try a custom build with this PR? Presto has problem reading parquet files with null values in complex types, this PR probably fix it:
https://github.com/facebook/presto/pull/3700

**Comment by Cidan** [comment]
@zhenxiao I actually -just- fixed this entire issue by setting `hive.parquet.use-column-names=true`. That being said, is there a similar option for ORC? I ran into a similar issue using ORC.

**Comment by zhenxiao** [comment]
@Cidan great you get it working. Aha, that setting is enable access parquet files by column name, instead of by column ordinal position. Seems like you do not have complex types at all. I think ORC is always accessing columns by column index, not sure about the details, let's ask @dain 
Just curious, did you evert do alter table rename to your table or alter table add columns to your table? Or there should not be problems for either column index access or column name access

**Comment by Cidan** [comment]
@zhenxiao No, we've never altered the table to rename it or add columns in any way. The error I get is actually a bit different using ORC:

```
2015-10-25T23:34:01.585Z        ERROR   SplitRunner-9-43        com.facebook.presto.execution.TaskExecutor      Error processing Split 20151025_233358_00028_skbbc.1.23-24 {path=s3n://xxx/part-r-00760-cf530cc4-3bcf-41ee-8a32-a1001f40d94e.orc, start=0, length=8772127, hosts=[localhost], database=default, table=xxx, forceLocalScheduling=false, partitionName=<UNPARTITIONED>, effectivePredicate=TupleDomain:ALL} (start = 1445816039303, wall = 2282 ms, cpu = 0 ms, calls = 1)
java.lang.UnsupportedOperationException
        at com.facebook.presto.spi.type.AbstractType.writeLong(AbstractType.java:111)
        at com.facebook.presto.orc.stream.LongStreamV2.nextLongVector(LongStreamV2.java:437)
        at com.facebook.presto.orc.reader.LongDirectStreamReader.readBlock(LongDirectStreamReader.java:111)
        at com.facebook.presto.orc.reader.LongStreamReader.readBlock(LongStreamReader.java:58)
        at com.facebook.presto.orc.OrcRecordReader.readBlock(OrcRecordReader.java:280)
        at com.facebook.presto.hive.orc.OrcPageSource$OrcBlockLoader.load(OrcPageSource.java:313)
        at com.facebook.presto.hive.orc.OrcPageSource$OrcBlockLoader.load(OrcPageSource.java:289)
        at com.facebook.presto.spi.block.LazyBlock.assureLoaded(LazyBlock.java:246)
        at com.facebook.presto.spi.Page.assureLoaded(Page.java:133)
        at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:242)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:380)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587)
        at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
        at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:640)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by electrum** [comment]
Could you send us sample Parquet and ORC files that reproduces the issue, along with the Hive CREATE TABLE statements that match the sample files? We might be able to guess the problem based on the stack trace, but having files that cause a crash will be much easier.

How are you writing this data? With Hive?

**Comment by Cidan** [comment]
@electrum The parquet issue was solved with `hive.parquet.use-column-names=true`. I can't send sample data over, unfortunately.

I'm writing the data using Spark.

**Comment by Cidan** [comment]
I'm closing this issue as the original issue is fixed. I'll open another one for the ORC error I'm seeing.

**Comment by aswinraj** [comment]
@zhenxiao the ORC issue throwing error "java.lang.UnsupportedOperationException
        at com.facebook.presto.spi.type.AbstractType.writeLong ...." is there fix for it ? can you refer that issue you have opened it.

**Comment by himanshurawatgh** [comment]
Hi @Cidan  how did you set set hive.parquet.use-column-names=true.
when setting this in hive.properties , this does not shows up in show session . and when setting this up in session , presto gives not a valid property . I have also tried hive.parquet.use_column_names=true , this does not works either .
