### ISSUE TITLE
create external hive table execution failing

### ISSUE THREAD

**Issue by anupash147** [facebook/presto#3834]
Hi,

The otherday i was able to create and delete external table from data on s3.
But today i tried the same procedure with a different table name but it failed

error message
presto:default> create external table test (a STRING);
Query 20151026_225840_00002_4mjn7 failed: line 1:8: no viable alternative at input 'create external'
create external table test (a STRING)

debug log from the server.log is
2015-10-26T22:55:58.455Z	INFO	main	com.facebook.presto.server.PrestoServer	======== SERVER STARTED ========
2015-10-26T22:58:16.677Z	WARN	http-client-shared-116	com.facebook.presto.memory.RemoteNodeMemory	Error fetching memory info from http://10.195.0.44:8090/v1/memory: java.util.concurrent.TimeoutException
2015-10-26T22:58:17.514Z	INFO	query-execution-2	com.facebook.presto.event.query.QueryMonitor	TIMELINE: Query 20151026_225816_00000_4mjn7 :: elapsed 723.00ms :: planning 216.70ms :: scheduling 420.00ms :: running 78.00ms :: finishing 8.00ms :: begin 2015-10-26T22:58:16.754Z :: end 2015-10-26T22:58:17.477Z
2015-10-26T22:58:17.913Z	INFO	query-execution-1	com.facebook.presto.event.query.QueryMonitor	TIMELINE: Query 20151026_225817_00001_4mjn7 :: elapsed 349.00ms :: planning 74.23ms :: scheduling 156.00ms :: running 92.00ms :: finishing 27.00ms :: begin 2015-10-26T22:58:17.544Z :: end 2015-10-26T22:58:17.893Z
2015-10-26T22:58:40.481Z	ERROR	http-worker-114	com.facebook.presto.execution.QueryStateMachine	Query 20151026_225840_00002_4mjn7 failed
com.facebook.presto.sql.parser.ParsingException: line 1:8: no viable alternative at input 'create external'
	at com.facebook.presto.sql.parser.SqlParser$1.syntaxError(SqlParser.java:46)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:566)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:308)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:145)
	at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:1408)
	at com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:205)
	at com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:93)
	at com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:66)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:276)
	at com.facebook.presto.server.StatementResource$Query.<init>(StatementResource.java:264)
	at com.facebook.presto.server.StatementResource.createQuery(StatementResource.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:52)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.antlr.v4.runtime.NoViableAltException
	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:1886)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:486)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:412)
	at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:843)
	... 57 more

2015-10-26T22:58:40.488Z	INFO	http-worker-114	com.facebook.presto.event.query.QueryMonitor	TIMELINE: Query 20151026_225840_00002_4mjn7 :: elapsed 0.00ms :: planning 37.65us :: scheduling 0.00ms :: running 0.00ms :: finishing 0.00ms :: begin 2015-10-26T22:58:40.479Z :: end 2015-10-26T22:58:40.479Z
2015-10-26T22:59:55.769Z	WARN	http-client-shared-154	com.facebook.presto.memory.RemoteNodeMemory	Error fetching memory info from http://10.195.0.44:8090/v1/memory: java.util.concurrent.TimeoutException

**Comment by nezihyigitbasi** [comment]
Presto doesn't support the keyword `external` that's why your query cannot be parsed. In fact, currently the tables created by Presto are `managed` tables. I have an outstanding PR (#3810) to add support for creating `external` tables with create table as select statements.

**Comment by nezihyigitbasi** [comment]
Also `STRING` is not a valid Presto type, please see the Presto documentation for the valid types. So your query should look like

```Sql
create table test (a varchar);
```
and it will create a `managed` Hive  table.

**Comment by anupash147** [comment]
ok.. Got it .. So i have to get the ddl like the table creation in hive and then access it via presto.
Correct me if wrong.

Thanks for your reply.

**Comment by kavap** [comment]
is "at" a reserved word in presto ?

**Comment by electrum** [comment]
@kavap No, it is not. You can find the list here: https://prestodb.io/docs/current/language/reserved.html
