### ISSUE TITLE
NPE in HivePageSink

### ISSUE THREAD

**Issue by electrum** [facebook/presto#3860]
```
java.lang.NullPointerException
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.facebook.presto.hive.HivePageSink.createWriter(HivePageSink.java:283)
        at com.facebook.presto.hive.HivePageSink.appendPage(HivePageSink.java:270)
        at com.facebook.presto.spi.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:41)
        at com.facebook.presto.operator.TableWriterOperator.addInput(TableWriterOperator.java:176)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:386)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587)
        at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
        at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:640)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by dain** [comment]
I'd bet that you have a null partition key, and that code is attempting to call `toString` on null.  Try changing https://github.com/facebook/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/HivePageSink.java#L282 to `Objects::toString`

**Comment by cosinequanon** [comment]
Can confirm, once I removed the null partition key I no longer saw this error.

**Comment by harunurhan** [comment]
I tried to fix this as @dain suggested. Expectedly it worked. If nobody is going to, I can create a PR for this.
Note: I also tested the solution with INSERT query from #4122 .
