### ISSUE TITLE
Query doesn't run when when default schema is specified

### ISSUE THREAD

**Issue by drnushooz** [facebook/presto#3878]
I am trying Presto 0.123 default build on Datastax Enterprise 4.7.3 which ships with cassandra 2.1.8. Presto works very well as long as I don't specify `--schema` parameter. Without that the output looks as below.
```
presto> select * from cassandra.prestotest.schools;
   name   | age 
----------+-----
 student4 |   4 
 test     |   1 
 student5 |   5 
 student6 |   6 
 student1 |   1 
 student2 |   2 
 student3 |   3 
(7 rows)

Query 20151102_042554_00014_6tk5w, FINISHED, 1 node
Splits: 2 total, 2 done (100.00%)
0:00 [7 rows, 7B] [29 rows/s, 29B/s]
```
Now I change schema with `use` statement and here is what happens.
```
presto:cassandra> select * from prestotest.schools;
Error running command: Error starting query at http://localhost:8080/v1/statement returned an invalid response: JsonResponse{statusCode=400, statusMessage=Bad Request, headers={Content-Length=[32], Date=[Mon, 02 Nov 2015 04:27:22 GMT], Content-Type=[text/plain]}, hasValue=false, value=null}
```

Here is output when presto is started in debug mode and --schema is specified.
```
$ ./presto1 --log-levels-file etc/log.properties --debug --schema cassandra
2015-11-02T04:28:17.195Z	INFO	main	io.airlift.log.Logging	Logging to stderr
2015-11-02T04:28:17.680Z	INFO	main	org.eclipse.jetty.util.log	Logging initialized @1202ms
presto:cassandra> 2015-11-02T04:28:18.627Z	WARN	completer-0	com.google.common.cache.LocalCache	Exception thrown during refresh
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error starting query at http://localhost:8080/v1/statement returned an invalid response: JsonResponse{statusCode=400, statusMessage=Bad Request, headers={Content-Length=[32], Date=[Mon, 02 Nov 2015 04:28:18 GMT], Content-Type=[text/plain]}, hasValue=false, value=null}
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137)
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348)
	at com.google.common.cache.LocalCache$Segment$1.run(LocalCache.java:2331)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.add(ExecutionList.java:101)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:170)
	at com.google.common.cache.LocalCache$Segment.loadAsync(LocalCache.java:2326)
	at com.google.common.cache.LocalCache$Segment.refresh(LocalCache.java:2389)
	at com.google.common.cache.LocalCache.refresh(LocalCache.java:4090)
	at com.google.common.cache.LocalCache$LocalLoadingCache.refresh(LocalCache.java:4843)
	at com.facebook.presto.cli.TableNameCompleter.lambda$populateCache$2(TableNameCompleter.java:95)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error starting query at http://localhost:8080/v1/statement returned an invalid response: JsonResponse{statusCode=400, statusMessage=Bad Request, headers={Content-Length=[32], Date=[Mon, 02 Nov 2015 04:28:18 GMT], Content-Type=[text/plain]}, hasValue=false, value=null}
	at com.facebook.presto.client.StatementClient.requestFailedException(StatementClient.java:279)
	at com.facebook.presto.client.StatementClient.<init>(StatementClient.java:103)
	at com.facebook.presto.cli.QueryRunner.startInternalQuery(QueryRunner.java:82)
	at com.facebook.presto.cli.TableNameCompleter.queryMetadata(TableNameCompleter.java:76)
	at com.facebook.presto.cli.TableNameCompleter.access$000(TableNameCompleter.java:37)
	at com.facebook.presto.cli.TableNameCompleter$2.load(TableNameCompleter.java:68)
	at com.facebook.presto.cli.TableNameCompleter$2.load(TableNameCompleter.java:64)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:189)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadAsync(LocalCache.java:2325)
	... 7 more


2015-11-02T04:28:18.639Z	WARN	completer-0	com.google.common.cache.LocalCache	Exception thrown during refresh
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error starting query at http://localhost:8080/v1/statement returned an invalid response: JsonResponse{statusCode=400, statusMessage=Bad Request, headers={Content-Length=[32], Date=[Mon, 02 Nov 2015 04:28:18 GMT], Content-Type=[text/plain]}, hasValue=false, value=null}
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137)
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348)
	at com.google.common.cache.LocalCache$Segment$1.run(LocalCache.java:2331)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.add(ExecutionList.java:101)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:170)
	at com.google.common.cache.LocalCache$Segment.loadAsync(LocalCache.java:2326)
	at com.google.common.cache.LocalCache$Segment.refresh(LocalCache.java:2389)
	at com.google.common.cache.LocalCache.refresh(LocalCache.java:4090)
	at com.google.common.cache.LocalCache$LocalLoadingCache.refresh(LocalCache.java:4843)
	at com.facebook.presto.cli.TableNameCompleter.lambda$populateCache$2(TableNameCompleter.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error starting query at http://localhost:8080/v1/statement returned an invalid response: JsonResponse{statusCode=400, statusMessage=Bad Request, headers={Content-Length=[32], Date=[Mon, 02 Nov 2015 04:28:18 GMT], Content-Type=[text/plain]}, hasValue=false, value=null}
	at com.facebook.presto.client.StatementClient.requestFailedException(StatementClient.java:279)
	at com.facebook.presto.client.StatementClient.<init>(StatementClient.java:103)
	at com.facebook.presto.cli.QueryRunner.startInternalQuery(QueryRunner.java:82)
	at com.facebook.presto.cli.TableNameCompleter.queryMetadata(TableNameCompleter.java:76)
	at com.facebook.presto.cli.TableNameCompleter.access$000(TableNameCompleter.java:37)
	at com.facebook.presto.cli.TableNameCompleter$1.load(TableNameCompleter.java:58)
	at com.facebook.presto.cli.TableNameCompleter$1.load(TableNameCompleter.java:54)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:189)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadAsync(LocalCache.java:2325)
	... 7 more
```
Every query responds with the 400 message.

**Comment by sbmaggarwal** [comment]
@drnushooz What was the issue you were facing?
