### ISSUE TITLE
Invalid plan for CROSS JOIN UNNEST

### ISSUE THREAD

**Issue by haozhun** [facebook/presto#3935]
```
EXPLAIN
  SELECT
    y
  FROM (
      (VALUES array[1, 2], array[3])
    UNION ALL
      (VALUES array[4, 5], array[6])
  ) t(x)
  CROSS JOIN
    UNNEST(x) u(y)
GROUP BY y
```

`AddExchanges.visitUnnest` does not exist. But it should exist and should check the preferred properties and filter the newly generated output symbol out.

```
Query 20151110_185357_00006_f7iy7 failed: index (0) must be less than size (0)
java.lang.IndexOutOfBoundsException: index (0) must be less than size (0)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:310)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:292)
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:65)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitUnion(AddExchanges.java:945)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitUnion(AddExchanges.java:173)
	at com.facebook.presto.sql.planner.plan.UnionNode.accept(UnionNode.java:133)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:970)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitPlan(AddExchanges.java:200)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitPlan(AddExchanges.java:173)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitUnnest(PlanVisitor.java:135)
	at com.facebook.presto.sql.planner.plan.UnnestNode.accept(UnnestNode.java:105)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:970)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitAggregation(AddExchanges.java:246)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitAggregation(AddExchanges.java:173)
	at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:180)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:970)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:222)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:173)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges.optimize(AddExchanges.java:135)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:101)
	at com.facebook.presto.sql.analyzer.QueryExplainer.getLogicalPlan(QueryExplainer.java:134)
	at com.facebook.presto.sql.analyzer.QueryExplainer.getPlan(QueryExplainer.java:91)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.getQueryPlan(StatementAnalyzer.java:711)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitExplain(StatementAnalyzer.java:692)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitExplain(StatementAnalyzer.java:208)
	at com.facebook.presto.sql.tree.Explain.accept(Explain.java:54)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:60)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:259)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:245)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:209)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$170(QueuedExecution.java:68)
	at com.facebook.presto.execution.QueuedExecution$$Lambda$399/184162826.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by yangyangyyy** [comment]
I'll be working on this

**Comment by haozhun** [comment]
@erichwang Is this the bug you fixed recently?

**Comment by erichwang** [comment]
this is already fixed.
