### ISSUE TITLE
Function not registered error

### ISSUE THREAD

**Issue by kyleburke** [facebook/presto#3967]
I've created a udf called ortrait. The function takes two bigints and does a bitwise or operation and returns a boolean. I've compiled the jar, copied it to all my nodes, and restarted the presto server service. When I attempt to call the function I get strange results. 

From the presto-cli when I run:
SELECT * FROM t02918.matrix3 WHERE ortrait(home,40) = true;

I get the following error:
Query 20151113_194947_00008_9gke9 failed: Unexpected parameters (varchar, bigint) for function ortrait. Expected: ortrait(bigint, bigint) 

The error leads me to believe the function has definitely been registered. When I cast the home column to a bigint list below I get the "Function not register" error.

SELECT * FROM t02918.matrix3 WHERE andTrait(cast(coalesce(home,'0') as bigint), 40) = true;

Any suggestions on how to correct this issue?

**Comment by martint** [comment]
The first query calls `ortrait`. The second one calls `andTrait`. Is that intentional?

**Comment by kyleburke** [comment]
Sorry that was a copy and paste mistake. Both functions exhibit the same error though. The orTrait does a bitwise OR operation and the "andTrait" does an bitwise AND operation.

**Comment by kyleburke** [comment]
Here is the code for both functions. I'm guessing the "Function is not registered" is a catch all type of message. 

@Description("Performs Bitwise OR operation of bitFamily and bitTrait to determine if family contains trait")
    @ScalarFunction("orTrait")
    @SqlType(StandardTypes.BOOLEAN)
    @Nullable
    public static Boolean orTrait(@Nullable @SqlType(StandardTypes.BIGINT) Long bitFamily, @Nullable @SqlType(StandardTypes.BIGINT) Long bitTrait)
    {
        return (bitFamily | bitTrait) > 0;
    }

    @Description("Performs Bitwise AND operation of bitFamily and bitTrait to determine if family contains trait")
    @ScalarFunction("andTrait")
    @SqlType(StandardTypes.BOOLEAN)
    @Nullable
    public static Boolean andTrait(@Nullable @SqlType(StandardTypes.BIGINT) Long bitFamily, @Nullable @SqlType(StandardTypes.BIGINT) Long bitTrait)
    {
        return (bitFamily & bitTrait) == bitTrait;
    }

**Comment by martint** [comment]
How are you registering the functions?

**Comment by kyleburke** [comment]
I'm using the https://github.com/qubole/presto-udfs library. Then I placed the jar file  in the "/usr/lib/presto/plugin/udfs/" directory on each of my nodes. I then restarted the presto-server several times. A few time I restarted the server using "bin/launcher run" so that I could check for error message. It took a few times until there were no errors in the logs. 

It appears that the function has definitely been registered because when I run the query below I get a the correct result. It must be something wrong with the data in the table I'm guessing? 

SELECT *,andtrait(10,2) FROM t02918.matrix3 limit 10;

**Comment by martint** [comment]
Can you paste the full error for the query that uses cast(xxx as bigint)?

Also, can if run your CLI with --debug it will print the full stack trace. Can you paste that, too?

**Comment by kyleburke** [comment]
I didn't know about the --debug flag so thank you. At least it helps figure out where to start trying to troubleshoot. He is the output:

17:24:52 [presto-udfs (master)] $ presto-cli --debug --server localhost:8889 --catalog hive --schema t02918
2015-11-13T17:25:07.806-0500	 INFO	main	io.airlift.log.Logging	Logging to stderr
2015-11-13T17:25:07.965-0500	 INFO	main	org.eclipse.jetty.util.log	Logging initialized @422ms
presto:t02918> SELECT * FROM t02918.matrix3 WHERE andTrait(cast(coalesce(home,'0') as bigint), 40) = true;

Query 20151113_222642_00010_9nujm, FAILED, 5 nodes
http://localhost:8889/v1/query/20151113_222642_00010_9nujm?pretty
Splits: 1 total, 0 done (0.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 0% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20151113_222642_00010_9nujm failed: Function andtrait not registered
com.facebook.presto.spi.PrestoException: Function andtrait not registered
	at com.facebook.presto.metadata.FunctionRegistry.resolveFunction(FunctionRegistry.java:473)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:690)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:215)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:70)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:234)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.getOperator(ExpressionAnalyzer.java:839)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitComparisonExpression(ExpressionAnalyzer.java:373)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitComparisonExpression(ExpressionAnalyzer.java:215)
	at com.facebook.presto.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:77)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:188)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressions(ExpressionAnalyzer.java:1018)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressionsWithInputs(ExpressionAnalyzer.java:1004)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypesFromInput(ExpressionAnalyzer.java:970)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:858)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitFilter(LocalExecutionPlanner.java:776)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitFilter(LocalExecutionPlanner.java:403)
	at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:71)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:235)
	at com.facebook.presto.execution.SqlTaskExecution.<init>(SqlTaskExecution.java:165)
	at com.facebook.presto.execution.SqlTaskExecution.createSqlTaskExecution(SqlTaskExecution.java:114)
	at com.facebook.presto.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:73)
	at com.facebook.presto.execution.SqlTask.updateTask(SqlTask.java:250)
	at com.facebook.presto.execution.SqlTaskManager.updateTask(SqlTaskManager.java:263)
	at com.facebook.presto.server.TaskResource.createOrUpdateTask(TaskResource.java:115)
	at sun.reflect.GeneratedMethodAccessor206.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:52)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
presto:t02918> SELECT andtrait(10,2) FROM t02918.matrix3 LIMIT 10;
 _col0 
-------
 true  
 true  
 true  
 true  
 true  
 true  
 true  
 true  
 true  
 true  
(10 rows)

Query 20151113_222815_00011_9nujm, FINISHED, 5 nodes
http://localhost:8889/v1/query/20151113_222815_00011_9nujm?pretty
Splits: 97 total, 2 done (2.06%)
CPU Time: 57.6s total,   575 rows/s, 91.2KB/s, 21% active
Per Node: 2.6 parallelism, 1.49K rows/s,  237KB/s
Parallelism: 13.0
0:04 [33.1K rows, 5.13MB] [7.47K rows/s, 1.16MB/s]

presto:t02918>

**Comment by martint** [comment]
Based on that exception, it would appear that some worker doesn't have the function available (it happens in `LocalExecutionPlanner`). 

If you open the web UI on http://localhost:8889, you should be able to track down which machine caused the failure (there will be a task marked as FAILED in the list of tasks for the query)

**Comment by martint** [comment]
The most probable reason `SELECT andtrait(10,2) FROM t02918.matrix3 LIMIT 10` works is that the function is constant-folded in the coordinator, and the query execution only has to return a constant value. You can see that by running EXPLAIN on that query.

**Comment by kyleburke** [comment]
If I do a "bin/launcher restart" on the coordinator does that also restart the workers also? or do I need to do a restart on each worker?  The jar file with the udfs are on each worker.

**Comment by martint** [comment]
No, you need to restart each worker independently.

**Comment by kyleburke** [comment]
I restarted each worker and now the functions are working great. Thanks for putting up with a Presto newbie.

**Comment by martint** [comment]
Great! Glad to hear it's working now.
