### ISSUE TITLE
Regression in output buffer creation

### ISSUE THREAD

**Issue by cberner** [facebook/presto#4071]
Caused by: java.lang.IllegalArgumentException: Broadcast partition must be 0
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.facebook.presto.execution.scheduler.BroadcastOutputBufferManager.addOutputBuffer(BroadcastOutputBufferManager.java:54)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler$StageLinkage.lambda$processScheduleResults$183(SqlQueryScheduler.java:419)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler$StageLinkage.processScheduleResults(SqlQueryScheduler.java:419)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler.schedule(SqlQueryScheduler.java:313)
	... 5 more

**Comment by dain** [comment]
Reproduces with:
```sql

select nationkey
from (
    select nationkey
    from nation
    group by nationkey
)
cross join (
    select nationkey as foo
    from nation
    group by nationkey
)
```
