### ISSUE TITLE
Raptor exception for insert

### ISSUE THREAD

**Issue by electrum** [facebook/presto#4167]
```
java.lang.UnsupportedOperationException: map<varchar,varchar> type is not orderable
	at com.facebook.presto.spi.type.AbstractType.compareTo(AbstractType.java:87)
	at com.facebook.presto.spi.block.SortOrder.compareBlockValue(SortOrder.java:62)
	at com_facebook_presto_$gen_PagesIndexComparator_5904.compareTo(Unknown Source)
	at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:87)
	at com.facebook.presto.operator.PagesIndexOrdering.sort(PagesIndexOrdering.java:37)
	at com.facebook.presto.operator.PagesIndex.sort(PagesIndex.java:305)
	at com.facebook.presto.operator.PagesIndex.sort(PagesIndex.java:300)
	at com.facebook.presto.PagesIndexPageSorter.sort(PagesIndexPageSorter.java:35)
	at com.facebook.presto.raptor.RaptorPageSink.flushPages(RaptorPageSink.java:175)
	at com.facebook.presto.raptor.RaptorPageSink.commit(RaptorPageSink.java:104)
	at com.facebook.presto.operator.TableWriterOperator.getOutput(TableWriterOperator.java:188)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:380)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by electrum** [comment]
I believe this prevents using maps in Raptor because the insertion fails. It might require an ordering column to be set on the table.

**Comment by electrum** [comment]
This seems to be fixed in recent versions.
