### ISSUE TITLE
Query failed at an unused column

### ISSUE THREAD

**Issue by soulmachine** [facebook/presto#4203]
I have a field in my parquet schema:

```json
{
   "name" : "tags",
   "type" : {
      "type" : "array",
      "elementType" : "string",
      "containsNull" : true
  }
}
```

But I don't use this field in my table at all, the following is my table's schema, there is no `tags` field:

```sql
CREATE EXTERNAL TABLE IF NOT EXISTS access_logs(
account_id_origin BIGINT,
auth STRING,
bytes BIGINT,
client_ip STRING,
content_length BIGINT,
destination STRING,
flume_node STRING,
geoip_administrative_area_level_1 STRING,
geoip_city_name STRING,
geoip_connection_type STRING,
geoip_continent_code STRING,
geoip_continent_name STRING,
geoip_country_iso_code STRING,
geoip_country_name STRING,
geoip_isp_autonomous_system_number BIGINT,
geoip_isp_autonomous_system_organization STRING,
geoip_isp_name STRING,
geoip_latitude DOUBLE,
geoip_longitude DOUBLE,
geoip_mcc BIGINT,
geoip_mnc BIGINT,
geoip_postal_code STRING,
geoip_proxy_type STRING,
host STRING,
httpversion DOUBLE,
ident STRING,
ip_type STRING,
parser STRING,
path STRING,
rawrequest STRING,
request STRING,
response BIGINT,
response_time BIGINT,
servername STRING,
tango_app_id STRING,
thread STRING,
`timestamp` BIGINT,
type STRING,
username_origin STRING,
verb STRING
)
PARTITIONED BY (year INT, month INT, day INT, hour INT)
STORED AS PARQUET
LOCATION 's3a://chef-logstash-access-structured/new/';
```

My query is:

```sql
select * from access_logs where year=2015 and month=12 and day=17 and hour=12 limit 10;
```

The stacktrace is:

    2015-12-17T19:55:18.746Z        ERROR   query-execution-77      com.facebook.presto.execution.QueryStateMachine Query 20151217_195517_00085_ruqhq failed
    java.lang.IllegalArgumentException: Column tags type LIST not supported
            at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createGroupConverter(ParquetHiveRecordCursor.java:697)
            at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.access$200(ParquetHiveRecordCursor.java:93)
            at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor$PrestoReadSupport.<init>(ParquetHiveRecordCursor.java:449)
            at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:369)
            at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.<init>(ParquetHiveRecordCursor.java:203)
            at com.facebook.presto.hive.parquet.ParquetRecordCursorProvider.createHiveRecordCursor(ParquetRecordCursorProvider.java:102)
            at com.facebook.presto.hive.HivePageSourceProvider.getHiveRecordCursor(HivePageSourceProvider.java:128)
            at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:106)
            at com.facebook.presto.spi.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:43)
            at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:48)
            at com.facebook.presto.operator.TableScanOperator.createSourceIfNecessary(TableScanOperator.java:258)
            at com.facebook.presto.operator.TableScanOperator.isFinished(TableScanOperator.java:206)
            at com.facebook.presto.operator.Driver.processInternal(Driver.java:377)
            at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
            at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587)
            at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
            at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:640)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)

Thus I can not use the wildcard `*`, instead, I need to specify columns in `select` queries, which is not convenient.

Why Presto will fail at an unused filed? Is this a bug or a feature?

**Comment by electrum** [comment]
Can you post reproduction steps for how to create such a file and corresponding table in Hive that causes the Presto error? Having this will make it much easier to debug.

**Comment by nezihyigitbasi** [comment]
@soulmachine as we discussed in #4136 , the indices of the columns in the hive table schema and the parquet file schema should match (unless you set `hive.parquet.use-column-names=true` then the names should match) otherwise a column index in the hive table schema may map to some other column in the parquet schema. If the rest of the parquet schema matches the hive table schema then using name-based access (set the above parameter to true) should do it. Otherwise you may need to re-write the parquet file to get rid of that `tags` column.

**Comment by soulmachine** [comment]
@nezihyigitbasi I'm using name-based access. I've set `hive.parquet.use-column-names=true` in Presto

**Comment by nezihyigitbasi** [comment]
@soulmachine aha I just saw that you are doing `select *`, so it won't matter whether you use name-based access or not since schemas won't match in either case. I can't think of any other solution than re-writing your parquet files (to sync their schemas with the hive table schema) if you don't want to specify columns as you point out above.

**Comment by soulmachine** [comment]
@nezihyigitbasi Thank you. This problem disappears after I restart my Presto cluster a few times, weird. I'll close this issue.
