### ISSUE TITLE
Exception in SqlQueryScheduler

### ISSUE THREAD

**Issue by electrum** [facebook/presto#4209]
This happened when I ran the query while the cluster was starting, probably before any of the workers were online.

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler.createStages(SqlQueryScheduler.java:191)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler.<init>(SqlQueryScheduler.java:102)
	at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:300)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:207)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$269(QueuedExecution.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by bigdatasunil** [comment]
can anyone tell me how to fix this issue?

**Comment by petroav** [comment]
@bigdatasunil it looks like this bug was fixed a while back so if you're running the latest Presto version you shouldn't see it. If you are running into it then open a new issue with a simple reproducible case.
