### ISSUE TITLE
Sporadic failure in TestSerDeUtils

### ISSUE THREAD

**Issue by electrum** [facebook/presto#4256]
We see this error occasionally in the CI:

```java
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at com.facebook.presto.hive.util.SerDeUtils.serializeStruct(SerDeUtils.java:214)
	at com.facebook.presto.hive.util.SerDeUtils.serializeObject(SerDeUtils.java:79)
	at com.facebook.presto.hive.util.SerDeUtils.getBlockObject(SerDeUtils.java:65)
	at com.facebook.presto.hive.util.TestSerDeUtils.toBinaryBlock(TestSerDeUtils.java:304)
	at com.facebook.presto.hive.util.TestSerDeUtils.testStructBlock(TestSerDeUtils.java:211)

**Comment by electrum** [comment]
Happened again here: https://travis-ci.org/facebook/presto/jobs/100655796

**Comment by raghavsethi** [comment]
Happens to me too.

**Comment by cberner** [comment]
For reference here's the test that failed for me:
```
testMapBlock(com.facebook.presto.hive.util.TestSerDeUtils)  Time elapsed: 0.013 sec  <<< FAILURE!
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at com.facebook.presto.hive.util.SerDeUtils.serializeStruct(SerDeUtils.java:214)
	at com.facebook.presto.hive.util.SerDeUtils.serializeObject(SerDeUtils.java:79)
	at com.facebook.presto.hive.util.SerDeUtils.serializeMap(SerDeUtils.java:191)
	at com.facebook.presto.hive.util.SerDeUtils.serializeObject(SerDeUtils.java:77)
	at com.facebook.presto.hive.util.SerDeUtils.serializeStruct(SerDeUtils.java:225)
	at com.facebook.presto.hive.util.SerDeUtils.serializeObject(SerDeUtils.java:79)
	at com.facebook.presto.hive.util.SerDeUtils.getBlockObject(SerDeUtils.java:65)
	at com.facebook.presto.hive.util.TestSerDeUtils.toBinaryBlock(TestSerDeUtils.java:304)
	at com.facebook.presto.hive.util.TestSerDeUtils.testMapBlock(TestSerDeUtils.java:192)
```

**Comment by haozhun** [comment]
I think it's caused by HIVE-11586

**Comment by cberner** [comment]
Fixed by https://github.com/facebook/presto/pull/4396
