### ISSUE TITLE
failed to write InterleavedBlock with more than 3 elements

### ISSUE THREAD

**Issue by haitaoyao** [facebook/presto#4279]
HI, I'm developing a connector, and encountered a strange error when I serialize a Map or Row type column with more than 3 elements inside. Can somebody tell me why this happens? thanks.

Here's the code 
```java
         final ImmutableList<Type> fieldTypes = ImmutableList.of(
          VarcharType.VARCHAR,
          VarcharType.VARCHAR,
          VarcharType.VARCHAR,
          VarcharType.VARCHAR,
          VarcharType.VARCHAR,
          VarcharType.VARCHAR
          );
        final BlockBuilder blockBuilder = new InterleavedBlockBuilder(fieldTypes,
          new BlockBuilderStatus(), expectedEntries);
        VarcharType.VARCHAR.writeString(blockBuilder, pbUserAudio.getDeviceModel());
        VarcharType.VARCHAR.writeString(blockBuilder, pbUserAudio.getAppVersion());
        VarcharType.VARCHAR.writeString(blockBuilder, pbUserAudio.getOsVersion());
        VarcharType.VARCHAR.writeString(blockBuilder, "" + pbUserAudio.getRecordTimezone());
        VarcharType.VARCHAR.writeString(blockBuilder, "" +pbUserAudio.getRecordTimestamp());
        VarcharType.VARCHAR.writeString(blockBuilder, "" + pbUserAudio.getMode());
        return blockBuilder.build();

```
And here's the stacktrace: 
```

2016-01-05T20:28:40.569+0800	ERROR	query-execution-1	com.facebook.presto.execution.QueryStateMachine	Query 20160105_122838_00002_g5dsi failed
java.lang.IllegalArgumentException: position is not valid
	at com.facebook.presto.spi.block.AbstractVariableWidthBlock.checkReadablePosition(AbstractVariableWidthBlock.java:169)
	at com.facebook.presto.spi.block.AbstractVariableWidthBlock.isNull(AbstractVariableWidthBlock.java:157)
	at com.facebook.presto.spi.block.AbstractInterleavedBlock.isNull(AbstractInterleavedBlock.java:288)
	at com.facebook.presto.operator.scalar.RowFieldReference.sliceAccessor(RowFieldReference.java:131)
	at com_facebook_presto_$gen_PageProcessor_45.project_0(Unknown Source)
	at com_facebook_presto_$gen_PageProcessor_45.process(Unknown Source)
	at com.facebook.presto.operator.FilterAndProjectOperator.getOutput(FilterAndProjectOperator.java:91)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:380)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by haitaoyao** [comment]
And if I query for the whole row type column, it just returns 3 elements only in the result. but the row type columns has 6 row fields. so strange.

**Comment by haozhun** [comment]
I read both your email in the mailing list and the example you shown above. It doesn't look like there's anything wrong in the code you shared.

Can you please tell us what the declared type of the column is? For example, you can run `describe tableName`.

Additionally, it would also help if you can show more code (context of the example you shared).

**Comment by haitaoyao** [comment]
@haozhun Thank you . 
Here's how I define my row type column: 

```java
    static RowType pbAudioType() {
        ImmutableList.Builder<RowType.RowField> builder = ImmutableList.builder();
        builder.add(new RowType.RowField(VarcharType.VARCHAR, Optional.of("device_model")));
        builder.add(new RowType.RowField(VarcharType.VARCHAR, Optional.of("os_version")));
        builder.add(new RowType.RowField(VarcharType.VARCHAR, Optional.of("app_version")));
        builder.add(new RowType.RowField(VarcharType.VARCHAR, Optional.of("record_timezone")));
        builder.add(new RowType.RowField(VarcharType.VARCHAR, Optional.of("record_timestamp")));
        builder.add(new RowType.RowField(VarcharType.VARCHAR, Optional.of("mode")));

        final List<RowType.RowField> rowFields = builder.build();
        final List<Type> rowFieldTypes = Lists.newArrayListWithCapacity(rowFields.size());
        final List<String> filedNames = Lists.newArrayListWithCapacity(rowFields.size());
        rowFields.forEach(field -> {
            rowFieldTypes.add(field.getType());
            filedNames.add(field.getName().get());
        });
        final RowType rowType = new RowType(rowFieldTypes, Optional.of(filedNames));
        return rowType;
    }
```

And here's how the table looks like: 

|Column|Type|Null|Partition Key|Comment|
|----|----|----|----|----|
|record_time|varchar|True|True|time when user recorded. Not null. client time using client timezone.  like: '23:59:10'|
|record_date|varchar|True|True|date when user recorded. Not null. client date using client timezone. like: '2015-12-13'|
|user_id|varchar|True|True|user neo id in the s3 path|
|tid|varchar|True|False|reserved column. no meaning until now|
|activity_id|varchar|True|False|lesson activity id|
|lesson_id|varchar|True|False|lesson id. unique only when lesson_id and activity_id |
|platform|varchar|True|False|client device platform. ios or android. This column is decided by the file format. android generate flac file, while ios generate m3a file.|
|pbaudio|row(device_model varchar, os_version varchar, app_version varchar, record_timezone varchar, record_timestamp varchar, mode varchar)|True|False|NO COMMENT HERE!|
|s3_key|varchar|True|False|full S3 key for the object. you can use this key to get the object through S3 api|
|file_size|bigint|True|False|audio file size in bytes|
|upload_timestamp|timestamp|True|False|timestamp when the audio is uploaded to server. GMT+8 time|

And I use a lazy block loader to load the row type column `pbaudio`, here's the code; 

```java
    @Override
    public void load(LazyBlock block) {
        final S3Object s3Object = this.s3Client.getObject(this.bucketName, this.s3Key);
        if (s3Object != null) {
            final Protoss.PBUserAudio pbUserAudio;
            try {
                pbUserAudio = Protoss.PBUserAudio.parseFrom(s3Object.getObjectContent());
            } catch (IOException ex) {
                throw new PrestoException(StandardErrorCode.INTERNAL_ERROR,
                  "failed parse pb from s3 key: s3://" + this.bucketName + "/" + this.s3Key,
                  ex
                );
            }
            LOG.info("start to get s3 content, key: " + this.s3Key);
            final Block mapBlock = serializeRow(pbUserAudio);
            block.setBlock(mapBlock);
        }
    }

    private Block serializeRow(Protoss.PBUserAudio pbUserAudio){
        int expectedEntries = calculateEntrySize(pbUserAudio);
        final ImmutableList<Type> fieldTypes = ImmutableList.of(
          VarcharType.VARCHAR,
          VarcharType.VARCHAR,
          VarcharType.VARCHAR,
          VarcharType.VARCHAR,
          VarcharType.VARCHAR,
          VarcharType.VARCHAR
          );
        final BlockBuilder blockBuilder = new InterleavedBlockBuilder(fieldTypes,
          new BlockBuilderStatus(), expectedEntries);
        VarcharType.VARCHAR.writeString(blockBuilder, pbUserAudio.getDeviceModel());
        VarcharType.VARCHAR.writeString(blockBuilder, pbUserAudio.getAppVersion());
        VarcharType.VARCHAR.writeString(blockBuilder, pbUserAudio.getOsVersion());
        VarcharType.VARCHAR.writeString(blockBuilder, "" + pbUserAudio.getRecordTimezone());
        VarcharType.VARCHAR.writeString(blockBuilder, "" +pbUserAudio.getRecordTimestamp());
        VarcharType.VARCHAR.writeString(blockBuilder, "" + pbUserAudio.getMode());
        return blockBuilder.build();
    }

```

**Comment by haitaoyao** [comment]
@haozhun I'm using `0.125`, I found that there's some api changes in `0.131`, and I think I need sometime to merge into 0.131.

**Comment by haitaoyao** [comment]
@haozhun  I've merged to the lastest `0.131`, still the same error: 

```java
java.lang.IllegalArgumentException: position is not valid
	at com.facebook.presto.spi.block.AbstractVariableWidthBlock.checkReadablePosition(AbstractVariableWidthBlock.java:169)
	at com.facebook.presto.spi.block.AbstractVariableWidthBlock.isNull(AbstractVariableWidthBlock.java:157)
	at com.facebook.presto.spi.block.AbstractInterleavedBlock.isNull(AbstractInterleavedBlock.java:288)
	at com.facebook.presto.operator.scalar.RowFieldReference.sliceAccessor(RowFieldReference.java:113)
	at com_facebook_presto_$gen_PageProcessor_48.project_0(Unknown Source)
	at com_facebook_presto_$gen_PageProcessor_48.process(Unknown Source)
	at com.facebook.presto.operator.FilterAndProjectOperator.getOutput(FilterAndProjectOperator.java:110)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:380)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:573)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by haozhun** [comment]
I don't think there's any material change between 0.125 and 0.131 related to `Block` and `BlockBuilder`.

The way you are using LazyBlock doesn't seem right. A lazy block usually represent a column (instead of one row in a column). These two concepts are different: a map, vs a column of only one item which is a map. Their difference is very similar to that between `1` and `ARRAY [1]`.

I had that thought yesterday. However, the stack trace you showed at the beginning should not happen if that is the case because your stacktrace shows that `com_facebook_presto_$gen_PageProcessor_45.project_0` is able to successfully extract an `InterleavedBlock` from the `Block` it's working on and pass it to `RowFieldReference.sliceAccessor`. This is not possible if you made the mistake I mentioned above.

Now, if you are using LazyBlock in a way we don't usually do, it is possible that all the code you presented is correct. The problem lies in the code that is further up.

**Comment by haitaoyao** [comment]
@haozhun I see. It worked after I change the load strategy. Thank you very much.
