### ISSUE TITLE
Transient IndexOutOfBoundsException with columnar_processing_dictionary=true

### ISSUE THREAD

**Issue by raghavsethi** [facebook/presto#4343]
The first time I ran the following query, I received an INTERNAL_ERROR:

```
SELECT a, b, c, COUNT(d) AS ct FROM test_raghavsethi_1 a='ok' GROUP BY a, b, c UNION ALL SELECT a, b, NULL, COUNT(d) AS ct FROM test_raghavsethi_1 WHERE a='ok' GROUP BY a, b; 
```

These session properties were set:
```
columnar_processing=true
columnar_processing_dictionary=true
optimize_hash_generation=false
```

Stack trace:
```
java.lang.ArrayIndexOutOfBoundsException: 204
	at com.facebook.presto.spi.block.DictionaryBlock.getReferencedPositions(DictionaryBlock.java:404)
	at com.facebook.presto.spi.block.DictionaryBlock.<init>(DictionaryBlock.java:88)
	at com_facebook_presto_$gen_PageProcessor_60.projectDictionary_1(Unknown Source)
	at com_facebook_presto_$gen_PageProcessor_60.processColumnarDictionary(Unknown Source)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:247)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:380)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:573)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cberner** [comment]
This is probably the race I fixed in https://github.com/facebook/presto/pull/4342
Can you test it with master?

**Comment by raghavsethi** [comment]
I can try, but the error was transient anyway. We can close this, and reopen if we see it again.
