### ISSUE TITLE
IndexOutOfBounds in AddExchanges

### ISSUE THREAD

**Issue by cberner** [facebook/presto#4485]
```
Caused by: java.lang.IndexOutOfBoundsException: index (-1) must not be negative
        at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:310)
        at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:292)
        at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:65)
        at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:608)
        at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
        at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:210)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitJoin(AddExchanges.java:810)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitJoin(AddExchanges.java:184)
        at com.facebook.presto.sql.planner.plan.JoinNode.accept(JoinNode.java:159)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1103)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitProject(AddExchanges.java:227)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitProject(AddExchanges.java:184)
        at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1103)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitAggregation(AddExchanges.java:271)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitAggregation(AddExchanges.java:184)
        at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:180)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1103)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitProject(AddExchanges.java:227)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitProject(AddExchanges.java:184)
        at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1103)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitTopN(AddExchanges.java:530)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitTopN(AddExchanges.java:184)
        at com.facebook.presto.sql.planner.plan.TopNNode.accept(TopNNode.java:112)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1103)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:233)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:184)
        at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
        at com.facebook.presto.sql.planner.optimizations.AddExchanges.optimize(AddExchanges.java:146)
        at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:103)
        at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:265)
        at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:244)
        at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:208)
        at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:68)
```

**Comment by martint** [comment]
There's a PR to fix this: https://github.com/facebook/presto/pull/4476
