### ISSUE TITLE
CTAS doesn't work when one partition is being written to by multiple workers

### ISSUE THREAD

**Issue by haozhun** [facebook/presto#4531]
Set up:
```
create table test_hjin_overwrite_5(a bigint, b varchar) with (partitioned_by=array['b']);
insert into test_hjin_overwrite_5 (values
 (100, 'z'), (101, 'z'), (102, 'z'), (103, 'z'), (104, 'z'), (105, 'z'), (106, 'z'), (107, 'z'), (108, 'z'), (109, 'z'),
 (110, 'z'), (111, 'z'), (112, 'z'), (113, 'z'), (114, 'z'), (115, 'z'), (116, 'z'), (117, 'z'), (118, 'z'), (119, 'z'),
 (120, 'z'), (121, 'z'), (122, 'z'), (123, 'z'), (124, 'z'), (125, 'z'), (126, 'z'), (127, 'z'), (128, 'z'), (129, 'z'),
 (130, 'z'), (131, 'z'), (132, 'z'), (133, 'z'), (134, 'z'), (135, 'z'), (136, 'z'), (137, 'z'), (138, 'z'), (139, 'z'),
 (140, 'z'), (141, 'z'), (142, 'z'), (143, 'z'), (144, 'z'), (145, 'z'), (146, 'z'), (147, 'z'), (148, 'z'), (149, 'z'),
 (150, 'z'), (151, 'z'), (152, 'z'), (153, 'z'), (154, 'z'), (155, 'z'), (156, 'z'), (157, 'z'), (158, 'z'), (159, 'z'),
 (160, 'z'), (161, 'z'), (162, 'z'), (163, 'z'), (164, 'z'), (165, 'z'), (166, 'z'), (167, 'z'), (168, 'z'), (169, 'z'),
 (170, 'z'), (171, 'z'), (172, 'z'), (173, 'z'), (174, 'z'), (175, 'z'), (176, 'z'), (177, 'z'), (178, 'z'), (179, 'z'),
 (180, 'z'), (181, 'z'), (182, 'z'), (183, 'z'), (184, 'z'), (185, 'z'), (186, 'z'), (187, 'z'), (188, 'z'), (189, 'z'),
 (190, 'z'), (191, 'z'), (192, 'z'), (193, 'z'), (194, 'z'), (195, 'z'), (196, 'z'), (197, 'z'), (198, 'z'), (199, 'z'),
 (200, 'z'), (201, 'z'), (202, 'z'), (203, 'z'), (204, 'z'), (205, 'z'), (206, 'z'), (207, 'z'), (208, 'z'), (209, 'z'),
 (210, 'z'), (211, 'z'), (212, 'z'), (213, 'z'), (214, 'z'), (215, 'z'), (216, 'z'), (217, 'z'), (218, 'z'), (219, 'z'),
 (220, 'z'), (221, 'z'), (222, 'z'), (223, 'z'), (224, 'z'), (225, 'z'), (226, 'z'), (227, 'z'), (228, 'z'), (229, 'z'),
 (230, 'z'), (231, 'z'), (232, 'z'), (233, 'z'), (234, 'z'), (235, 'z'), (236, 'z'), (237, 'z'), (238, 'z'), (239, 'z'),
 (240, 'z'), (241, 'z'), (242, 'z'), (243, 'z'), (244, 'z'), (245, 'z'), (246, 'z'), (247, 'z'), (248, 'z'), (249, 'z'),
 (250, 'z'), (251, 'z'), (252, 'z'), (253, 'z'), (254, 'z'), (255, 'z'), (256, 'z'), (257, 'z'), (258, 'z'), (259, 'z'),
 (260, 'z'), (261, 'z'), (262, 'z'), (263, 'z'), (264, 'z'), (265, 'z'), (266, 'z'), (267, 'z'), (268, 'z'), (269, 'z'),
 (270, 'z'), (271, 'z'), (272, 'z'), (273, 'z'), (274, 'z'), (275, 'z'), (276, 'z'), (277, 'z'), (278, 'z'), (279, 'z'),
 (280, 'z'), (281, 'z'), (282, 'z'), (283, 'z'), (284, 'z'), (285, 'z'), (286, 'z'), (287, 'z'), (288, 'z'), (289, 'z'),
 (290, 'z'), (291, 'z'), (292, 'z'), (293, 'z'), (294, 'z'), (295, 'z'), (296, 'z'), (297, 'z'), (298, 'z'), (299, 'z'));
```

```
presto> create table test_hjin_overwrite_6 with (partitioned_by = array['pk']) as select a, 'pk' as pk from test_hjin_overwrite_5 left join (select * from (values -1) t(x)) on a = x;

Query 20160211_000319_00062_tuzi6, FAILED, 95 nodes
Splits: 848 total, 82 done (9.67%)
CPU Time: 0.3s total,   423 rows/s, 15.5KB/s, 20% active
Per Node: 0.0 parallelism,     0 rows/s,    13B/s
Parallelism: 0.1
0:04 [119 rows, 4.37KB] [33 rows/s, 1.22KB/s]

Query 20160211_000319_00062_tuzi6 failed: Target directory for new partition 'Optional[pk=pk]' of table 'di.test_hjin_overwrite_6' already exists: hdfs://dfs41.data.facebook.com:9000/namespace/di/warehouse/269d316177314cd9b16097ede18342db/53da33cdff654c4fb31886e829e045c0/pk=pk
com.facebook.presto.spi.PrestoException: Target directory for new partition 'Optional[pk=pk]' of table 'di.test_hjin_overwrite_6' already exists: hdfs://dfs41.data.facebook.com:9000/namespace/di/warehouse/269d316177314cd9b16097ede18342db/53da33cdff654c4fb31886e829e045c0/pk=pk
        at com.facebook.presto.hive.HivePageSink.createWriter(HivePageSink.java:330)
        at com.facebook.presto.hive.HivePageSink.appendPage(HivePageSink.java:277)
        at com.facebook.presto.spi.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:41)
        at com.facebook.presto.operator.TableWriterOperator.addInput(TableWriterOperator.java:186)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:386)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:580)
        at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
        at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:640)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

It appears to me that this is an incorrect sanity check.

**Comment by maciejgrzybek** [comment]
@haozhun I cannot reproduce this scenario on master with HEAD = bbbb151cbdf4457c2be1d656b78739d47a0d1e4e
Hadoop version: Hadoop 2.6.0-cdh5.4.2
Hive: 1.1.0-cdh5.4.2
HADOOP_USER_NAME=hdfs

Can you provide with more details about your environment? Any options for `Hive`/`Hadoop`?

```sql
presto:default> select count(1) from test_hjin_overwrite_5 former inner join test_hjin_overwrite_6 new on former.a = new.a;
 _col0 
-------
   200 
(1 row)
```

**Comment by haozhun** [comment]
When I filed the bug, I didn't realize special condition is required to trigger this bug. Your comment lead me to investigate a little more.

This bug only happens when temporary path is not used for creating table, which is the case when the file system is S3 (and potentially when a non-default implementation of LocationService is used).
