### ISSUE TITLE
Queries with "IN (NULL)" fail with NullPointerException

### ISSUE THREAD

**Issue by cberner** [facebook/presto#4560]
This is a regression in the 0.137 release
```
select * from (values 1) t(x) where x in (null, 0);
```
fails with
```
Query 20160216_172038_00009_u4q3q failed: null
java.lang.NullPointerException
	at sun.invoke.util.ValueConversions.unboxLong(ValueConversions.java:121)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:649)
	at com.facebook.presto.sql.FunctionInvoker.invoke(FunctionInvoker.java:69)
	at com.facebook.presto.sql.FunctionInvoker.invoke(FunctionInvoker.java:41)
	at com.facebook.presto.sql.planner.DomainTranslator$Visitor.visitComparisonExpression(DomainTranslator.java:369)
	at com.facebook.presto.sql.planner.DomainTranslator$Visitor.visitComparisonExpression(DomainTranslator.java:232)
	at com.facebook.presto.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:91)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.planner.DomainTranslator$Visitor.visitLogicalBinaryExpression(DomainTranslator.java:278)
	at com.facebook.presto.sql.planner.DomainTranslator$Visitor.visitLogicalBinaryExpression(DomainTranslator.java:232)
	at com.facebook.presto.sql.tree.LogicalBinaryExpression.accept(LogicalBinaryExpression.java:73)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.planner.DomainTranslator$Visitor.visitInPredicate(DomainTranslator.java:467)
	at com.facebook.presto.sql.planner.DomainTranslator$Visitor.visitInPredicate(DomainTranslator.java:232)
	at com.facebook.presto.sql.tree.InPredicate.accept(InPredicate.java:55)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.planner.DomainTranslator.fromPredicate(DomainTranslator.java:229)
	at com.facebook.presto.sql.planner.optimizations.WindowFilterPushDown$Rewriter.visitFilter(WindowFilterPushDown.java:149)
	at com.facebook.presto.sql.planner.optimizations.WindowFilterPushDown$Rewriter.visitFilter(WindowFilterPushDown.java:82)
	at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:71)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$146(SimplePlanRewriter.java:75)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:76)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:40)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:24)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:34)
	at com.facebook.presto.sql.planner.optimizations.WindowFilterPushDown.optimize(WindowFilterPushDown.java:79)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:105)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:265)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:244)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:208)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$162(QueuedExecution.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by martint** [comment]
This should have fixed it, but it appears the fix was incomplete: https://github.com/facebook/presto/commit/7f6cf1aeac7a6e1bea3be27682c82e1fe03891d9

**Comment by cberner** [comment]
@erichwang can you look at this?

**Comment by martint** [comment]
Here's the related issue: https://github.com/facebook/presto/issues/4471
