### ISSUE TITLE
Failure in phased scheduler

### ISSUE THREAD

**Issue by cberner** [facebook/presto#4771]
```
java.lang.UnsupportedOperationException: not yet implemented: com.facebook.presto.sql.planner.plan.ExchangeNode
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:282)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:163)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitExchange(PlanVisitor.java:160)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:197)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.processJoin(PhasedExecutionSchedule.java:214)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitJoin(PhasedExecutionSchedule.java:195)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitJoin(PhasedExecutionSchedule.java:163)
	at com.facebook.presto.sql.planner.plan.JoinNode.accept(JoinNode.java:159)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:280)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:163)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitProject(PlanVisitor.java:40)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:280)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:163)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitFilter(PlanVisitor.java:35)
	at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:71)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:280)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:163)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitProject(PlanVisitor.java:40)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:280)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:163)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitProject(PlanVisitor.java:40)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:280)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:163)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitAggregation(PlanVisitor.java:30)
	at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:180)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.processFragment(PhasedExecutionSchedule.java:184)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.lambda$processFragment$478(PhasedExecutionSchedule.java:179)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.processFragment(PhasedExecutionSchedule.java:179)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitRemoteSource(PhasedExecutionSchedule.java:239)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitRemoteSource(PhasedExecutionSchedule.java:163)
	at com.facebook.presto.sql.planner.plan.RemoteSourceNode.accept(RemoteSourceNode.java:75)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:280)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:163)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitExchange(PlanVisitor.java:160)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:197)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:280)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:163)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitAggregation(PlanVisitor.java:30)
	at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:180)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:280)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:163)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitProject(PlanVisitor.java:40)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.processFragment(PhasedExecutionSchedule.java:184)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.lambda$processFragment$478(PhasedExecutionSchedule.java:179)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.processFragment(PhasedExecutionSchedule.java:179)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitRemoteSource(PhasedExecutionSchedule.java:239)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitRemoteSource(PhasedExecutionSchedule.java:163)
	at com.facebook.presto.sql.planner.plan.RemoteSourceNode.accept(RemoteSourceNode.java:75)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:280)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.visitPlan(PhasedExecutionSchedule.java:163)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.processFragment(PhasedExecutionSchedule.java:184)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.lambda$processFragment$478(PhasedExecutionSchedule.java:179)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule$Visitor.processFragment(PhasedExecutionSchedule.java:179)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule.extractPhases(PhasedExecutionSchedule.java:135)
	at com.facebook.presto.execution.scheduler.PhasedExecutionSchedule.<init>(PhasedExecutionSchedule.java:63)
	at com.facebook.presto.execution.scheduler.PhasedExecutionPolicy.createExecutionSchedule(PhasedExecutionPolicy.java:26)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler.schedule(SqlQueryScheduler.java:319)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cberner** [comment]
Opened by mistake, this bug only exists in a branch
